### ISSUE TITLE
ONNX deprecation warnings on import

### ISSUE THREAD

**Issue by ReneeErnst** [onnx/sklearn-onnx#1006]
I've been getting deprecation warnings when importing skl2onnx (1.14.1) that are coming from the onnx package [here](https://github.com/onnx/onnx/blob/86f7744b866a253a4f1286a108f29128509777c0/onnx/cpp2py_export.cc#L239). 

I created a new python environment (3.9.7) and only installed skl2onnx, to replicate the issue. This is my output. 
![Screenshot 2023-07-11 at 5 23 30 PM](https://github.com/onnx/sklearn-onnx/assets/13136940/0519fd3a-abf6-4e19-9211-95a00c4d270d)

Please let me know if you need anything else!

**Comment by xadupre** [comment]
The latest merged PR fixes that issue. We should release it soon.

**Comment by xadupre** [comment]
I'll close the issue. Feel free to reopen it.

**Comment by ReneeErnst** [comment]
Thank you!
