### ISSUE TITLE
TPOT converter implemented

### ISSUE THREAD

**Issue by AimJee** [onnx/sklearn-onnx#1012]
Hi,

I was wondering if in the near future there was the project to add TPOT's converters ? 

I have tried but failed to create a custom converter for <class 'tpot.builtins.stacking_estimator.StackingEstimator'>(https://github.com/EpistasisLab/tpot/blob/master/tpot/builtins/stacking_estimator.py). Could you help me ? 

I wish you a nice day

**Comment by xadupre** [comment]
This estimator is not supporting by skl2onnx but custom converter can be added. You can follow the tutorial here: http://onnx.ai/sklearn-onnx/tutorial_2_new_converter.html.

**Comment by xadupre** [comment]
Closing the issue. Feel free to reopen.
