### ISSUE TITLE
Use onnx graph from PyTorch `torch.onnx.export` in custom converter

### ISSUE THREAD

**Issue by KarelZe** [onnx/sklearn-onnx#1014]
Thanks for your effort on slearn2onnx. 👍 

**Summary**
I have PyTorch models wrapped as a sklearn estimator in my sklearn pipeline. I want to use the onnx graph derived from `torch.onnx.export` as a custom converter for conversion.

**Comprehensive**

My question is related to https://github.com/onnx/sklearn-onnx/issues/597. I have implemented an AutoEncoder in PyTorch, from which I use the encoder for dimensionality reduction. The autoencoder is wrapped in sklearn-compatible wrapper named `AutoEncoderModel`. Similar concept exists with libraries like [`skorch`](https://github.com/skorch-dev/skorch). The wrapper derives from `BaseEstimator`, `TransformerMixin`, `ClassNamePrefixFeaturesOutMixin` . The `fit()` in the `AutoEncoderModel` trains the Autoencoder and `transform()` passes the input through the encoder.

I'm using the following [PyTorch code](https://pytorch.org/docs/stable/onnx.html) to generate the onnx graph for the encoder inside my wrapper `AutoEncoderModel`:
```python
input_names = ["input"] + [
            layer.__class__.__name__ for layer in self.module.encoder[:-1]
]

cache = io.BytesIO()
torch.onnx.export(
            self.module.encoder,
            torch.ones(size=(self.batch_size, n_features_in)),
            cache,
            input_names=input_names,
            output_names=["bottleneck"],
            keep_initializers_as_inputs=False,
            verbose=True,
            opset_version=15,
)
onx = onnx.load_model_from_string(cache.getvalue())
```
My Autoencoder / AutoEncoder/Model has the following structure:
```python
AutoEncoderModel(epochs=2,
                 module=AutoEncoder(
  (encoder): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
  )
  (decoder): Sequential(
    (0): Linear(in_features=20, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=50, bias=True)
  )
))
```
The resulting graph looks like this:
```proto
ir_version: 8
opset_import {
  version: 15
}
producer_name: "pytorch"
producer_version: "2.0.1"
graph {
  node {
    input: "input"
    input: "Linear"
    input: "ReLU"
    output: "/0/Gemm_output_0"
    name: "/0/Gemm"
    op_type: "Gemm"
    attribute {
      name: "alpha"
      type: FLOAT
      f: 1
    }
    attribute {
      name: "beta"
      type: FLOAT
      f: 1
    }
    attribute {
      name: "transB"
      type: INT
      i: 1
    }
...
  name: "torch_jit"
  initializer {
    dims: 30
    dims: 50
    data_type: 1
    name: "Linear"
    raw_data: "!\033(=\013\245\236\275u\021\204;g\301\264\275\"\373\351\275\026\227&\275\3028\250=\324\021\263=\220\221\366\275z\252\002>\3064\362=\331\353\006>\203p\202\274\213\316\307\275T\377\217=Tr\326<g\200\366=m\213\345\274L\250Y=\235f\004>(\252\017;\246k9=\234l\001>\026\330z\274\034n\350\274\340\263\016=C\323\334\274\030\302:<\3716\271=\255\340\302\274z\2276=\231\023\216<\276nn=\217P<=Xi\232\275\0132\360\275\216\377\347=\307E\305=\223\034\351=\314\226T=}Y]
...
  }
```

My goal is now to register a custom converter for `AutoEncoderModel`. I've seen the [CatBoost Example](https://onnx.ai/sklearn-onnx/auto_tutorial/plot_gexternal_catboost.html), where onnx code is generated by the catboost library first and then inserted into the container. PyTorch, however, uses initializers for the weights as visualised above. As per the tutorial it is not supported by `sklearn2onnx`. Is this universally true?

Is there a fast way to load the onnx graph from PyTorch into the converter or do I have to parse the entire graph myself and it to the container? I assume that for the latter, I'd have to reimplement using the [`ModelComponentContainer api`](https://onnx.ai/sklearn-onnx/api_summary.html#concepts).

Thanks for your help.

**Comment by xadupre** [comment]
Did you try the following tutorial http://onnx.ai/sklearn-onnx/tutorial_2_new_converter.html?

**Comment by xadupre** [comment]
Thanks for telling me. I'll add the function add_onnx_graph to sk2onnx. I don't plan to maintain mlprodict anymore since the main feature (the python runtime) was integrated to onnx. It may be useful for other cases.

**Comment by KarelZe** [comment]
@xadupre I guess, that would be really helpful. 👍
