### ISSUE TITLE
Can I convert StandardScaler object to onnx object

### ISSUE THREAD

**Issue by danerlt** [onnx/sklearn-onnx#1018]
I have a Standard Scaler object, I used pickle.dumps to convert it to a scaler.pkl file, I don't want to use the scikit-learn library in my deployed project, can I convert it to a file in onnx format, run it through onnx, if so, what should I do?

**Comment by xadupre** [comment]
Did you try the tutorial: https://onnx.ai/sklearn-onnx/auto_tutorial/plot_abegin_convert_pipeline.html?

**Comment by danerlt** [comment]
@xadupre Yes, I have reviewed the relevant documentation. The documentation supports converting models to ONNX format. I would like to know if StandardScaler can also be converted to ONNX format?

**Comment by xadupre** [comment]
Yes. You can find the list of supported models here: https://onnx.ai/sklearn-onnx/supported.html.
