### ISSUE TITLE
Converting a sklearn TF-IDF model to onnx uses invalid locale on real iOS device

### ISSUE THREAD

**Issue by l3utterfly** [onnx/sklearn-onnx#1019]
Workflow:
1. create a tf-idf classifier using sklearn, on Windows machine
2. convert it to onnx via:

```
model_onnx = convert_sklearn(
    pipeline,
    "tfidf_pipeline",
    initial_types=[("input", StringTensorType([1, 1]))],
    # https://github.com/triton-inference-server/onnxruntime_backend/issues/94#issuecomment-1142065156
    options={LogisticRegression: {"zipmap": False}},
    target_opset=12,
)
```

The output onnx model fails on real iOS devices with the error: `[E:onnxruntime:, inference_session.cc:1644 operator()] Exception during initialization: /Users/runner/work/1/s/onnxruntime/core/providers/cpu/nn/string_normalizer.cc:90 auto onnxruntime::string_normalizer::Locale::Locale(const std::string &)::(anonymous class)::operator()() const Failed to construct locale with name:en_US.UTF-8:collate_byname<char>::collate_byname failed to construct for en_US.UTF-8:Please, install necessary language-pack-XX and configure locales`

**Comment by xadupre** [comment]
It seems an issue for onnxruntime. Can you tell which version are you using? Did you compile yourself, how... Is it possible to install the missing package as mentioned in the error message?

**Comment by l3utterfly** [comment]
Yeah.. upon investigating further, it appears iPhone do not come shipped with default c++ locales. The locale needs to be "en". I opened an issue over at onnxruntime: https://github.com/microsoft/onnxruntime/issues/17017

Also see this stackoverflow post explaining the issue:  https://stackoverflow.com/questions/51949128/c-stdlocaleen-throws-exception-on-ios

So a suggestion would be to allow users to configure the locale for the StringNormaliser phase in the TFIDF pipeline? My current workaround is modifying the source code of `text_vectorizer.py:292` adding a hard-coded locale during each build.

**Comment by xadupre** [comment]
Can you share your modifications? It would not be too difficult to add an option to the converter and specify the locale you need.

**Comment by l3utterfly** [comment]
Sure. This is more of a hack than anything... basically added a hardcoded "locale" before initialising StringNormaliser

<img width="622" alt="image" src="https://github.com/onnx/sklearn-onnx/assets/6970347/752363e4-3713-4233-9174-1a487317eeda">

**Comment by l3utterfly** [comment]
> Is it possible to install the missing package as mentioned in the error message?

You can't install locales on iPhone as far as I know. I tried the workaround specified in the stackoverflow post, it doesn't seem to work due to apps can only modify environment variables AFTER they are loaded. And also being sandbox and whatnot so the changes aren't permanent
