### ISSUE TITLE
File naming convention

### ISSUE THREAD

**Issue by c-bata** [onnx/sklearn-onnx#102]
Hi maintainers!

Thanks for developing this project. I want to make machine learning models using python3 and scikit-learn, then want to run on Go programs using a [golearn](https://github.com/sjwhitworth/golearn) project. I think that ONNX-ML is the best format to pass trained model parameters into Go. I feel this project has a great potential.

BTW, I think that it's better to decide the file-naming convention earlier, because this will be breaking changes.

* *lowercase_with_underscores*: https://github.com/onnx/sklearn-onnx/blob/master/skl2onnx/operator_converters/multilayer_perceptron.py
* *UpperCamelCase*: https://github.com/onnx/sklearn-onnx/blob/master/skl2onnx/operator_converters/AdaBoost.py

I recommend you to use *lowercase_with_underscores* like the most of python projects (including scikit-learn and onnx). Are there your opinions on this?

**Comment by prabhat00155** [comment]
Actually lowercase_with_underscores is recommended by pep8, so we need to rename files that don't align.

**Comment by c-bata** [comment]
Great :+1: It seems to be conflicted with other pull requests (for example, there are 50 file changes in #78). It's difficult when we need to resolve this issue.

**Comment by prabhat00155** [comment]
We can wait for that PR to get merged before changing the filenames then.

**Comment by c-bata** [comment]
This issue is resolved after merging https://github.com/onnx/sklearn-onnx/pull/145 and https://github.com/onnx/sklearn-onnx/pull/144
