### ISSUE TITLE
Convert CustomEncoder to ONNX

### ISSUE THREAD

**Issue by prithivi1** [onnx/sklearn-onnx#1032]
`class CustomEncoderTransformer(BaseEstimator, TransformerMixin):
    def __init__(self, encoder_object):
        self.encoder_object = encoder_object

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        self.X_transformed = X.copy()

        for col in self.X_transformed.keys():
            value = self.X_transformed[col].str.lower().values[0]

            if value in self.encoder_object[col]:
                self.X_transformed[col] = self.encoder_object[col][value]
            elif 'zxzx' in self.encoder_object[col]:
                self.X_transformed[col] = self.encoder_object[col]['zxzx']
            else:
                self.X_transformed[col] = len(self.encoder_object[col])

        return self.X_transformed

encoder_object = {
    '15842000000002559': {'dummy': 1, 'zxzx': 2},
    '00000000000000000': {'abc': 1, 'zxzx': 2}
}

preprocessor = ColumnTransformer(
    transformers=[
        ('encoder1', CustomEncoderTransformer(encoder_object), ['15842000000002559', '00000000000000000']),

    ], 
    remainder='passthrough')

data = {
    '15842000000002559': ['zxzx'],
    '00000000000000000': ['abc']
}

df = pd.DataFrame(data)
out = preprocessor.fit_transform(X=df)
`

This is my python Custom Encoder Script. How can I convert this to ONNX?

**Comment by xadupre** [comment]
You can follow the steps described in the tutorial https://onnx.ai/sklearn-onnx/auto_tutorial/plot_jcustom_syntax.html.
 About your encoder, I would use a [LabelEncoder](https://onnx.ai/onnx/operators/onnx_aionnxml_LabelEncoder.html#l-onnx-docai-onnx-ml-labelencoder). You can look at the converter of [OrdinalEncoder](https://github.com/onnx/sklearn-onnx/blob/main/skl2onnx/operator_converters/ordinal_encoder.py) to see how it is done in the generic case. You could also implements your CustomEncoderTransformer in a way it is very similar to the OrdinalEncoder and use the same converter.
