### ISSUE TITLE
Option zipmap not in gemm for class Kmeans

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [onnx/sklearn-onnx#1043]
I am trying to save a scikit-learn clustering model (or a scikit-learn pipeline which terminates in a clustering model) to onnx, so that I can deploy it to BQ as a BQML "imported model." 

From this [onnx documentation page](https://onnx.ai/sklearn-onnx/supported.html), it looks to me like my only supported clustering algorithm choice is KMeans (or Minibatch Kmeans). That's fine with me.

So I try following [this GCP BQML tutorial](https://cloud.google.com/bigquery/docs/making-predictions-with-sklearn-models-in-onnx-format) for saving an arbitrary scikit-learn pipeline model to ONNX. The GCP provided script contains the following key code and comment:
```
# Disable zipmap as it is not supported in BigQuery ML.
options = {id(pipe): {'zipmap': False}}
```

However, when I run my `convert_sklearn(...)` statement, I'm getting the following error:
```
NameError: Option 'zipmap' not in ['gemm'] for class 'Kmeans'.
```

Can you help me understand what's going on here, and if there's some other way I should be approaching saving a scikit-learn clustering model (Kmeans or other) to onnx? 

Thanks!
Max

**Comment by xadupre** [comment]
The option zipmap is used when the pipeline ends with a classifier. It is then used to remove the final ZipMap operator. If your pipeline ends with a KMeans estimator, you should just drop the options. This exception is raised to let the user know the options is not used or misspelled.

**Comment by xadupre** [comment]
Closing the issue. Feel free to reopen.
