### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.compose', sklearn 0.18

### ISSUE THREAD

**Issue by arielramos97** [onnx/sklearn-onnx#1045]
Python 3.6 installation with the following dependencies.

scipy==0.19.*
numpy==1.12.*
scikit-learn==0.18.*
onnx==1.4.*
skl2onnx==1.4.0

**Scikit-learn** version requirements not included in requirements.txt

**Comment by xadupre** [comment]
We don't plan any new release for python 3.6. Python 3.6 is deprecated. Is it possible to handle these constraints on your side?

**Comment by xadupre** [comment]
Closing the issue. Feel free to reopen.
