### ISSUE TITLE
Intercept issue with Linear Models and Gamma Regressor

### ISSUE THREAD

**Issue by AfonsoSequeira** [onnx/sklearn-onnx#1064]
The Poisson regressor and Gamma regressor classes (these are the ones I checked) display the following problematic behavior:
- if the fit() method is called with fit_intercept=True, the intercept_ attribute is of type np.float64.
- if the fit() method is called with fit_intercept=False, the intercept_ attribute is of primitive type float.

This causes issues with in the operator converters, as the implementation assumes that the intercept object has a "shape" attribute, thus throwing an exception if one tries to fit a model with fit_intercept=False. 
See operator_converters>linear_regressor.py line 201.

Could this be safely resolved by explicitly casting the intercept object  to a np.float64?

**Comment by sdpython** [comment]
Do you have an example I could use as a unittest?

**Comment by AfonsoSequeira** [comment]
Hi, sure, below are two examples, for Poisson regressor and Gamma regressor. At the moment they will both fail as "fit_intercept" is set to False.

`from sklearn.linear_model import GammaRegressor, PoissonRegressor, LogisticRegression
import unittest

if __name__ == "__main__":

    class OnnxUnitTests(unittest.TestCase):
        ##Poisson
        def test_poisson_without_intercept(self):
            model = PoissonRegressor(fit_intercept=False)
            X = np.array([[1.0, 2.0], [2.0, 3.0], [3.0, 4.0], [4.0, 3.0]])
            y = np.array([19.0, 26.0, 33.0, 30.0])
            model.fit(X, y)

            model_onnx = convert_sklearn(
                model,
                "scikit-learn Poisson Regressor without Intercept",
                [("input", FloatTensorType([None, X.shape[1]]))],
            )

            self.assertIsNotNone(model_onnx is not None)

        ## Gamma
        def test_gamma_without_intercept(self):
            model = GammaRegressor(fit_intercept=False)
            X = np.array([[1.0, 2.0], [2.0, 3.0], [3.0, 4.0], [4.0, 3.0]])
            y = np.array([19.0, 26.0, 33.0, 30.0])
            model.fit(X, y)

            model_onnx = convert_sklearn(
                model,
                "scikit-learn Gamma Regressor without Intercept",
                [("input", FloatTensorType([None, X.shape[1]]))],
            )

            self.assertIsNotNone(model_onnx is not None)

    unittest.main(exit=False)`

**Comment by xadupre** [comment]
Fixed.
