### ISSUE TITLE
Multi Output Gaussian Regressor 

### ISSUE THREAD

**Issue by liberty-askew** [onnx/sklearn-onnx#1073]
Hello, 

I'm trying to convert a multioutput Gaussian regressor to ONNX format. 
The `gpr_model` is trained on data with 8 input variables and 3 output variables - each represented by a `val_y` in  `sklearn_parser()`.
I understand from the docs that this can be supported but I need to add a parser. 
Following [this tutorial ](https://onnx.ai/sklearn-onnx/auto_tutorial/plot_mcustom_parser.html) and details on[ this similar thread](https://github.com/onnx/sklearn-onnx/issues/212) I have the following code: 
```
def sklearn_parser(scope, model, inputs, custom_parsers=None):
    alias = get_model_alias(type(model))
    this_operator = scope.declare_local_operator(alias, model)

    # inputs
    this_operator.inputs.append(inputs[0])
    
    # outputs
    cls_type = inputs[0].type.__class__
    val_y1 = scope.declare_local_variable("Z.Fx", cls_type())
    val_y2 = scope.declare_local_variable("Z.Fy", cls_type())
    val_y3 = scope.declare_local_variable("Z.Fz", cls_type())
    this_operator.outputs.append(val_y1)
    this_operator.outputs.append(val_y2)
    this_operator.outputs.append(val_y3)
    
    # ends
    return this_operator.outputs

initial_type = [('input', FloatTensorType([None, X_train.shape[1]]))]

update_registered_parser(gpr_model,sklearn_parser)
onnx_model = convert_sklearn(gpr_model, initial_types=initial_type, target_opset=12)
```

The above code gives me the following error:
```
Traceback (most recent call last):
  File "C:\Users\laske\Desktop\Code\sgpsim\libs\cfd_matrix_models\train_model.py", line 274, in <module>
    onnx_model = convert_sklearn(gpr_model, initial_types=initial_type, target_opset=12)
  File "C:\Users\laske\Desktop\Code\sgpsim\.venv\lib\site-packages\skl2onnx\convert.py", line 208, in convert_sklearn
    onnx_model = convert_topology(
  File "C:\Users\laske\Desktop\Code\sgpsim\.venv\lib\site-packages\skl2onnx\common\_topology.py", line 1532, in convert_topology
    topology.convert_operators(container=container, verbose=verbose)
  File "C:\Users\laske\Desktop\Code\sgpsim\.venv\lib\site-packages\skl2onnx\common\_topology.py", line 1350, in convert_operators
    self.call_converter(operator, container, verbose=verbose)
  File "C:\Users\laske\Desktop\Code\sgpsim\.venv\lib\site-packages\skl2onnx\common\_topology.py", line 1133, in call_converter
    conv(self.scopes[0], operator, container)
  File "C:\Users\laske\Desktop\Code\sgpsim\.venv\lib\site-packages\skl2onnx\common\_registration.py", line 27, in __call__
    return self._fct(*args)
  File "C:\Users\laske\Desktop\Code\sgpsim\.venv\lib\site-packages\skl2onnx\operator_converters\gaussian_process.py", line 132, in convert_gaussian_process_regressor       
    if not hasattr(op, "_y_train_std") or op._y_train_std == 1:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

On debugging `op._y_train_std=[1,1,1]` so I assume the error is due to the multioutput and the parser has not worked. I get this same error with or without the parser. 
If I retrain my model to only have 1 output the code works without any issues. 

I want to avoid using[MultiOutputRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.multioutput.MultiOutputRegressor.html)or training the model with single outputs because I do not want to lose the covariance of the output variables.

So my question is - how can I configure this ONNX conversion to accept my model with multioutputs?

Thanks in advance for your help!

**Comment by xadupre** [comment]
Sorry for the delay, this error probably comes from ``op._y_train_std == 1``. I assume ``_y_train_std`` is a numpy array and numpy triggers an error in this case because it cannot guess what needs to be done: is it a true comparison (1 is expected) or an element-wise comparison (comparing each element to 1). The code was implemented to single dimension and it is a float in that case. It requires a code change in skl2onnx. I'm going to create a PR for this case. Feel free to contribute if I'm doing it fast enough for you.

**Comment by xadupre** [comment]
I think you solved this in your PR.

**Comment by xadupre** [comment]
The PR was merged.
