### ISSUE TITLE
Running inference session for a supported sklearn model with custom inference logic

### ISSUE THREAD

**Issue by ospedra** [onnx/sklearn-onnx#1090]
Assuming I have a classic sklearn model RandomForestRegressor which is converted to an onnx model that can be used for an inference session. For my use case it would be extremely helpful to define a custom inference method that uses the output of the RandomForestRegressor and includes some sort of post-processing. Is this possible at all?

Let's take this as a minimal example and train a model. That model should be converted to onnx and the InferenceSession.run should subtract 1 after the prediction for simplicity:

Train the model
```ruby
from skl2onnx import update_registered_converter
from sklearn.ensemble import RandomForestRegressor
from skl2onnx import to_onnx
from skl2onnx.common.data_types import FloatTensorType
from skl2onnx.algebra.onnx_operator import OnnxSubEstimator

model = RandomForestRegressor()
model.fit(some_X, some_Y)
```
Custom shape calculator with n and m being some placeholders and custom converter 
```ruby
def custom_shape_calculator(operator):
    op = operator.raw_operator
    input_type = operator.inputs[0].type.__class__
    input_dim = operator.inputs[0]
    
    output_type = input_type
    output_dim = FloatTensorType(shape=[n,m])

def custom_converter(scope, operator, container):
    op = operator.raw_operator
    opv = container.target_opset
    out = operator.outputs
    
    Y = OnnxSubEstimator(out, 1, op_version=opv, output_names=out[:1])
    Y.add_to(scope, container)
    
update_registered_converter(
    RandomForestRegressor,
    "CustomRF",
    custom_shape_calculator,
    custom_converter,
)

onnx_model = to_onnx(model,initial_types=[("X", FloatTensorType([1, some_X.shape[1]]))])

for_storage = onnx_model.SerializeToString()
 ```
 
The resulting model is pretty much empty and when I store it (with .SerializeToString()) and load it into the onnxruntime InferenceSession it raises 
```ruby
InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Failed to load model with error: /onnxruntime_src/onnxruntime/core/graph/model_load_utils.h:46 void onnxruntime::model_load_utils::ValidateOpsetForDomain(const std::unordered_map<std::__cxx11::basic_string<char>, int>&, const onnxruntime::logging::Logger&, bool, const std::string&, int) ONNX Runtime only *guarantees* support for models stamped with official released onnx opset versions. Opset 21 is under development and support for this is limited. The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain ai.onnx is till opset 20.
 ```
 
 What am I doing wrong or is it possible at all to insert custom 'post-processing' logic into the inference session?
 
 Versions:
 onnxruntime               1.17.0
 skl2onnx                      1.16.0

**Comment by xadupre** [comment]
By default, sklearn-onnx chooses the latest onnx opset available but onnxruntime is usually a couple of opset behind. You need to add ``to_onnx(..., target_opset=18)``, it can be any version between 7 and 20.

**Comment by xadupre** [comment]
I'll close the issue. Feel free to reopen it.
