### ISSUE TITLE
ONNXRuntimeError] : 1 : FAIL : Load model from /kaggle/working/model.onnx failed:Type Error: Type (tensor(double)) of output arg (variable) of node (Co_Concat) does not match expected type (tensor(float)).

### ISSUE THREAD

**Issue by DiTo97** [onnx/sklearn-onnx#1102]
when converting the following model:

```python
from typing import Any
import os 
import pandas as pd
import dask.dataframe as dd
import numpy as np
from warnings import simplefilter

import lightgbm
import numpy
import onnxruntime
import optuna
import skl2onnx
from optuna.pruners import SuccessiveHalvingPruner
from onnxmltools.convert.lightgbm.operator_converters.LightGbm import convert_lightgbm
from skl2onnx import update_registered_converter, to_onnx
from skl2onnx.common import data_types, shape_calculator
from sklearn import (
    base,
    compose,
    datasets,
    ensemble,
    linear_model,
    model_selection,
    multioutput,
    pipeline,
    preprocessing
)
from sklearn.metrics import make_scorer, mean_squared_error
from sklearn.model_selection import GroupKFold
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import MinMaxScaler


def Normalizer() -> list[tuple[str, Any]]:
    return [
        ("cast64", skl2onnx.sklapi.CastTransformer(dtype=numpy.float64)),
        ("scaler", preprocessing.StandardScaler()),
        ("cast32", skl2onnx.sklapi.CastTransformer(dtype=numpy.float32))
    ]


def Embedder(**kwargs: dict[str, Any]) -> list[tuple[str, Any]]:
    return [
        ("basemodel", lightgbm.LGBMRegressor(**kwargs))
    ]


def BoL2EmotionV2(
    backbone_kwargs: dict[str, Any] | None = None,
) -> base.BaseEstimator:
   
    backbone = Embedder(**backbone_kwargs)

    normalizer= Normalizer()
    
    model = pipeline.Pipeline([*normalizer, *backbone])

    return multioutput.MultiOutputRegressor(model)
```

to ONNX with the following conversion code:

```python
update_registered_converter(
    lightgbm.LGBMRegressor,
    "LightGbmLGBMRegressor",
    shape_calculator.calculate_linear_regressor_output_shapes,
    convert_lightgbm,
    options={"split": None},
)

sample = X

exported = to_onnx(
    model,
    X=numpy.asarray(sample).astype(numpy.float32),
    name="BoL2emotion",
    target_opset={"": 19, "ai.onnx.ml": 2}
)

with open("model.onnx", "wb") as f:
    f.write(exported.SerializeToString())
```

the inference session from the exported model works just fine and is well calibrated with the original model:

```python
modelengine = onnxruntime.InferenceSession(
   exported.SerializeToString(), providers=["CPUExecutionProvider"]
)
```

but loading the model from file results in the error in the title; what might be the problem?

```python
model = onnx.load("/kaggle/working/model.onnx")
```

or

```python
modelengine = onnxruntime.InferenceSession(
   "model.onnx", providers=["CPUExecutionProvider"]
)
```

**Comment by xadupre** [comment]
I assume ``model = BoL2EmotionV2()``?

**Comment by DiTo97** [comment]
> ```python
> BoL2EmotionV2
> ```

@xadupre that's right, if I forgot to mention it

**Comment by xadupre** [comment]
I tried to replicate but it seems to work for me. The code I wrote is here: #1103. Feel free to add comment if I did something wrong.

**Comment by DiTo97** [comment]
@xadupre, appreciate the code replication.

The code you wrote works for me as well, likely didn't do a great job at explaining it in the original post.

The problem arises when we save the exported model to a .onnx file and try to instantiate the inference session from the exported file at a later time.

To be clearer, snippet 1 works, snippet 2 does not:
```python
.
.
.

exported = to_onnx(model, ...)

modelengine = onnxruntime.InferenceSession(
    exported.SerializeToString(), providers=["CPUExecutionProvider"]
)
```

```python
.
.
.

exported = to_onnx(model, ...)

with open("model.onnx", "wb") as f:
    f.write(exported.SerializeToString())

modelengine = onnxruntime.InferenceSession(
   "model.onnx", providers=["CPUExecutionProvider"]
)
```

**Comment by xadupre** [comment]
I tried to replicate but it still working for me. Saving the model on disk should not change anything. The error comes from shape_inference. This is the model I get.

![image](https://github.com/onnx/sklearn-onnx/assets/22452781/0fe8ea16-3630-4a8f-82e5-a6b628292b97)

Can you run the updated unit test? I need to know the version you are using as well (onnx, scikit-learn onnxmltools, lightgbm, onnxruntime)

**Comment by DiTo97** [comment]
@xadupre will try replicating the unit test in our own environment; will let you know ASAP!

@andreaGiacolono is in charge of the experiments

**Comment by andreaGiacolono** [comment]
Hi @xadupre, I replicated the unit test and it gave me this error message:

/root/ (unittest.loader._FailedTest) ... ERROR
======================================================================
ERROR: /root/ (unittest.loader._FailedTest)
----------------------------------------------------------------------
AttributeError: module '__main__' has no attribute '/root/'
----------------------------------------------------------------------
Ran 1 test in 0.004s
FAILED (errors=1)


An exception has occurred, use %tb to see the full traceback.
SystemExit: True


/opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


There are the versions:
onnx                                     1.16.1
scikit-learn                          1.2.2
lightgbm                               4.2.0
onnxmltools                         1.12.0
onnxruntime                         1.18.0

**Comment by xadupre** [comment]
I forgot to ask about the version of numpy. Did you run just one test or a couple of them? It seems the way you run the test is not right. Can you do ``pytest <test_file>``?

**Comment by andreaGiacolono** [comment]
The numpy version is 1.26.4, i copied this code:

```
import unittest
import packaging.version as pv
from onnxruntime import __version__ as ort_version
from sklearn.utils._testing import ignore_warnings
from sklearn.exceptions import ConvergenceWarning

@unittest.skipIf(
    pv.Version(ort_version) < pv.Version("1.17.3"),
    reason="opset 19 not implemented",
)
@ignore_warnings(category=(ConvergenceWarning, FutureWarning))
def test_issue_1102(self):
    from typing import Any
    from sklearn.datasets import make_regression
    import lightgbm
    import numpy
    import onnxruntime
    import skl2onnx
    from onnx.reference import ReferenceEvaluator
    from onnxmltools.convert.lightgbm.operator_converters.LightGbm import (
        convert_lightgbm,
    )
    from skl2onnx import update_registered_converter, to_onnx
    from skl2onnx.common import shape_calculator
    from sklearn import base, multioutput, pipeline, preprocessing

    def Normalizer() -> list[tuple[str, Any]]:
        return [
            ("cast64", skl2onnx.sklapi.CastTransformer(dtype=numpy.float64)),
            ("scaler", preprocessing.StandardScaler()),
            ("cast32", skl2onnx.sklapi.CastTransformer(dtype=numpy.float32)),
        ]

    def Embedder(**kwargs: dict[str, Any]) -> list[tuple[str, Any]]:
        return [("basemodel", lightgbm.LGBMRegressor(**kwargs))]

    def BoL2EmotionV2(
        backbone_kwargs: dict[str, Any] | None = None,
    ) -> base.BaseEstimator:
        backbone = Embedder(**(backbone_kwargs or {}))
        normalizer = Normalizer()
        model = pipeline.Pipeline([*normalizer, *backbone])
        return multioutput.MultiOutputRegressor(model)

    model = BoL2EmotionV2()
    X, y = make_regression(100, n_features=4, n_targets=2)
    model.fit(X, y)

    update_registered_converter(
        lightgbm.LGBMRegressor,
        "LightGbmLGBMRegressor",
        shape_calculator.calculate_linear_regressor_output_shapes,
        convert_lightgbm,
        options={"split": None},
    )

    sample = X.astype(numpy.float32)

    exported = to_onnx(
        model,
        X=sample,
        name="BoL2emotion",
        target_opset={"": 19, "ai.onnx.ml": 2},
    )
    expected = model.predict(sample)

    ref = ReferenceEvaluator(exported)
    got = ref.run(None, dict(X=sample))[0]
    numpy.testing.assert_allclose(expected, got, 1e-4)

    sess = onnxruntime.InferenceSession(
        exported.SerializeToString(), providers=["CPUExecutionProvider"]
    )
    got = sess.run(None, dict(X=sample))[0]
    numpy.testing.assert_allclose(expected, got, 1e-4)


if __name__ == "__main__":
    unittest.main(verbosity=2)
```

Maybe I took the wrong code. We're running this on kaggle, I don't know if it could depend on this

**Comment by andreaGiacolono** [comment]
Hi @xadupre, we ran the test on the same environment of the training pipeline and, except for some warnings, it passed. We tried to run again the InferenceSession with the original exported model but it failed with the same error as before:

`Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /kaggle/working/emotion_model_norm.onnx failed:Type Error: Type (tensor(double)) of output arg (variable) of node (Co_Concat) does not match expected type (tensor(float)).`

Do you have any idea what the problem could be? Otherwise if you have some time we could plan a session to understand what's happening.

**Comment by xadupre** [comment]
scikit-learn using double by default. onnx uses float by default and is strongly typed but the type is used by the converter to guess the output type. You can read this https://onnx.ai/sklearn-onnx/auto_examples/plot_cast_transformer.html, inserting CastTransformer in your pipeline should fix it.

**Comment by andreaGiacolono** [comment]
We tried to run again the export and the InferenceSession and it seems to be working. For now we can close the issue but we continue to monitor. Thank you!

**Comment by xadupre** [comment]
:)
