### ISSUE TITLE
Docs pages broken

### ISSUE THREAD

**Issue by syzonyuliia** [onnx/sklearn-onnx#1112]
Hi. I am trying to access the Docs page for sklearn-onnx (https://onnx.ai/sklearn-onnx/), but the pages have been broken since at least Monday, June 17th. I have tried both Safari and Chrome on a Mac, but the problem persists. I am attaching a screenshot for your reference. Thanks!
<img width="1187" alt="image" src="https://github.com/onnx/sklearn-onnx/assets/92266161/7e73a793-7b7a-40d1-9515-765741073be4">

**Comment by xadupre** [comment]
Working on it. Sorry for the inconvenience.

**Comment by xadupre** [comment]
Fixed.
