### ISSUE TITLE
Missing Shape Calculator for econml.grf.classes.CausalForest

### ISSUE THREAD

**Issue by cynthiaZV** [onnx/sklearn-onnx#1114]
Traceback (most recent call last):
  File "/path/to/zzt/script/pangolin_onnx.py", line 38, in <module>
    onnx_model = convert_sklearn(grf_loaded, initial_types=initial_type)
  File "/path/to/anaconda3/lib/python3.9/site-packages/skl2onnx/convert.py", line 206, in convert_sklearn
    onnx_model = convert_topology(
  File "/path/to/anaconda3/lib/python3.9/site-packages/skl2onnx/common/_topology.py", line 1533, in convert_topology
    topology.convert_operators(container=container, verbose=verbose)
  File "/path/to/anaconda3/lib/python3.9/site-packages/skl2onnx/common/_topology.py", line 1350, in convert_operators
    self.call_shape_calculator(operator)
  File "/path/to/anaconda3/lib/python3.9/site-packages/skl2onnx/common/_topology.py", line 1165, in call_shape_calculator
    operator.infer_types()
  File "/path/to/anaconda3/lib/python3.9/site-packages/skl2onnx/common/_topology.py", line 631, in infer_types
    raise MissingShapeCalculator(
skl2onnx.common.exceptions.MissingShapeCalculator: Unable to find a shape calculator for type '<class 'econml.grf.classes.CausalForest'>'.
It usually means the pipeline being converted contains a
transformer or a predictor with no corresponding converter
implemented in sklearn-onnx. If the converted is implemented
in another library, you need to register
the converted so that it can be used by sklearn-onnx (function
update_registered_converter). If the model is not yet covered
by sklearn-onnx, you may raise an issue to
https://github.com/onnx/sklearn-onnx/issues
to get the converter implemented or even contribute to the
project. If the model is a custom model, a new converter must
be implemented. Examples can be found in the gallery.: 
Steps to Reproduce:
Load a CausalForest model using econml.
Attempt to convert the model to ONNX format using sklearn-onnx.
Expected Behavior: The CausalForest model should be successfully converted to ONNX format.
Environment:
econml version: [0.14.0]
scikit-learn  version: [1.1.3]
Python version: [3.9.12]
Additional Context: It appears that there is no shape calculator implemented for the CausalForest type in sklearn-onnx. Please provide support for this model or guide on how to implement a custom converter.
Thank you!

**Comment by xadupre** [comment]
Every model outside scikit-learn is out of scope for this package but you may register your own converters if one if your estimator is inserted into a pipeline. See https://onnx.ai/sklearn-onnx/auto_tutorial/plot_icustom_converter.html or https://onnx.ai/sklearn-onnx/auto_tutorial/plot_jcustom_syntax.html.

**Comment by xadupre** [comment]
I'll close the issue. Feel free to reopen it.
