### ISSUE TITLE
What does zipmap, raw_scores, output_class_labels, nocl mean for a Regressor?

### ISSUE THREAD

**Issue by ogencoglu** [onnx/sklearn-onnx#1120]
In your docs, you explain the logic of these things in the context of Classifiers but the list of available options at the end also list Regressors. What do these mean for Regressors?

https://onnx.ai/sklearn-onnx/auto_tutorial/plot_dbegin_options.html

**Comment by xadupre** [comment]
They don't mean anything and should not be available except raw_scores in rare occasion.

**Comment by ogencoglu** [comment]
So the docs are not up to date or what?

![image](https://github.com/user-attachments/assets/fd73e848-9e8f-4f4b-8e17-00be59053669)

**Comment by xadupre** [comment]
HistGradientBoostingRegressor looks wrong. I'll check about that but the rest looks ok to me.

**Comment by xadupre** [comment]
I'll close the issue. I'll update the documentation soon.
