### ISSUE TITLE
Multi label classifier (OneVsRestClassifier) normalization

### ISSUE THREAD

**Issue by bambi2511** [onnx/sklearn-onnx#113]
Hi,

I am working on a multilabel pipeline (not multiclass): classifier may have multiple outputs.

## sklearn pipeline

I use OneVsRestClassifier on a LogisticRegression as a last step on a sklearn pipeline to get a multi-label classifier (not multiclass: my classifier may predict 0 classes, 1 class or several classes)

When I use predict_proba on my pipeline, I am able to get probabilities for each class, each probability of a class is independant from the one of another class.

```python
pipeline3 = Pipeline(steps=[('tfidf', TfidfVectorizer(input='content', analyzer='word',
                                                     min_df=5, max_df=0.5, ngram_range=(1, 1), lowercase=True)),
                           ('best', TruncatedSVD(n_components=50)),
                           ('lr', OneVsRestClassifier(LogisticRegression(penalty='l1',
                                                      solver='liblinear',
                                                      class_weight='balanced',
                                                      fit_intercept=True)))])
pipeline3.fit(X_train_preprocessed, y_train)
pipeline3.predict_proba(X_train_preprocessed.reshape(-1, 1)[0])
```
outputs array([[0.6818949 , 0.38450937, 0.39627797]]) 

- Class 0 is selected (>.5)
- Class 1 and 2 are not selected (< .5)

## Conversion to onnx

When I convert this pipeline with onnx, (convert_sklearn), these probabilities are normalized to sum to one (one vs rest classifier)

```python
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import StringTensorType

seps = {TfidfVectorizer: {"sep": [' ']}}
model3_onnx = convert_sklearn(pipeline3, name="tfidf",
                              initial_types=[("input", StringTensorType([1, 1]))],
                              options=seps)

with open("pipeline3_tfidf.onnx", "wb") as f:
    f.write(model3_onnx.SerializeToString())

# Inference session
import onnxruntime as rt

sess = rt.InferenceSession("pipeline3_tfidf.onnx")
inputs = {'input': X_train_preprocessed.reshape(-1, 1)[0]}
pred_onx = sess.run(None, inputs)
# print("predict", pred_onx[0])
print("predict_proba", pred_onx[1])
```
outputs [{0: 0.44900158047676086, 1: 0.2634965181350708, 2: 0.28750190138816833}]

I get a multiclass classifier (It corresponds to sklean output that was normalized afterwards).

I did not see any option within sklearn-onnx to bypass normalization step

## Calculation graph print and attempt to change outputs

Therefore I attempted to change the output of the calculation graph to get calculaitions before normalization step ('concatenated' step if I am right)

![model3_onnx dot](https://user-images.githubusercontent.com/31990506/56885801-a09af480-6a6d-11e9-9e55-f4aa68013be8.png)

```python
onnx_helper.select_model_inputs_outputs(model3_onnx, 'concatenated')

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-30-5926ab7e7f40> in <module>
----> 1 onnx_helper.select_model_inputs_outputs(model3_onnx, 'concatenated')

~/environment/default/lib/python3.7/site-packages/skl2onnx/helpers/onnx_helper.py in select_model_inputs_outputs(model, outputs, inputs)
    108             nb += 1
    109             for inp in node.input:
--> 110                 if mark_var[inp] == 1:
    111                     continue
    112                 mark_var[inp] = 1

KeyError: 'transform_matrix'
```

But it did not work out (Besides, if I cannot get a node to be an output as soon as I go after SVD step)

I suppose I am doing something wrong but I can't figure out what ?

Any help would be appreciated.

Regards,

Francois

**Comment by xadupre** [comment]
I created PR #142 which converts the classifier in case of multilabels. The converter also produces the labels. That should address your issue.

**Comment by bambi2511** [comment]
Thanks Xavier,

I tested it, and it works as expected, great !

Regards,

Francois
