### ISSUE TITLE
numpy>=2.0.0 leads to AttributeError: module 'numpy' has no attribute 'NAN'

### ISSUE THREAD

**Issue by VikWeg** [onnx/sklearn-onnx#1143]
It appears that some places (e.g. [here](https://github.com/onnx/sklearn-onnx/blob/f41ffd857fac779378682c6bd4e3cfcf46c588cf/skl2onnx/operator_converters/power_transformer.py#L107)) in sklearn2onnx are not compatible with numpy>=2.0.0 since 2.0.0 removed the np.NAN alias for np.nan.

I could resolve the issue by downgrading numpy, but it would be nice to be able to use sklearn2onnx along the latest numpy version.

**Comment by xadupre** [comment]
We just released a new version. The constrainsts should have disappeared.

**Comment by xadupre** [comment]
https://github.com/onnx/sklearn-onnx/pull/1148
