### ISSUE TITLE
ONNX installed from source (v1.5) test failures

### ISSUE THREAD

**Issue by vinitra** [onnx/sklearn-onnx#115]
While editing the CI build files (#114), I found a few errors that cropped up in the "onnx-git" checks for Linux. As these are upcoming opset 10 changes, I recovered the build by disabling them in the PR, but wanted to let the contributors know for a future fix.

Error: Node:StringNormalizer No Op or Function registered for StringNormalizer with domain_version of 9
- SklearnPipelineTfidfTransformer

Error: Node:TopK Node (TopK) has input size 2 not in range [min=1, max=1].
- CustomTransformerTSNEkNN-OneOffArray
- CustomTransformerTSNEkNNCustomParser-OneOffArray

**Comment by xadupre** [comment]
It seems to be fixed in the last version. CI now includes ONNX==1.5 and onnxruntime==0.4.0
