### ISSUE TITLE
Making a prediction with onnx runtime on a string input

### ISSUE THREAD

**Issue by embicks** [onnx/sklearn-onnx#125]
I am trying to make predictions on text from a sklearn pipeline with a tfidf vectorizer that has been packaged as ONNX. I am able to write out and read in the model but when I make the prediction I get the error: "Method run failed due to: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Missing required input: float_input". 

'''
#convert pipeline into onnx
model_onnx = convert_sklearn(pipeline, "tfidf",
                             initial_types=[("str_input", StringTensorType([1, 2000]))])

with open("pipeline_emails.onnx", "wb") as f:
     f.write(onx.SerializeToString())

#make predictions on test data
sess = rt.InferenceSession("pipeline_emails.onnx")
pred_onx = sess.run(None, {"str_input": test_df})[0]
print("predict", pred_onx[0])
print("predict_proba", pred_onx[1])
'''

**Comment by xadupre** [comment]
Your example is confusing because you convert a pipeline into **model_onnx** but you save variable **onx**. I suspect the file you load is coming from another pipeline. You don't need to save the onnx model into a file. You can just write ``rt.InferenceSession(model_onnx.SerializeToString())``.

**Comment by embicks** [comment]
True, I have fixed that but when I run:

model_onnx = convert_sklearn(pipeline, "tfidf",
                             initial_types=[("input", StringTensorType([1, 2000]))])
sess = rt.InferenceSession(model_onnx.SerializeToString())

I get the error RuntimeError: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for the node StringNormalizer:StringNormalizer(10)

**Comment by xadupre** [comment]
You need to the nightly build of onnxruntime: https://test.pypi.org/project/ort-nightly/.
