### ISSUE TITLE
RandomForestRegressor converter prediction mismatch with Scikit output

### ISSUE THREAD

**Issue by prabhat00155** [onnx/sklearn-onnx#166]
data = load_diabetes()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)
model = RandomForestRegressor().fit(X_train, y_train)

onnx_model = convert_sklearn(model, 'lr', [('input', FloatTensorType(X_test.shape))])
save_model(onnx_model, 'lr.onnx')
sess = InferenceSession('lr.onnx')
res = sess.run(None, input_feed={'input': X_test.astype(np.float32)})

print(np.mean(np.isclose(model.predict(X_test), list(map(lambda x: x[0], res[0])))))

>> 0.9411764705882353

With n_estimators=3 however, prediction matches go upto 0.99.

**Comment by xadupre** [comment]
This should be fixed by PR #237. Can you confirm?

**Comment by prabhat00155** [comment]
Yes, it has been fixed now. Thanks!
