### ISSUE TITLE
How to populate onnx model with custom meta data map ?

### ISSUE THREAD

**Issue by ac4922** [onnx/sklearn-onnx#214]
I have an array which I intend to append in the onnx file itself. 

In my opninion,  onnxruntime provides an option to retrieve custom meta data map/

from onnxruntime import InferenceSession
sess = InferenceSession(example)
meta = sess.get_modelmeta()
print("custom_metadata_map={}".format(meta.custom_metadata_map))
source - https://microsoft.github.io/onnxruntime/auto_examples/plot_metadata.html#sphx-glr-auto-examples-plot-metadata-py

However, it is always populated empty. My goal is to append some custom_metadata when I convert a scikit learn model to onnx which is available when the onnx is read by onnxruntime. 

Please suggest if that is possible and how.

**Comment by prabhat00155** [comment]
The metadata information actually comes from onnxruntime. Could you file an issue with onnxruntime: https://github.com/microsoft/onnxruntime, they should be able to help you with this?

**Comment by ac4922** [comment]
@prabhat00155  I opened this in onnxruntime, and they want me to open here. 

The information comes from onnxruntime, but that needs to be set while converting the model to the ONNX format. In this use case, I am using sklearn to onnx converter, hence I opened this here. 

In my use case, I currently have a pickle file which carries some additional information. I would want to know if that could be serialized in the model itself using model metadatamap.

Thanks

**Comment by prabhat00155** [comment]
@xadupre could clarify this.

**Comment by prabhat00155** [comment]
By the way, this is the issue reported in onnxruntime: https://github.com/microsoft/onnxruntime/issues/1315.

**Comment by xadupre** [comment]
skl2onnx does not add any metadata but you can do it we module onnx once the model is converted. It is a list of key value pair where key and value are strings.

```
meta = model_onnx.metadata_props.add()
meta.key = "key_meta"
meta.value = "value_meta"
print(model_onnx.metadata_props[0])
```

You need to do that after converting and before saving the ONNX model.

**Comment by xadupre** [comment]
Closing the issue. Feel free to reopen if the proposed solution does not fit your needs.

**Comment by blakechi** [comment]
> skl2onnx does not add any metadata but you can do it we module onnx once the model is converted. It is a list of key value pair where key and value are strings.
> 
> ```
> meta = model_onnx.metadata_props.add()
> meta.key = "key_meta"
> meta.value = "value_meta"
> print(model_onnx.metadata_props[0])
> ```
> 
> You need to do that after converting and before saving the ONNX model.

Just to add supplemental information. If want to add more than two, one have to call `meta = model_onnx.metadata_props.add()` again. E.g.:
```python
meta = model_onnx.metadata_props.add()
meta.key = "key_meta_1"
meta.value = "value_meta_1"

meta = model_onnx.metadata_props.add()
meta.key = "key_meta_2"
meta.value = "value_meta_2"
```
