### ISSUE TITLE
Does Batch predictions support for KNeighborsClassifier in onnx ?

### ISSUE THREAD

**Issue by yeyinthtoon** [onnx/sklearn-onnx#215]
`from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import numpy
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType
import onnxruntime as rt

iris = load_iris()
X, y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y)
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X_train, y_train)
neigh.predict(X_test)

initial_type = [('float_input', FloatTensorType([1, 4]))]
onx = convert_sklearn(neigh, initial_types=initial_type)
with open("knn_iris.onnx", "wb") as f:
  f.write(onx.SerializeToString())

sess = rt.InferenceSession("knn_iris.onnx")
input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
sess.run([label_name], {input_name: X_test.astype(numpy.float32)})`
It produce the following error.
**RuntimeError: Method run failed due to: [ONNXRuntimeError] : 1 : GENERAL ERROR : ..\onnxruntime\core/providers/cpu/math/element_wise_ops.h:349 onnxruntime::BroadcastIterator::Append axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 38 by 112**
Although the above error is produced with batch inference, it successfully return the prediction for single data input.
`sess.run([label_name], {input_name: numpy.atleast_2d(X_test[0]).astype(numpy.float32)})`

**Comment by xadupre** [comment]
Not yet, but we plan to fix it.

**Comment by xadupre** [comment]
It is not merged yet but the PR is ready: #293.

**Comment by xadupre** [comment]
The PR has been merged. I'll close the issue.
