### ISSUE TITLE
Fix wrong parameter name in OneHotEncoder converter

### ISSUE THREAD

**Issue by scnakandala** [onnx/sklearn-onnx#221]
In https://github.com/onnx/sklearn-onnx/blob/master/skl2onnx/operator_converters/one_hot_encoder.py#L151 mutiple should be multiple

**Comment by prabhat00155** [comment]
Thanks for reporting this. I had created an issue on OHE previously, which includes this: https://github.com/onnx/sklearn-onnx/issues/165.
