### ISSUE TITLE
min and max are now arguments and not parameters for operator Clip in ONNX opset=11

### ISSUE THREAD

**Issue by xadupre** [onnx/sklearn-onnx#245]

**Comment by xadupre** [comment]
This is an issue for onnxconverter-common https://github.com/microsoft/onnxconverter-common/issues/17.

**Comment by prabhat00155** [comment]
This issue has been fixed by https://github.com/onnx/sklearn-onnx/pull/289 and https://github.com/onnx/sklearn-onnx/pull/284.
