### ISSUE TITLE
skl2onnx converter for OrdinalEncoder

### ISSUE THREAD

**Issue by shihclin** [onnx/sklearn-onnx#249]
Hi,

I am currently using ColumnTransformer which includes an Ordinal Encoder to encode categorical features. However, it looks like there is not an available converter for ordinal encoder, am I correct? If so, is there any workaround? Thanks!

**Comment by prabhat00155** [comment]
Can't you use OneHotEncoder?

**Comment by shihclin** [comment]
Yes, just also want to consider other choices like Ordinal or Label encoder. For the LabelEncoder, there's a class issue taking different amount of args. The OneHotEncoder works fine and I am able to convert it successfully.

**Comment by shihclin** [comment]
Oh, I think the issue happens in the pipeline stage: https://stackoverflow.com/questions/46162855/fit-transform-takes-2-positional-arguments-but-3-were-given-with-labelbinarize

Essentially the label encoder is used for the target but not for the feature transformation. I was wanting to use Label Encoder in the pipeline to do the numerical encoding then convert the pipeline to ONNX via the converter. To conclude, I don't think it is the issue happens in the ONNX stage but in the pipeline formation stage.

Thanks still, looking forward to the Ordinal Encoder converter!

**Comment by prabhat00155** [comment]
https://github.com/onnx/sklearn-onnx/pull/267

**Comment by prabhat00155** [comment]
Checked-in OrdinalEncoder converter.
