### ISSUE TITLE
How is the sklearn version managed ?

### ISSUE THREAD

**Issue by alexandreCameron** [onnx/sklearn-onnx#251]
Hi,

Sorry, I'm a newbie with onnx, I'm not sure I understand how the sklearn version is managed by skl2onnx.

My problem is the following:

If I export a sklearn pipeline created on an environment with a version V-sklearn_1 of sklearn and V-onnx_1 of onnx, is it possible to reload the same pipeline on an environment with a version V-sklearn_2 of sklearn V-onnx_2 of onnx or can I only use an environment with the same requirements ?

Thank you for taking the time

**Comment by xadupre** [comment]
It is not merged yet but the PR is ready: #293.
