### ISSUE TITLE
Run time error: Parameter name cannot be empty and must be a string.

### ISSUE THREAD

**Issue by varshakirani** [onnx/sklearn-onnx#260]
I am trying to convert sklearn pipeline to onnx and end up getting runtime error. The code looks like this:

`update_registered_converter(XGBClassifier, 'XGBClassifier', calculate_xgboost_classifier_output_shapes, convert_xgboost)`  

`pipeline = Pipeline(steps=[
    ('preprocessor' , preprocessor),
    ('classifier', xgb_model)
])
`

`pipeline.fit(X_train_down, y_train_down, 
             **params_fit)`

`model_onnx = convert_sklearn(pipeline, name='pipeline_xgb', initial_types=inputs)`

The error stacktrace:

![image](https://user-images.githubusercontent.com/3057235/65150573-b2813200-da24-11e9-9deb-2dc46a98aded.png)

Even though I have passed parameter _name="pipeline_xgb"_ I am getting runtime error.

**Comment by varshakirani** [comment]
This issue is related to this:
https://github.com/onnx/onnxmltools/issues/334

**Comment by prabhat00155** [comment]
@xadupre is working on addressing this.

**Comment by xadupre** [comment]
This issue is fixed by #262. A default name is given if not specified.

**Comment by varshakirani** [comment]
Is the fix present in latest release? 
How can I access it?

**Comment by xadupre** [comment]
Not in the latest release, only in the master branch.

**Comment by xadupre** [comment]
This is fixed now.
