### ISSUE TITLE
How can I chain onnx operations stored in .onnx files ? 

### ISSUE THREAD

**Issue by alexandreCameron** [onnx/sklearn-onnx#279]
Hi, 

Sorry, I'm quite new to the package and I have not been able to find how to properly pipe existing operations stored in files. 

I'm trying to version my project by saving separately the pre-processing transformations from the modelling part of my project. 

In practice, I can have multiple models using the same pre-processing transformations. In that case, to make a prediction, I need to reload the different operations and chain them together like 'transfo.onnx' piping its outputs into 'model_1.onnx', 'transfo.onnx' piping its output into 'model_2.onnx' ...  

In a broader scope, is there a way to chain sklearn-onnx steps together to make integrated pipeline like:

``` python
# Input files 
step_onnx_files = [ 
    "step_1.onnx", 
    "step_2.onnx", 
    "step_3.onnx", 
    "step_4.onnx", 
] 

# Operations to chain 
operations = [] 
for step_file in step_files: 
    operations.append(onnx.load(open(step_file, 'rb'))) 

# The chaining operation I'm looking for  
pipeline = chain(operations) 

# Save chained operation 
pipeline_file = 'pipeline.onnx' 
with open(pipeline_file, "wb") as f: 
    f.write(pipeline.SerializeToString())
```

**Comment by prabhat00155** [comment]
Why don't you use Pipeline()(combined with ColumnTransformer())? You can convert your entire scikit pipeline into onnx. 
Anyways, if you want to have multiple steps of your scikit experiment saved into separate onnx files, you may look at this example:

model1 = StandardScaler().fit(X_train)
onnx_model = convert_sklearn(model1, 'm1', [('input', FloatTensorType(X_test.shape))])
save_model(onnx_model, 'm1.onnx')
model2 = Normalizer().fit(model1.transform(X_train), y_train)
onnx_model = convert_sklearn(model2, 'm2', [('input', FloatTensorType(X_test.shape))])
save_model(onnx_model, 'm2.onnx')
model3 = SGDClassifier().fit(model2.transform(model1.transform(X_train)), y_train)
onnx_model = convert_sklearn(model3, 'm3', [('input', FloatTensorType(X_test.shape))])
save_model(onnx_model, 'm3.onnx')

Here, I create a StandardScaler model1, which takes X_train as input. Output of this goes into Normaliser(model2) and finally we have an SGDClassifier(model3). I save these models as separate onnx files: `m1.onnx`, `m2.onnx` and `m3.onnx`.

This is how you can score them:
sess = InferenceSession('m1.onnx')
r1 = sess.run(None, input_feed={'input': X_test.astype(np.float32)})
sess = InferenceSession('m2.onnx')
r2 = sess.run(None, input_feed={'input': r1[0].astype(np.float32)})
sess = InferenceSession('m3.onnx')
r3 = sess.run(None, input_feed={'input': r2[0].astype(np.float32)})

However, this doesn't look pretty and I would suggest you to use Pipeline.

**Comment by alexandreCameron** [comment]
@prabhat00155: thank you for your answer 

> Why don't you use Pipeline()(combined with ColumnTransformer())? 

I would like to version different parts of my pipeline. Transforming raw data to preprocessed data can take time. To speed up training, I usually preprocess the raw data once and then train different models with the same preprocessed data. Once I have selected the best model for my problem, I create a scoring pipeline by piping the transformation and the model. By the way, most of the time the best solution is often an ensemble of models which I train separately and group together to generate a the score.

> This is how you can score them:
> sess = InferenceSession('m1.onnx')
> r1 = sess.run(None, input_feed={'input': X_test.astype(np.float32)})
> sess = InferenceSession('m2.onnx')
> r2 = sess.run(None, input_feed={'input': r1[0].astype(np.float32)})
> sess = InferenceSession('m3.onnx')
> r3 = sess.run(None, input_feed={'input': r2[0].astype(np.float32)})

These lines of code help create the m3(m2(m1()))-scoring pipeline. However, I'll like to go one step further and save this pipeline to onnx format. That way, once it's built, I don't have to keep the piping script, I only have to reload the pipeline to make a prediction.

**Comment by prabhat00155** [comment]
I am not sure if that's possible. May be you should ask this question here: https://github.com/onnx/onnx/issues or https://github.com/Microsoft/onnxruntime/issues.

**Comment by xadupre** [comment]
I started to explore this direction. I'm not sure it works in all cases but my idea was to wrap InferenceSession as scikit transform and then to convert any pipeline containing it (see https://github.com/sdpython/mlprodict/blob/master/_unittests/ut_sklapi/test_onnx2onnx.py#L47, http://www.xavierdupre.fr/app/mlprodict/helpsphinx/gyexamples/plot_grid_search.html).

**Comment by alexandreCameron** [comment]
@xadupre : will try to test your tip which a the files, I hope it interacts properly with the onnx runtime

**Comment by xadupre** [comment]
You can also look into example: http://www.xavierdupre.fr/app/mlprodict/helpsphinx/notebooks/transfer_learning.html#merge-onnx-graphs-in-a-pipeline.

**Comment by xadupre** [comment]
May I close this issue?

**Comment by alexandreCameron** [comment]
@xadupre , sorry for the delay, I'm closing the issue
