### ISSUE TITLE
Support for installing with conda

### ISSUE THREAD

**Issue by sgreene** [onnx/sklearn-onnx#287]
sklearn-onnx can be installed with pip. It would be nice if it could also be installed with conda. Even trying to build a conda recipe using `conda skeleton pypi skl2onnx` fails because the source url cannot be found. I'm assuming only a binary exists in the pypi repo?

**Comment by prabhat00155** [comment]
@wenbingl @xadupre What do you think about this request?

**Comment by prabhat00155** [comment]
@sgreene Any particular reason you want to install it with conda? Even if you are using Anaconda, you can still use pip to install it.

**Comment by y2kbugger** [comment]
Sometimes conda is the sole method for getting packages reliably to a large number of developers.

**Comment by jonaphin** [comment]
Pinging to ask if there are any efforts underway to support skl2onnx in conda.

**Comment by xadupre** [comment]
I updated the recent 2 days ago and I released a Wheel and a file .tar.gz. Let me know if that works for you.
