### ISSUE TITLE
Output Shape

### ISSUE THREAD

**Issue by XciD** [onnx/sklearn-onnx#312]
Hello,

I've followed the tutorial to Convert your scikit-learn model into ONNX,

If I understand well, the shape `[None, 4]` means that the first dimension is dynamic. In order to batch calls to the model.

The thing I don't understand is why the output tensor has a shape of `[1]` and not `[None]`

```python
input name='float_input' and shape=[None, 4]
NodeArg(name='output_label', type='tensor(int64)', shape=[1])
```

**Comment by prabhat00155** [comment]
Can you give me link to the tutorial? I don't use output shape when converting models, so I'll need to look at the exact code.

**Comment by XciD** [comment]
I've used this one, 

I've just replace: 
```
initial_type = [('float_input', FloatTensorType([1, 4]))]
``` 
to
```
initial_type = [('float_input', FloatTensorType([None, 4]))]
```

Seems like the first one don't work.
```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: float_input for the following indices
 index: 0 Got: 38 Expected: 1
 Please fix either the inputs or the model.
```

**Comment by prabhat00155** [comment]
I don't see a link in your message, are you using this: http://onnx.ai/sklearn-onnx/?
Yes, we need to use _None_ for dynamic number of inputs because of changes in latest onnxruntime.

**Comment by XciD** [comment]
Yes it’s this one. 
Yes I understood the None as input that create the dynamic shape. 

But the 1 as output should then be None ? As it’s a scalar output with a dynamic shape also ?

**Comment by prabhat00155** [comment]
This is the correct example:

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
iris = load_iris()
X, y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y)
clr = RandomForestClassifier()
clr.fit(X_train, y_train)

# Convert into ONNX format with onnxmltools
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType
initial_type = [('float_input', FloatTensorType([None, 4]))]
onx = convert_sklearn(clr, initial_types=initial_type)
with open("rf_iris.onnx", "wb") as f:
    f.write(onx.SerializeToString())

# Compute the prediction with ONNX Runtime
import onnxruntime as rt
import numpy
sess = rt.InferenceSession("rf_iris.onnx")
input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
pred_onx = sess.run([label_name], {input_name: X_test.astype(numpy.float32)})[0]

Replace 1 -> None in input shape. I don't see output shape in this example, may be you used a different one. Can you paste your complete code here? Sorry, I have never used output shape before.

**Comment by XciD** [comment]
Yes you are right, this is the code.

Then you can print the onnx input / outputs and you will see the i/o shape.
```
print("input name='{}' and shape={}".format(
    sess.get_inputs()[0].name, sess.get_inputs()[0].shape))
print("output name='{}' and shape={}".format(
    sess.get_outputs()[0].name, sess.get_outputs()[0].shape))
```
will print:
```
input name='float_input' and shape=[1, 4]
output name='output_label' and shape=[1]
```

I'm not setting up the output shape, just displaying it

**Comment by prabhat00155** [comment]
I see what you mean, I'll mark this as a bug and debug this further.

**Comment by XciD** [comment]
Great. 

If you give me some pointer I be glad to help you

**Comment by xadupre** [comment]
It seems a bug in onnxruntime and onnx (see #323), it works for regressors but fails for classifiers.
