### ISSUE TITLE
Deviations between the predicted probabilities of sklearn and ONNX runtime

### ISSUE THREAD

**Issue by PatrickSager** [onnx/sklearn-onnx#324]
Hi all

Using skl2onnx 1.6:
I've trained an AdaBoost model on the Iris data set (once using the "SAMME" and once the "SAMME.R" algorithm).
Then let the model predict the probabilities for class 1 on the testing set.
I've then exported the model to ONNX, created an inference session on it, and used it to predict the same probabilities.
Comparing the results, I've noted the following differences between the probabilities predicted by sklearn and the probabilities predicted by ONNX runtime:
- SAMME algorithm: 
  -- max deviation: 2.5E-7
  -- average deviation: 2.9E-8
- SAMME.R algorithm:
  -- max deviation: 1.5E-2
  -- average deviation: 7.6E-3

Deviations in the area of 1E-7 seem to be expected and be based on rounding errors. 
However, deviations of about 1E-2 are in my opinion too significant to be ignored.

Besides, using skl2onnx 1.5.1, I'm getting a max deviation of 4.2E-8 for "SAMME".
(The max deviation for SAMME.R, did not change).

I suspect that this might be an issue that was introduced with skl2onnx 1.5.2.

Attached the example code based on the Iris data set.
[simple_AdaBoost.zip](https://github.com/onnx/sklearn-onnx/files/3875288/simple_AdaBoost.zip)

One additional question: What kind of deviations in the predicted probability between sklearn and ONNX runtime do I usually have to expect and is assumed to be acceptable?

Thanks for any help
-- Patrick

**Comment by prabhat00155** [comment]
Looking into this.

**Comment by prabhat00155** [comment]
SAMME.R seems to produce NaN probabilities in the latest skl2onnx.

**Comment by PatrickSager** [comment]
Sorry, I've mixed up the two algorithms above.
The observed deviations are:

**SAMME.R** algorithm:
-- max deviation: 2.5E-7
-- average deviation: 2.9E-8

**SAMME** algorithm:
-- max deviation: 1.5E-2
-- average deviation: 7.6E-3

So, **SAMME** causes for us the significant deviations.

Sorry about that
-- Pat

**Comment by prabhat00155** [comment]
https://github.com/onnx/sklearn-onnx/pull/330

**Comment by prabhat00155** [comment]
https://github.com/scikit-learn/scikit-learn/issues/15732

**Comment by prabhat00155** [comment]
Closing this as the fix was merged.
