### ISSUE TITLE
Error in converting SageMaker model to onnx

### ISSUE THREAD

**Issue by csharpbd** [onnx/sklearn-onnx#326]
I'm trying to convert a SageMaker XGBoost model to ONNX. There is a good resource to use machine learning in business area. I've tried [Using Machine Learning to Improve Sales in SageMaker](http://fasttrackteam.com/using-machine-learning-to-improve-sales-a-simple-example.aspx) to create the model and then convert the model to ONNX model. The example is working well in SageMaker. I've load the model successfully by using `pickle` and `joblib`. But it's shown error, when I'm going to convert the model to onnx using `sklearn-onnx`. Please take a look at the attached images for more details about the error.

![sklearn-onnx #1](https://user-images.githubusercontent.com/25961704/69671898-89040880-105c-11ea-9e06-1bc0534a99ac.png)
![sklearn-onnx #2](https://user-images.githubusercontent.com/25961704/69671899-899c9f00-105c-11ea-911e-8dde494d656e.png)

Could you please take a look at the issues and let me know a way to solve the issues? Thanks in advance!

**Comment by xadupre** [comment]
There is no solution yet. There is no converter in onnxmltools for a xgboost booster yet (see https://github.com/onnx/onnxmltools/issues/349).

**Comment by csharpbd** [comment]
@xadupre thanks for your reply. I've tried the `winmltools` and `onnxmltools` but unfortunetly the tools are not working. Already I've posted a question on StackOverflow about it. 
You can find the question [Error in converting SageMaker XGBoost model to ONNX model
](https://stackoverflow.com/questions/59000779/error-in-converting-sagemaker-xgboost-model-to-onnx-model) I've tried to explain each steps that I followed to convert the mode to ONNX model. Could you please take a look at the question? I hope you may help me.

**Comment by xadupre** [comment]
winmltools is using onnxmltools. That's why it does not work. I can try to have a fix by the end of the week. Would that work for you?

**Comment by csharpbd** [comment]
Sure, that will help me a lot.
Thank you for your kindness.

**Comment by xadupre** [comment]
I made a PR: https://github.com/onnx/onnxmltools/pull/355. You need to use onnxmltools from this branch: https://github.com/xadupre/onnxmltools/tree/xgbb. Let me know if it fixes your issue. I still have some doubts because it does not seem possible to retrieve the objective function from a booster. I only guess which kind of problem it is (classifier, regressor) but I might require an extra parameter if it does not work.

**Comment by csharpbd** [comment]
@xadupre I'm sorry for late response.
I've tried to convert the model to onnx after installing the `xgbb` branch. But I got an error. Actually I'm new in this field, I don't have enough and I'm struggling to get the desired result. Please take a look at the attached image and please guide me, what should I do now.

![image](https://user-images.githubusercontent.com/25961704/69995100-13dd7b00-1515-11ea-98d8-d04a990dec3c.png)

**Comment by xadupre** [comment]
The PR has been merged. So it should be easier to install. I don't see any error, just a warning we should probably remove. You need to test your model with a runtime now (onnxruntime for example). You should also use None instead of 'None' when you specify the shape.

**Comment by csharpbd** [comment]
Thanks @xadupre the model is converted to onnx and I can save the model as `.onnx` format. I'm working to check the model using ML.NET. I will back to you after testing the model.

**Comment by xadupre** [comment]
I'll close the issue. Feel free to reopen it.
