### ISSUE TITLE
target_opset is not properly set

### ISSUE THREAD

**Issue by mbaelde** [onnx/sklearn-onnx#335]
I tried to convert a fitted `sklearn.svm.SVC` model to onnx using `skl2onnx.convert_sklearn` and I wanted to fix the `target_opset` in order to remove the `onnxruntime` warning about opset. I set the target opset to 7 like this:

```python
onx = convert_sklearn(clf, initial_types=initial_type, target_opset=7)
```

But when I check the converted model opset with `converted_model.opset_import` it was always 1. 

Is this a normal behaviour?

I use Python3.6, sklearn version 0.22 and skl2onnx version 1.6.0 on Ubuntu 18.04.3 LTS.

FIY this is the `onnxruntime` warning:
```python
2019-12-06 16:19:05.741171855 [W:onnxruntime:Default, model.cc:114 Model] ONNX Runtime only *guarantees* support for models stamped with opset version 7 or above for opset domain 'ai.onnx'. Please upgrade your model to opset 7 or higher. For now, this opset 1 model may run depending upon legacy support of some older opset version operators.
```

**Comment by xadupre** [comment]
Can you tell more about your model? One possible Reason is the model only contains ML-ONNX operators.

**Comment by mbaelde** [comment]
The model is simply a `sklearn.svm.SVC` classifier from the last release of `scikit-learn`.

**Comment by xadupre** [comment]
When target_opset=7, the converter choose for every operator the highest version below or equal 7, then update the global ONNX version to the highest operator version. It may be 1. onnxruntime does not implement all the first versions of the operators, only versions >= 7.

**Comment by mbaelde** [comment]
Ok thanks for the information! This is not a problem therefore.
