### ISSUE TITLE
python 2.7 compatibility

### ISSUE THREAD

**Issue by psathyrella** [onnx/sklearn-onnx#336]
Sorry if this is covered somewhere, but is there a python 2 version of sklearn-onnx? The version I install with pip3 works fine. pip2 also happily installs a version of sklearn-onnx (1.6.0) into my python 2.7 local dir, but the version it installs seems to be python 3 code (it crashes on import in a number of places due to python 3-specific syntax).

I realize we're not even a month from python 2.7 deprecation, so I can't complain if sklearn-onnx only supports python 3, but if so maybe it would be possible to have pypi reflect this?

**Comment by xadupre** [comment]
There is no plan to support 2.7. Many packages stop supporting 2.7. And even if we do so, onnxruntime does not support python 2.7 and we would be unable to check that the converted models return the same values as the original models.

**Comment by psathyrella** [comment]
Ok, thanks for the reply. I totally understand lack of 2.7 support in 2019. That said, I would still expect the behavior when pip2 is asked to install sklearn-onnx to be a crash or warning of some sort, rather than blithely installing the python 3 version into pip's python 2.7  `~/.local` directory. But I'd understand if this was pip's problem rather than sklearn-onnx.
