### ISSUE TITLE
Convert HierarchicalSVM to onnx

### ISSUE THREAD

**Issue by mbaelde** [onnx/sklearn-onnx#338]
Can you plan to implement a converter of `HierarchicalSVM` to an onnx model please?

It can be found in the following package:
https://github.com/globality-corp/sklearn-hierarchical-classification

Thanks in advance.

**Comment by prabhat00155** [comment]
HierarchicalSVM, not being a part of scikit-learn package, wasn't there in our plan. Is this important for your use-case? I can discuss it with my team and get back.

**Comment by mbaelde** [comment]
It could be important, and if you have some guidelines to contribute on the project and some starting point I can try to implement it myself.

**Comment by prabhat00155** [comment]
You may look at this example, which talks about implementing your own converter: https://github.com/onnx/sklearn-onnx/blob/master/docs/examples/plot_custom_model.py

**Comment by mbaelde** [comment]
Thanks for the link. I tried to implement my own converter by pruning the example code and I came up with the following:
```python
def hierarchical_classifier_shape_calculator(operator):
    input = operator.inputs[0] 
    op = operator.raw_operator

    N = input.type.shape[0] 
    C = op.n_classes_

    # new output definition
    operator.outputs[0].type = FloatTensorType([N])
    operator.outputs[1].type = FloatTensorType([N, C])

def hierarchical_classifier_converter(scope, operator, container):
    """
    :param scope: name space, where to keep node names, get unused new names
    :param operator: operator to converter, same object as sent to
        *hierarchical_classifier_shape_calculator*
    :param container: contains the ONNX graph

    """
    op = operator.raw_operator

    model = op.base_estimator
    alias = _get_sklearn_operator_name(type(model))
    svc_op = scope.declare_local_operator(alias, model)
    svc_op.inputs = operator.inputs
    svc_op.outputs = operator.outputs

    shape_calc = get_shape_calculator(alias)
    shape_calc(svc_op)

update_registered_converter(
    HierarchicalClassifier,
    "CustomHierarchicalClassifier",
    hierarchical_classifier_shape_calculator,
    hierarchical_classifier_converter,
)

model_onnx = convert_sklearn(
    clf,
    name="hierarchical_classifier",
    initial_types=[("input", FloatTensorType([None, n_features]))],
)
```

However I keep getting the following error:

```python
RuntimeError: One variable can only be assigned once: Variable(raw_name='label', onnx_name='label', type=StringTensorType(shape=[None])).
``` 

If you have any though about it I would appreciate. Thanks in advance!

**Comment by mbaelde** [comment]
I think this can be due to the `SklearnZipMap` layer which is automatically added to `topology.scope` when using non standard sklearn class. However I don't know how to solve the problem.

**Comment by xadupre** [comment]
It is possible to remove the zipmap operator by using options. You can look into the particular line: https://github.com/onnx/sklearn-onnx/blob/master/skl2onnx/operator_converters/calibrated_classifier_cv.py#L246. This enables the operator to return raw scores instead of probabilities. For zipmap, the option would be {'zipmap': False}.

**Comment by mbaelde** [comment]
Thank you for your answer. I tried the proposed solution by adding the line
```python
container.add_options(id(model), {'zipmap': False})
```
in `def hierarchical_classifier_converter(scope, operator, container):` but I get the following error:
```python
AttributeError: 'ModelComponentContainer' object has no attribute 'add_options'
```

**Comment by xadupre** [comment]
Which version are you using? sklearn-onnx was not updated for a long time and it is better to use master branch.

**Comment by minotru** [comment]
Hi @mbaelde! I am also interested in the conversion of the Hierarchical Classifier to ONNX. Did you have luck with it?

**Comment by mbaelde** [comment]
Hi @minotru , sorry I give up on this, finally I don't need this anymore. I didn't manage to correctly convert a Hierarchical model.

**Comment by xadupre** [comment]
One way to write the converter with ONNX would be to compute the output of all SVMs and use the output as input features for a decision tree.
