### ISSUE TITLE
lgbm onnx conversion output type error 

### ISSUE THREAD

**Issue by yasamanK** [onnx/sklearn-onnx#342]
Hi! 

I am using skl2onnx.convert_sklearn according to 
http://onnx.ai/sklearn-onnx/auto_examples/plot_pipeline_lightgbm.html 
to convert some lgbm classifiers to onnx. the conversion/save steps happen without issue but when I loading the converted onnx models back and makingt inference using:
sess = rt.InferenceSession(model_onnx_output)
I get this error:
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from test_model.onnx failed:Type Error: Type (tensor(float)) of output arg (probabilities) of node (ZipMap) does not match expected type (seq(map(int64,tensor(float)))).

I tried running  plot_pipeline_lightgbm.py downloaded from the above link and hit exactly same error.

here are the package versions I am using:
numpy: 1.16.2
scikit-learn: 0.20.3
onnx:  1.5.0
onnxruntime:  1.0.0
skl2onnx:  1.4.9
onnxmltools:  1.4.1
lightgbm:  2.2.3
Python 3.7.0

would appreciate your help. thanks
FYI @xadupre

**Comment by prabhat00155** [comment]
Can you try using the latest version of skl2onnx, scikit, onnx, etc.?
numpy==1.17.4
skl2onnx==1.6.0
onnxmltools==1.6.0
onnxruntime==1.0.0
onnx==1.6.0
scikit-learn==0.22

**Comment by yasamanK** [comment]
I have upgraded the packages you listed to the latest versions. still getting the same error with this line:
sess = rt.InferenceSession("pipeline_lightgbm.onnx")

in addition, there is a warning about model opset:
2019-12-10 10:02:01.0586805 [W:onnxruntime:Default, model.cc:114 onnxruntime::Model::Model] ONNX Runtime only *guarantees* support for models stamped with opset version 7 or above for opset domain 'ai.onnx'. Please upgrade your model to opset 7 or higher. For now, this opset 1 model may run depending upon legacy support of some older opset version operators.

**Comment by prabhat00155** [comment]
I am able to reproduce the error now. Marking this as a bug.

**Comment by xadupre** [comment]
The example is working with the master branch. Every example is tested at every commit. Could you try with the master branch?

**Comment by huzq2016** [comment]
I met the same issue now. 
Wonder if anybody found solution.

**Comment by xadupre** [comment]
Could you give the version of the packages listed above?

**Comment by xadupre** [comment]
The example explains how to convert a lightgbm model: [Convert a pipeline with a LightGBM classifier](http://onnx.ai/sklearn-onnx/auto_tutorial/plot_gexternal_lightgbm.html). I'll close the issue. Feel free to reopen it.

**Comment by huzq2016** [comment]
Hi Xavier Dupre,

Thanks for your sharing. It is OK for me.

Best regards,
Zhongqiao


Xavier Dupré ***@***.***> 于2021年11月26日周五 下午6:25写道：
