### ISSUE TITLE
Unable to find a shape calculater for OwnTransformer

### ISSUE THREAD

**Issue by drvshavva** [onnx/sklearn-onnx#359]
Hello ,
I wrote my own transformer sklearn according to the summer support, but we can not convert the transformer we created onnx. So is there any onnx format to convert??

Problem:
skl2onnx.common.exceptions.MissingShapeCalculator: Unable to find a shape calculator for type '<class 'newBackend.feature_engineering.normalize_MinMaxScaler_class.normalizeMinMaxScaler'>'.

**Comment by prabhat00155** [comment]
You also need to add a shape calculator along with teh converter. Look at the skl2onnx/shape_calculator. You can try adding your op here: skl2onnx/shape_calculators/linear_classifier.py.
