### ISSUE TITLE
support for PowerTransformer

### ISSUE THREAD

**Issue by msteijaert** [onnx/sklearn-onnx#376]
I noticed that there is not yet support for PowerTransformer. Is anybody working on this?

If not, I will see if I can solve this on my end. I'm new to this package, but here is my naive understanding of what needs to happen (feel free to correct or comment):

1) creation of a scaler (at first glance the new converter can be almost identical to calculate_sklearn_function_transformer_output_shapes or calculate_sklearn_scaler_output_shapes)

2) creation of a converter, which reimplements PowerTransformer.transform(), and makes use of the method name and fitted lambda values stored in operator object

**Comment by xadupre** [comment]
You can look into PR #318 or PR #294 depending on what you need to do. The first step consists in compute the shape of the output given the input. You will find more explanation in this example: http://onnx.ai/sklearn-onnx/auto_examples/plot_custom_model.html.

**Comment by xadupre** [comment]
I'll close this issue as the PR was merged.
