### ISSUE TITLE
Combine sklearn pipeline with keras or lightgbm

### ISSUE THREAD

**Issue by NonaryR** [onnx/sklearn-onnx#38]
Hello! It's possible to use `pipeline` for preparing data and on top of that `keras` or `lightgbm` model?
It is not clear for me - which convert function I should choose for this operation

**Comment by NonaryR** [comment]
@xadupre hello! This is awesome, thank you! May you explain - I should always define extractor like [this](https://github.com/onnx/sklearn-onnx/commit/7f1bb3b46ec7ec15749c3e390989c4787e3d3f44#diff-eff30bf4e762f12034ba4681ca8c6127R74)
Or they implementation will be defined in library later? 
And one more question - what about keras with pipeline support?

**Comment by xadupre** [comment]
We are currently refactoring onnxmltools and keras converters. The mechanism will be same (you need to register a new converter) but it should be more simple. The custom shape calculator should disappear to be replaced by a version coming from onnxmltools.

**Comment by xadupre** [comment]
I'll close that issue since the issue has a solution.

**Comment by NonaryR** [comment]
@xadupre what about keras?

**Comment by henningsway** [comment]
@NonaryR I believe the proposed solution will work for lightgmb, keras and other "flavors" mentioned in https://github.com/onnx/onnxmltools#introduction

@xadupre could you elaborate a little bit more, if this is already possible and become more simple in the future or if this is new functionality. If possible please mention a rough timeline, also. :)

For a little context, I would hope to transform and serve a sklearn-Pipeline (with a few custom steps) build around `KerasClassifier`.

**Comment by themummy** [comment]
@xadupre , I see the lightGBM converter is there a converter for a Keras/TF model?

**Comment by PatrickSager** [comment]
@xadupre: I was also not able to export a pipeline that contains a scikit_learn.KerasClassifier.
I'm getting the following error: Unable to find a shape calculator for type '<class 'keras.wrappers.scikit_learn.KerasClassifier'>'.
Could you please provide an example or add a statement, that this is the scikit_learn.KerasClassifier is currently not supported.
