### ISSUE TITLE
Converted TfidfVectorizer can't be run with dtype float64

### ISSUE THREAD

**Issue by interplanetaryDB** [onnx/sklearn-onnx#392]
I am trying to convert a tfidf Vectorizer followed by naive bayes to onnx and run it. I had discrepancies in the results between sklearn and onnx for some test sets, which were far worse than the usual difference in the 6th decimal point. Then i tried switching to dtype=numpy.float64 in the convert_sklearn method but running that in onnxruntime fails.

`import numpy as np`
`from sklearn.feature_extraction.text import TfidfVectorizer`
`import onnxruntime`
`from skl2onnx import convert_sklearn`
`from skl2onnx.common.data_types import StringTensorType`

`data = np.array(["ksd f i o osp  p posfj jp pas jj",`
`                "jfio psjfpisaj jfsaidfsfipjfp p gfdg asf",`
`                   "soh fo fsf dnp fdfjkdpfl f fpgpplf"],`
`                dtype=object)`

`initial_type = [('string_input', StringTensorType([None]))]`

`tfidf = TfidfVectorizer()`

`tfidf.fit(data)`

`onx = convert_sklearn(tfidf, initial_types=initial_type, dtype=np.float64)`

`sess = onnxruntime.InferenceSession(onx.SerializeToString())`

---------------------------------------------------------------------------
Fail                                      Traceback (most recent call last)
<ipython-input-1-d80a1d2a9a91> in <module>
     20 onx = convert_sklearn(tfidf, initial_types=initial_type, dtype=np.float64)
     21 
---> 22 sess = onnxruntime.InferenceSession(onx.SerializeToString())

c:\users\u733825\appdata\local\continuum\miniconda2\envs\classifly_from_yml\lib\site-packages\onnxruntime\capi\session.py in __init__(self, path_or_bytes, sess_options, providers)
     23         self._path_or_bytes = path_or_bytes
     24         self._sess_options = sess_options
---> 25         self._load_model(providers)
     26         self._enable_fallback = True
     27 

c:\users\u733825\appdata\local\continuum\miniconda2\envs\classifly_from_yml\lib\site-packages\onnxruntime\capi\session.py in _load_model(self, providers)
     41             raise TypeError("Unable to load from type '{0}'".format(type(self._path_or_bytes)))
     42 
---> 43         self._sess.load_model(providers)
     44 
     45         self._session_options = self._sess.session_options

Fail: [ONNXRuntimeError] : 1 : FAIL : Type Error: Type parameter (T) bound to different types (tensor(float) and tensor(double) in node (Mul).

---------------------------------------------------------------------------

If the dtype of the convert method is chnaged to float32
`convert_sklearn(tfidf, initial_types=initial_type, dtype=np.float32)`
there is no error. The sklearn TfidfVectorizer has a default dtype argument of numpy.float64

Used versions:
numpy.__version__: 1.17.0
sklearn.__version__: 0.22.1
onnxruntime.__version__: 1.1.0
skl2onnx.__version__: 1.6.0
Python.version: 3.7.6

**Comment by prabhat00155** [comment]
I think float64 is not handled properly, that needs to be fixed. Meanwhile, can you paste the example with float32 that gives you mismatches with scikit output?

**Comment by interplanetaryDB** [comment]
Thanks for the quick reply. Unfortunately I can't share the data. The structure is very similar to the above example just with many more lines and a class label for each line. I would like to anonymize it while keeping the result but I'm not too confident about that.

**Comment by xadupre** [comment]
See https://github.com/onnx/onnx/blob/master/docs/Operators.md#TfIdfVectorizer, onnx specifications only allows float as output type. Onnxruntime reflects that constraint.
