### ISSUE TITLE
Options ['nocl'] are not registerd for model 'LGBMClassifier'

### ISSUE THREAD

**Issue by gargayush792** [onnx/sklearn-onnx#393]
I am trying to convert an SkLearn pipeline with LightGBM classifier to ONNX. 

```
preprocessor = ColumnTransformer(
    transformers=[
        ('cat_encode', OrdinalEncoder(categories = cat_encodings), [0,1,2,3,4,5,6,7]),
        ],
    remainder='passthrough'
)

clf = Pipeline(steps=[('preprocessor', preprocessor),
                      ('train', LGBMClassifier(num_leaves = 31, objective ='binary', max_depth = 6, n_estimators = 200))])

clf.fit(X_train, y_train)

update_registered_converter(LGBMClassifier, 'LightGbmLGBMClassifier',
                            calculate_linear_classifier_output_shapes,
                            convert_lightgbm)

model_onnx = convert_sklearn(clf, 'pipeline_unfunded', [('input', FloatTensorType(shape=[None, 27]))])
```

This gives me the error - 
Options ['nocl'] are not registerd for model 'LGBMClassifier'

**Comment by prabhat00155** [comment]
@xadupre: Do we need to add `nocl` option to lightgbm and xgboost?

**Comment by xadupre** [comment]
There is an example which does that: plot_pipeline_xgboost. It shows how to do it.

**Comment by gargayush792** [comment]
Tried running `examples/plot_pipeline_xgboost.py` and `examples/plot_pipeline_lightgbm.py`. Both of them fail too giving the same error.

**Comment by xadupre** [comment]
I looked into the wrong branch, I updated the examples in PR #396. It should be merged soon in master branch.
