### ISSUE TITLE
Support drop option of OneHotEncoder

### ISSUE THREAD

**Issue by victornoel** [onnx/sklearn-onnx#402]
Hi,

I tried to use a `OneHotEncoder` with `drop` option set to `first` but when I do so, running the generated model with onnxruntime gives me  the following error during prediction:
```
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running OneHotEncoder node. Name:'OneHotEncoder7' Status Message: Unknown Category and zeros = 0.
```

See https://github.com/onnx/sklearn-onnx/issues/321#issuecomment-584052819 for an example of code used to generate and convert the model.

**Comment by prabhat00155** [comment]
I think you are passing an unknown category(category in test set not seen in training). Have you checked scikit output, that should give you an error(related to unknown category) as well.

**Comment by victornoel** [comment]
@prabhat00155 I fit the `OneHotEncoder` with the full train+test dataset to avoid such problem. With sklearn it works as expected (`full_df` in https://github.com/onnx/sklearn-onnx/issues/321#issuecomment-584052819)

**Comment by victornoel** [comment]
@prabhat00155 tomorrow I will try to make a repro using one of the sklearn-provided datasets :)

**Comment by victornoel** [comment]
@prabhat00155 here it is: https://gist.github.com/victornoel/c4da3089f6792ac1b6fdcdb583886f97

**Comment by prabhat00155** [comment]
To simplify, I extracted the text columns separately and just did OHE transform.
```
data = pd.read_csv(('https://raw.githubusercontent.com/amueller/'
                        'scipy-2017-sklearn/091d371/notebooks/datasets/titanic3.csv'))
text_df3 = data[data.columns[data.dtypes == 'object']]
list(map(lambda col: text_df3[col].fillna('N/A', inplace=True), text_df3.columns))
print(text_df3.isnull().values.any())
model = OneHotEncoder().fit(text_df3)
onnx_model = convert_sklearn(model, 'ohe', [('input', StringTensorType([None, text_df3.values.shape[1]]))])
save_model(onnx_model, 'ohe.onnx')
sess = InferenceSession('ohe.onnx')
res = sess.run(None, input_feed={'input': text_df3.values})
res
```
This works on the whole dataset, but if I divide the dataset into train and test:
```
train_df, test_df = train_test_split(text_df3, test_size=.2)
model = OneHotEncoder().fit(train_df)
model.transform(test_df)

ValueError: Found unknown categories ...
```
Scikit transform() gives ValueError.

**Comment by prabhat00155** [comment]
If you don't want error for unknown categories in test set, add `handle_unknown='ignore'` in OHE and remove `drop='first'`(both can't be specified together).
```
model = OneHotEncoder(handle_unknown='ignore').fit(train_df)
```

**Comment by victornoel** [comment]
@prabhat00155 have you tried to run the repro I provided? I think your comment is not answering my question. 

In the example I gave abvoe:
- I fit the encoder with the whole dataset (and not only the train_df)
- It works with sklearn/xgboost (i.e., Scikit transform() does NOT give ValueError) as expected
- It doesn't work with onnx

**Comment by prabhat00155** [comment]
I see what the problem is now. If we set drop='first', sk2onnx removes the first category from each feature and hence when you do transform with that feature value, skl2onnx give the error, whereas scikit keeps that category value, and simply hides that category from the output. This needs to be fixed, thanks for reporting. Here is a simpler example which shows this:
```
X = np.array([['male', 'first'], ['female', 'first'], ['male', 'second']])
model = OneHotEncoder(drop='first').fit(X)
print(model.transform(X).toarray())
onnx_model = convert_sklearn(model, 'ohe', [('input', StringTensorType([None, 2]))])
save_model(onnx_model, 'ohe.onnx')
sess = InferenceSession('ohe.onnx')
res = sess.run(None, input_feed={'input': X})

[[1. 0.]
 [0. 0.]
 [1. 1.]]
---------------------------------------------------------------------------
Fail                                      Traceback (most recent call last)
<ipython-input-57-66d5e90d517b> in <module>
      5 save_model(onnx_model, 'ohe.onnx')
      6 sess = InferenceSession('ohe.onnx')
----> 7 res = sess.run(None, input_feed={'input': X})
      8 res

~/Documents/MachineLearning/onnx_projects/skl_env/lib/python3.6/site-packages/onnxruntime/capi/session.py in run(self, output_names, input_feed, run_options)
    140             output_names = [output.name for output in self._outputs_meta]
    141         try:
--> 142             return self._sess.run(output_names, input_feed, run_options)
    143         except C.EPFail as err:
    144             if self._enable_fallback:

Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running OneHotEncoder node. Name:'OneHotEncoder1' Status Message: Unknown Category and zeros = 0.
```
If you print `model.categories_`, you still see all the categories in training data:
[array(['female', 'male'], dtype='<U6'),
 array(['first', 'second'], dtype='<U6')]

**Comment by victornoel** [comment]
@prabhat00155 really cool, thx :)
