### ISSUE TITLE
LinearRegressor conversion generates invalid shape

### ISSUE THREAD

**Issue by skottmckay** [onnx/sklearn-onnx#409]
onnx_test_runner.exe for model from SklearnLinearRegression-Dec4 fails.

> Tensor shape mismatch, model file expects '{,1}', real output is [500, 2]

Unit test involved is test_model_multi_linear_regression

Looks like the output shape needs to take into account the number of targets as it's 2 in this unit test not 1, so probably the output shape should be {,2}.

**Comment by xadupre** [comment]
I can't reproduce.
