### ISSUE TITLE
Converter for sklearn.naive_bayes.CategoricalNB

### ISSUE THREAD

**Issue by minglonglam** [onnx/sklearn-onnx#429]
The sklearn.naive_bayes.CategoricalNB is new in version 0.22.2.  Please develop a convert for it.  Thank you.

**Comment by xadupre** [comment]
It is available in master branch: https://github.com/onnx/sklearn-onnx/blob/master/skl2onnx/operator_converters/naive_bayes.py#L472. This version is not released yet.
