### ISSUE TITLE
How to have .scores method instead only _predict_proba in our ONNX model converted from GMM Sklearn

### ISSUE THREAD

**Issue by alexivaner** [onnx/sklearn-onnx#431]
Hi I need scoring method from GMM Sklearn, I succed convert the model to onnx, but there is no scoring method inside onnx model. How to have that method in our ONNX model? I only have .predict  and predict_proba in onnx

**Comment by xadupre** [comment]
You mean scoring predictions against expected outputs?

**Comment by alexivaner** [comment]
![image](https://user-images.githubusercontent.com/57290644/79880596-d2496000-8422-11ea-8ab3-8fd7411ebfa7.png)

 I attached the images, it is one of the method inside the GMM Sklearn model. 
I already tried to changed the option using this code:
options = {id(models): {'raw_scores': True}}

But I still couldn't found the score yet.
Thank you

**Comment by xadupre** [comment]
Sorry for my previous reply, it was irrelevant. It is not implemented but it should not be too difficult. Do you prefer a third output or to replace the probabilities by scoring?

**Comment by alexivaner** [comment]
I prefer third output, but since I still not used probabilities, replace the probabilities also okay. Thank you.

**Comment by alexivaner** [comment]
@xadupre Hi sorry, I just want to clarify, so the .score_samples method is still not yet implemented for this version that mean that I still couldn't use it for now? If not yet implemented, how long the development of this method? Or I can use another way like custom pipeline or something? Thank you very much for your help.

**Comment by xadupre** [comment]
It is not implemented yet. The convert the score method needs to be converted into ONNX whatever the solution you choose. I plan to work on it. It should be ready by end of week. Let me know if that's not ok for you.

**Comment by alexivaner** [comment]
Wow that's great, thank you very much really appreciate it. It will be really mean for me if I could use it by this week or next week. Really need it soon, anyway thank you very much. This Onnx-Sklearn library already helps me a lot especially when I need to use my python model in unity. @xadupre

**Comment by xadupre** [comment]
Related PR #432, I still need to fix some discrepencies.

**Comment by alexivaner** [comment]
@xadupre Thank you for your changes to the code, but I found some error, here is the error when I run the session from onnxruntime after converting the model.
![image](https://user-images.githubusercontent.com/57290644/80056906-e9d63500-8557-11ea-8a40-be9ea53e5e42.png)

**Comment by xadupre** [comment]
Which version of onnxruntime are you using? I'll continue working on this today.

**Comment by alexivaner** [comment]
I used version 1.2.0

**Comment by alexivaner** [comment]
I am using version 1.2.0 for OnnxRuntime, but it runs well if I didn't put options when converting my model.

**Comment by xadupre** [comment]
I used the nightly build and this error is now a warning (but I still need to remove it).

**Comment by xadupre** [comment]
The PR is ready.

**Comment by alexivaner** [comment]
Thank you very much @xadupre. It's worked as expected. Really appreciate your help
