### ISSUE TITLE
Add converter for RadiusNeighborsClassifier, Regressor

### ISSUE THREAD

**Issue by xadupre** [onnx/sklearn-onnx#453]

**Comment by deepchatterjeeligo** [comment]
Hi,

I was encountering an error when converting a `KNeighborsClassifier` model following the  [sklearn-onnx tutorial](http://onnx.ai/sklearn-onnx/tutorial.html#step-3-load-and-run-the-model-using-onnx-runtime). The model get converted but I get the error using `onnxruntime`. Is conversion of  `KNeighborsClassifier` supported?

Traceback:
```python
>>> import onnxruntime as rt
>>> sess = rt.InferenceSession('k-neighbors.onnx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/deep/virtualenvs/p-astro/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 25, in __init__
    self._load_model(providers)
  File "/home/deep/virtualenvs/p-astro/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 43, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (Sc_Scan) Op (Scan) [TypeInferenceError] Graph attribute inferencing failed: Node (Su_Sub) Op (Sub) [ShapeInferenceError] Incompatible dimensions
```

**Comment by xadupre** [comment]
The converter should work and is tested at each commit. Can you tell me more about the version you are using (onnx, onnxruntime, skl2onnx, scikit-kearn, onnxconverter-common) and the training parameters you used?

**Comment by deepchatterjeeligo** [comment]
Output of pip freeze
```bash
onnx==1.6.0
onnxconverter-common==1.6.1
onnxruntime==1.2.0
skl2onnx==1.6.1
scikit-learn==0.22.2.post1
```

The feature space for my `KNeighborsClassifier` is 5 dimensional (all numerical float values), used for binary classification, target 0/1.

**Comment by deepchatterjeeligo** [comment]
Any updates on this @xadupre ?

**Comment by xadupre** [comment]
Did you try to install sklearn-onnx from master branch?
