### ISSUE TITLE
Difference in prediction output of a scikit-learn model and ONNX model for the same data.

### ISSUE THREAD

**Issue by Karnav123** [onnx/sklearn-onnx#506]
See the difference in output in following image.
![onnxVSpkl](https://user-images.githubusercontent.com/36244620/86598792-47a4e580-bfbb-11ea-8da5-1173bca6923a.PNG)
The dataset is for binary classification. The code to generate the model is:
```
categorical_pipeline_onehot = Pipeline([
             ('OneHot', OneHotEncoder( handle_unknown='ignore'))
        ])
preprocessor = ColumnTransformer(
    transformers=[('Onehot', categorical_pipeline_onehot, CATEGORICAL_ATTRIBUTES_ONEHOT)],
    remainder='passthrough')
from xgboost import XGBClassifier
xgb = XGBClassifier()

clf = Pipeline(steps=[('preprocessor', preprocessor),('cls', xgb)])
clf.fit(df_train[predictors], df_train["IsSelected"])

update_registered_converter(
    XGBClassifier, 'XGBoostXGBClassifier',
    calculate_linear_classifier_output_shapes, convert_xgboost,
    options={'nocl': [True, False], 'zipmap': [True, False]})
```

To convert this model to ONNX the code is:

```
def convert_dataframe_schema(df, drop=None):
    inputs = []
    for k, v in zip(df.columns, df.dtypes):
        if drop is not None and k in drop:
            continue
        if v == 'int64':
            t = Int64TensorType([None, 1])
        elif v == 'float64':
            t = FloatTensorType([None, 1])
        else:
            t = StringTensorType([None, 1])
        inputs.append((k, t))
    return inputs

try:
    model_onnx_wholed = convert_sklearn(model, 'pipeline_with_onehot', inputs)
except Exception as e:
    print(e)

with open("XGB_onehot_wholedata.onnx", "wb") as f:
    f.write(model_onnx_wholed.SerializeToString())
```
While prediction I am using C++ APIs as well as Python for onnxruntime. The prediction output generated by the onnx model is all 0 for both C++ and Python which do not match with that of the trained sklearn model.

The ONNX model adds Cast operator for features. It may be due to this but I am not sure.

The C++ onnxruntime API log is as following:

```
2020-07-06 18:50:47.2890620 [W:onnxruntime:test, abi_session_options.cc:147 OrtApis::SetIntraOpNumThreads] Since openmp is enabled in this build, this API cannot be used to configure intra op num threads. Please use the openmp environment variables to control the number of threads.
Using Onnxruntime C++ API
2020-07-06 18:50:55.2296864 [I:onnxruntime:, inference_session.cc:174 onnxruntime::InferenceSession::ConstructorCommon] Creating and using per session threadpools since use_per_session_threads_ is true
2020-07-06 18:50:55.4219403 [I:onnxruntime:, inference_session.cc:830 onnxruntime::InferenceSession::Initialize] Initializing session.
2020-07-06 18:50:55.4220585 [I:onnxruntime:, inference_session.cc:848 onnxruntime::InferenceSession::Initialize] Adding default CPU execution provider.
2020-07-06 18:50:55.4224222 [I:onnxruntime:test, bfc_arena.cc:15 onnxruntime::BFCArena::BFCArena] Creating BFCArena for Cpu
2020-07-06 18:50:55.4224870 [V:onnxruntime:test, bfc_arena.cc:32 onnxruntime::BFCArena::BFCArena] Creating 21 bins of max chunk size 256 to 268435456
2020-07-06 18:50:55.4247204 [V:onnxruntime:, inference_session.cc:671 onnxruntime::InferenceSession::TransformGraph] Node placements
2020-07-06 18:50:55.4248273 [V:onnxruntime:, inference_session.cc:673 onnxruntime::InferenceSession::TransformGraph] All nodes have been placed on [CPUExecutionProvider].
2020-07-06 18:50:55.4249199 [I:onnxruntime:, session_state.cc:25 onnxruntime::SessionState::SetGraph] SaveMLValueNameIndexMapping
2020-07-06 18:50:55.4250567 [I:onnxruntime:, session_state.cc:70 onnxruntime::SessionState::SetGraph] Done saving OrtValue mappings.
2020-07-06 18:50:55.4266916 [I:onnxruntime:, session_state_initializer.cc:178 onnxruntime::SaveInitializedTensors] Saving initialized tensors.
2020-07-06 18:50:55.4268214 [I:onnxruntime:, session_state_initializer.cc:223 onnxruntime::SaveInitializedTensors] Done saving initialized tensors
2020-07-06 18:50:55.7311821 [I:onnxruntime:, inference_session.cc:919 onnxruntime::InferenceSession::Initialize] Session successfully initialized.
Number of inputs = 22
Number of outputs = 2
Output 0 : name=label
Output 1 : name=probabilities

2020-07-06 18:51:18.7355209 [I:onnxruntime:, sequential_executor.cc:145 onnxruntime::SequentialExecutor::Execute] Begin execution
2020-07-06 18:51:27.4858870 [I:onnxruntime:test, bfc_arena.cc:259 onnxruntime::BFCArena::AllocateRawInternal] Extending BFCArena for Cpu. bin_num:0 rounded_bytes:256
2020-07-06 18:51:27.4867688 [I:onnxruntime:test, bfc_arena.cc:143 onnxruntime::BFCArena::Extend] Extended allocation by 1048576 bytes.
2020-07-06 18:51:27.4871985 [I:onnxruntime:test, bfc_arena.cc:147 onnxruntime::BFCArena::Extend] Total allocated bytes: 1048832
2020-07-06 18:51:27.4872666 [I:onnxruntime:test, bfc_arena.cc:150 onnxruntime::BFCArena::Extend] Allocated memory at 000001D54AC25060 to 000001D54AD25060
Predicted Class:
0
0
0
0
0
0
0
0
0
0
0
0

```
```
Versions: 
skl2onnx: 1.7.0
onnxruntime: 1.3.0
```

**Comment by hanzigs** [comment]
I have a somewhat like issue, but I am not sure how to extract the probability values,
I have sklearn RandomForestClassifier
```
initial_type = [('float_input', FloatTensorType([None, 21]))]
RFOnnx_model = skl2onnx.convert_sklearn(RF_model, initial_types=initial_type)
content = RFOnnx_model.SerializeToString()
sess = onnxruntime.InferenceSession(content)
input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
payload = [[6.23825461e-01,-1.26414939e-02,-2.98698634e-01,7.49970172e-01,9.77326200e-02,1.70205380e-02,2.48707775e+00,2.07501365e+00,2.70571484e-01,2.41767187e+00,4.42420606e-01,-5.39277508e-01,-7.73496115e-02,2.77599946e-01,-2.68517817e-02,2.72781908e-01,2.22730821e+00,8.44443394e-01,-5.75698893e-02,-3.34715704e-01,1.09698389e-01]]
pred_onnx = sess.run([label_name], {input_name: payload})[0]
pred_onnx[0]
```
this returns 1, but if I do with regular model predict_proba
```
df = pandas.DataFrame(data=payload,columns=cols)
RF_model.predict_proba(df.values)
```
I get
```
array([[0.02219565, 0.97780435]])
```
may I know how to extract the probability values

**Comment by siddharth98765** [comment]
> I have a somewhat like issue, but I am not sure how to extract the probability values,
> I have sklearn RandomForestClassifier
> 
> ```
> initial_type = [('float_input', FloatTensorType([None, 21]))]
> RFOnnx_model = skl2onnx.convert_sklearn(RF_model, initial_types=initial_type)
> content = RFOnnx_model.SerializeToString()
> sess = onnxruntime.InferenceSession(content)
> input_name = sess.get_inputs()[0].name
> label_name = sess.get_outputs()[0].name
> payload = [[6.23825461e-01,-1.26414939e-02,-2.98698634e-01,7.49970172e-01,9.77326200e-02,1.70205380e-02,2.48707775e+00,2.07501365e+00,2.70571484e-01,2.41767187e+00,4.42420606e-01,-5.39277508e-01,-7.73496115e-02,2.77599946e-01,-2.68517817e-02,2.72781908e-01,2.22730821e+00,8.44443394e-01,-5.75698893e-02,-3.34715704e-01,1.09698389e-01]]
> pred_onnx = sess.run([label_name], {input_name: payload})[0]
> pred_onnx[0]
> ```
> 
> this returns 1, but if I do with regular model predict_proba
> 
> ```
> df = pandas.DataFrame(data=payload,columns=cols)
> RF_model.predict_proba(df.values)
> ```
> 
> I get
> 
> ```
> array([[0.02219565, 0.97780435]])
> ```
> 
> may I know how to extract the probability values from onnx model

@hanzigs check pred_onnx[1] you might get what you want

**Comment by hanzigs** [comment]
its IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by Karnav123** [comment]
> pred_onnx[1] is IndexError: index 1 is out of bounds for axis 0 with size 1

Check the size of the output node and then try to find it.

**Comment by hanzigs** [comment]
without index
![image](https://user-images.githubusercontent.com/30790120/86768868-8dcc7880-c091-11ea-86c2-e58ec37206c6.png)
and sess parameters
![image](https://user-images.githubusercontent.com/30790120/86768953-b05e9180-c091-11ea-8a9c-d99dfa682ba2.png)

**Comment by Karnav123** [comment]
> without index
> ![image](https://user-images.githubusercontent.com/30790120/86768868-8dcc7880-c091-11ea-86c2-e58ec37206c6.png)
> and sess parameters
> ![image](https://user-images.githubusercontent.com/30790120/86768953-b05e9180-c091-11ea-8a9c-d99dfa682ba2.png)
> don't understand why
> output shape is [None] and
> output type supposed to be float may be

use as following:

```
sess = rt.InferenceSession("your_model.onnx")
input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
output_probability = sess.get_outputs()[1].name

pred_onx = sess.run([label_name, output_probability], {input_name: X_test_.astype(np.int64)})
print("predict", pred_onx[0][:])
print("predict_proba", pred_onx[1][:])
```

**Comment by hanzigs** [comment]
That's perfect, Thank you very much

**Comment by prabhat00155** [comment]
> See the difference in output in following image.
> ![onnxVSpkl](https://user-images.githubusercontent.com/36244620/86598792-47a4e580-bfbb-11ea-8da5-1173bca6923a.PNG)
> The dataset is for binary classification. The code to generate the model is:
> 
> ```
> categorical_pipeline_onehot = Pipeline([
>              ('OneHot', OneHotEncoder( handle_unknown='ignore'))
>         ])
> preprocessor = ColumnTransformer(
>     transformers=[('Onehot', categorical_pipeline_onehot, CATEGORICAL_ATTRIBUTES_ONEHOT)],
>     remainder='passthrough')
> from xgboost import XGBClassifier
> xgb = XGBClassifier()
> 
> clf = Pipeline(steps=[('preprocessor', preprocessor),('cls', xgb)])
> clf.fit(df_train[predictors], df_train["IsSelected"])
> 
> update_registered_converter(
>     XGBClassifier, 'XGBoostXGBClassifier',
>     calculate_linear_classifier_output_shapes, convert_xgboost,
>     options={'nocl': [True, False], 'zipmap': [True, False]})
> ```
> 
> To convert this model to ONNX the code is:
> 
> ```
> def convert_dataframe_schema(df, drop=None):
>     inputs = []
>     for k, v in zip(df.columns, df.dtypes):
>         if drop is not None and k in drop:
>             continue
>         if v == 'int64':
>             t = Int64TensorType([None, 1])
>         elif v == 'float64':
>             t = FloatTensorType([None, 1])
>         else:
>             t = StringTensorType([None, 1])
>         inputs.append((k, t))
>     return inputs
> 
> try:
>     model_onnx_wholed = convert_sklearn(model, 'pipeline_with_onehot', inputs)
> except Exception as e:
>     print(e)
> 
> with open("XGB_onehot_wholedata.onnx", "wb") as f:
>     f.write(model_onnx_wholed.SerializeToString())
> ```
> 
> While prediction I am using C++ APIs as well as Python for onnxruntime. The prediction output generated by the onnx model is all 0 for both C++ and Python which do not match with that of the trained sklearn model.
> 
> The ONNX model adds Cast operator for features. It may be due to this but I am not sure.
> 
> The C++ onnxruntime API log is as following:
> 
> ```
> 2020-07-06 18:50:47.2890620 [W:onnxruntime:test, abi_session_options.cc:147 OrtApis::SetIntraOpNumThreads] Since openmp is enabled in this build, this API cannot be used to configure intra op num threads. Please use the openmp environment variables to control the number of threads.
> Using Onnxruntime C++ API
> 2020-07-06 18:50:55.2296864 [I:onnxruntime:, inference_session.cc:174 onnxruntime::InferenceSession::ConstructorCommon] Creating and using per session threadpools since use_per_session_threads_ is true
> 2020-07-06 18:50:55.4219403 [I:onnxruntime:, inference_session.cc:830 onnxruntime::InferenceSession::Initialize] Initializing session.
> 2020-07-06 18:50:55.4220585 [I:onnxruntime:, inference_session.cc:848 onnxruntime::InferenceSession::Initialize] Adding default CPU execution provider.
> 2020-07-06 18:50:55.4224222 [I:onnxruntime:test, bfc_arena.cc:15 onnxruntime::BFCArena::BFCArena] Creating BFCArena for Cpu
> 2020-07-06 18:50:55.4224870 [V:onnxruntime:test, bfc_arena.cc:32 onnxruntime::BFCArena::BFCArena] Creating 21 bins of max chunk size 256 to 268435456
> 2020-07-06 18:50:55.4247204 [V:onnxruntime:, inference_session.cc:671 onnxruntime::InferenceSession::TransformGraph] Node placements
> 2020-07-06 18:50:55.4248273 [V:onnxruntime:, inference_session.cc:673 onnxruntime::InferenceSession::TransformGraph] All nodes have been placed on [CPUExecutionProvider].
> 2020-07-06 18:50:55.4249199 [I:onnxruntime:, session_state.cc:25 onnxruntime::SessionState::SetGraph] SaveMLValueNameIndexMapping
> 2020-07-06 18:50:55.4250567 [I:onnxruntime:, session_state.cc:70 onnxruntime::SessionState::SetGraph] Done saving OrtValue mappings.
> 2020-07-06 18:50:55.4266916 [I:onnxruntime:, session_state_initializer.cc:178 onnxruntime::SaveInitializedTensors] Saving initialized tensors.
> 2020-07-06 18:50:55.4268214 [I:onnxruntime:, session_state_initializer.cc:223 onnxruntime::SaveInitializedTensors] Done saving initialized tensors
> 2020-07-06 18:50:55.7311821 [I:onnxruntime:, inference_session.cc:919 onnxruntime::InferenceSession::Initialize] Session successfully initialized.
> Number of inputs = 22
> Number of outputs = 2
> Output 0 : name=label
> Output 1 : name=probabilities
> 
> 2020-07-06 18:51:18.7355209 [I:onnxruntime:, sequential_executor.cc:145 onnxruntime::SequentialExecutor::Execute] Begin execution
> 2020-07-06 18:51:27.4858870 [I:onnxruntime:test, bfc_arena.cc:259 onnxruntime::BFCArena::AllocateRawInternal] Extending BFCArena for Cpu. bin_num:0 rounded_bytes:256
> 2020-07-06 18:51:27.4867688 [I:onnxruntime:test, bfc_arena.cc:143 onnxruntime::BFCArena::Extend] Extended allocation by 1048576 bytes.
> 2020-07-06 18:51:27.4871985 [I:onnxruntime:test, bfc_arena.cc:147 onnxruntime::BFCArena::Extend] Total allocated bytes: 1048832
> 2020-07-06 18:51:27.4872666 [I:onnxruntime:test, bfc_arena.cc:150 onnxruntime::BFCArena::Extend] Allocated memory at 000001D54AC25060 to 000001D54AD25060
> Predicted Class:
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> 0
> ```
> 
> ```
> Versions: 
> skl2onnx: 1.7.0
> onnxruntime: 1.3.0
> ```

Do you see this with other classifiers as well or just XGBoost?

**Comment by Karnav123** [comment]
> > See the difference in output in following image.
> > ![onnxVSpkl](https://user-images.githubusercontent.com/36244620/86598792-47a4e580-bfbb-11ea-8da5-1173bca6923a.PNG)
> > The dataset is for binary classification. The code to generate the model is:
> > ```
> > categorical_pipeline_onehot = Pipeline([
> >              ('OneHot', OneHotEncoder( handle_unknown='ignore'))
> >         ])
> > preprocessor = ColumnTransformer(
> >     transformers=[('Onehot', categorical_pipeline_onehot, CATEGORICAL_ATTRIBUTES_ONEHOT)],
> >     remainder='passthrough')
> > from xgboost import XGBClassifier
> > xgb = XGBClassifier()
> > 
> > clf = Pipeline(steps=[('preprocessor', preprocessor),('cls', xgb)])
> > clf.fit(df_train[predictors], df_train["IsSelected"])
> > 
> > update_registered_converter(
> >     XGBClassifier, 'XGBoostXGBClassifier',
> >     calculate_linear_classifier_output_shapes, convert_xgboost,
> >     options={'nocl': [True, False], 'zipmap': [True, False]})
> > ```
> > 
> > 
> > To convert this model to ONNX the code is:
> > ```
> > def convert_dataframe_schema(df, drop=None):
> >     inputs = []
> >     for k, v in zip(df.columns, df.dtypes):
> >         if drop is not None and k in drop:
> >             continue
> >         if v == 'int64':
> >             t = Int64TensorType([None, 1])
> >         elif v == 'float64':
> >             t = FloatTensorType([None, 1])
> >         else:
> >             t = StringTensorType([None, 1])
> >         inputs.append((k, t))
> >     return inputs
> > 
> > try:
> >     model_onnx_wholed = convert_sklearn(model, 'pipeline_with_onehot', inputs)
> > except Exception as e:
> >     print(e)
> > 
> > with open("XGB_onehot_wholedata.onnx", "wb") as f:
> >     f.write(model_onnx_wholed.SerializeToString())
> > ```
> > 
> > 
> > While prediction I am using C++ APIs as well as Python for onnxruntime. The prediction output generated by the onnx model is all 0 for both C++ and Python which do not match with that of the trained sklearn model.
> > The ONNX model adds Cast operator for features. It may be due to this but I am not sure.
> > The C++ onnxruntime API log is as following:
> > ```
> > 2020-07-06 18:50:47.2890620 [W:onnxruntime:test, abi_session_options.cc:147 OrtApis::SetIntraOpNumThreads] Since openmp is enabled in this build, this API cannot be used to configure intra op num threads. Please use the openmp environment variables to control the number of threads.
> > Using Onnxruntime C++ API
> > 2020-07-06 18:50:55.2296864 [I:onnxruntime:, inference_session.cc:174 onnxruntime::InferenceSession::ConstructorCommon] Creating and using per session threadpools since use_per_session_threads_ is true
> > 2020-07-06 18:50:55.4219403 [I:onnxruntime:, inference_session.cc:830 onnxruntime::InferenceSession::Initialize] Initializing session.
> > 2020-07-06 18:50:55.4220585 [I:onnxruntime:, inference_session.cc:848 onnxruntime::InferenceSession::Initialize] Adding default CPU execution provider.
> > 2020-07-06 18:50:55.4224222 [I:onnxruntime:test, bfc_arena.cc:15 onnxruntime::BFCArena::BFCArena] Creating BFCArena for Cpu
> > 2020-07-06 18:50:55.4224870 [V:onnxruntime:test, bfc_arena.cc:32 onnxruntime::BFCArena::BFCArena] Creating 21 bins of max chunk size 256 to 268435456
> > 2020-07-06 18:50:55.4247204 [V:onnxruntime:, inference_session.cc:671 onnxruntime::InferenceSession::TransformGraph] Node placements
> > 2020-07-06 18:50:55.4248273 [V:onnxruntime:, inference_session.cc:673 onnxruntime::InferenceSession::TransformGraph] All nodes have been placed on [CPUExecutionProvider].
> > 2020-07-06 18:50:55.4249199 [I:onnxruntime:, session_state.cc:25 onnxruntime::SessionState::SetGraph] SaveMLValueNameIndexMapping
> > 2020-07-06 18:50:55.4250567 [I:onnxruntime:, session_state.cc:70 onnxruntime::SessionState::SetGraph] Done saving OrtValue mappings.
> > 2020-07-06 18:50:55.4266916 [I:onnxruntime:, session_state_initializer.cc:178 onnxruntime::SaveInitializedTensors] Saving initialized tensors.
> > 2020-07-06 18:50:55.4268214 [I:onnxruntime:, session_state_initializer.cc:223 onnxruntime::SaveInitializedTensors] Done saving initialized tensors
> > 2020-07-06 18:50:55.7311821 [I:onnxruntime:, inference_session.cc:919 onnxruntime::InferenceSession::Initialize] Session successfully initialized.
> > Number of inputs = 22
> > Number of outputs = 2
> > Output 0 : name=label
> > Output 1 : name=probabilities
> > 
> > 2020-07-06 18:51:18.7355209 [I:onnxruntime:, sequential_executor.cc:145 onnxruntime::SequentialExecutor::Execute] Begin execution
> > 2020-07-06 18:51:27.4858870 [I:onnxruntime:test, bfc_arena.cc:259 onnxruntime::BFCArena::AllocateRawInternal] Extending BFCArena for Cpu. bin_num:0 rounded_bytes:256
> > 2020-07-06 18:51:27.4867688 [I:onnxruntime:test, bfc_arena.cc:143 onnxruntime::BFCArena::Extend] Extended allocation by 1048576 bytes.
> > 2020-07-06 18:51:27.4871985 [I:onnxruntime:test, bfc_arena.cc:147 onnxruntime::BFCArena::Extend] Total allocated bytes: 1048832
> > 2020-07-06 18:51:27.4872666 [I:onnxruntime:test, bfc_arena.cc:150 onnxruntime::BFCArena::Extend] Allocated memory at 000001D54AC25060 to 000001D54AD25060
> > Predicted Class:
> > 0
> > 0
> > 0
> > 0
> > 0
> > 0
> > 0
> > 0
> > 0
> > 0
> > 0
> > 0
> > ```
> > 
> > 
> > ```
> > Versions: 
> > skl2onnx: 1.7.0
> > onnxruntime: 1.3.0
> > ```
> 
> Do you see this with other classifiers as well or just XGBoost?

I have seen this with RandomForest too.

**Comment by prabhat00155** [comment]
Can you give a simple example to reproduce the issue with RandomForestClassifier? I tried the following and didn't see the issue:
```
import numpy as np
import pandas as pd
from onnxmltools import save_model
from onnxruntime import InferenceSession
from skl2onnx.common.data_types import StringTensorType, Int64TensorType
from skl2onnx.convert import convert_sklearn
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

data = pd.DataFrame({'gender': ['male', 'female', 'male', 'female', 'male'],
              'age': [19, 22, 34, 55, 67],
              'profession': ['student', 'student', 'teacher', 'teacher', 'teacher']
             })
labels = [1, 0, 0, 1, 1]


categorical_pipeline_onehot = Pipeline([('OneHot', OneHotEncoder(handle_unknown='ignore'))])
preprocessor = ColumnTransformer(
    transformers=[('Onehot', OneHotEncoder(), [0, 2])],
    remainder='passthrough')
model = RandomForestClassifier()

clf = Pipeline(steps=[('preprocessor', preprocessor),('cls', model)])
clf.fit(data, labels)

onnx_fs = convert_sklearn(clf, 'ada',
                          [
                              ('float_input1', StringTensorType([None, 1])),
                              ('float_input2', Int64TensorType([None, 1])),
                              ('float_input3', StringTensorType([None, 1]))
                          ])

save_model(onnx_fs, 'onnx_model.onnx')
sess = InferenceSession('onnx_model.onnx')

sess.run(None, input_feed={'float_input1': data['gender'].values.reshape((-1, 1)),
                           'float_input2': data['age'].values.reshape((-1, 1)),
                          'float_input3': data['profession'].values.reshape((-1, 1))})
```
Output:
```
[array([1, 0, 0, 1, 1], dtype=int64),
 [{0: 0.3600003123283386, 1: 0.6399996876716614},
  {0: 0.7100000381469727, 1: 0.28999999165534973},
  {0: 0.690000057220459, 1: 0.3099999725818634},
  {0: 0.1300005316734314, 1: 0.8699994683265686},
  {0: 0.1600005030632019, 1: 0.8399994969367981}]]
```

**Comment by xadupre** [comment]
May I close the issue?

**Comment by Karnav123** [comment]
> May I close the issue?

Yes
