### ISSUE TITLE
Can scikit-learn still be used to train the converted onnx models?

### ISSUE THREAD

**Issue by linkerzhang** [onnx/sklearn-onnx#512]
Is it possible for scikit-learn to be used to train the converted onnx models? or the converted onnx has to be converted back to some format so that scikit-learn can train it again. @xadupre

**Comment by xadupre** [comment]
The ONNX model cannot be trained again. The ONNX format does not keep the original structure or the coefficient. However, we could imagine that the model structure is stored in the metadata of ONNX. The short answer is no.

**Comment by xadupre** [comment]
The answer may be different depending on your model. You'll find more details here: [Use ONNX Runtime for Training](https://www.onnxruntime.ai/docs/get-started/training.html).
