### ISSUE TITLE
fantastic library. sklearn MultiOutputRegressor support ?

### ISSUE THREAD

**Issue by doolingdavid** [onnx/sklearn-onnx#514]
I think a great addition would be support for the scikit-learn multioutputregressor estimator class, so that such models can be contained in one .onnx.   The workable workaround is to have separate .onnx files for each output column, so not a crucial issue by any means! thank you.

**Comment by xadupre** [comment]
That should be an easy fix.

**Comment by xadupre** [comment]
I'll close the issue. This model is now supported.
