### ISSUE TITLE
why not support windows 7?

### ISSUE THREAD

**Issue by whidbey** [onnx/sklearn-onnx#532]
C:\Users\Administrator\miniconda3\envs\py3.7\lib\site-packages\onnxruntime\capi\
onnxruntime_validation.py:27: UserWarning: Unsupported Windows version (7). ONNX
 Runtime supports Windows 10 and above, only.
  __my_distro_ver__)

so far I can run onnxruntime.dll on my win7 on 1.14version.

**Comment by xadupre** [comment]
The warnings just tells onnxruntime is not tested on Windows 7, it may work, newer versions may break.

**Comment by whidbey** [comment]
thanks.
