### ISSUE TITLE
Pipeline example not working - AttributeError: 'ColumnTransformer' object has no attribute 'transformers_'

### ISSUE THREAD

**Issue by pederpansen** [onnx/sklearn-onnx#552]
Hi,

I'm new to ONNX and just tried out the example scikit-learn pipeline serialization (sklearn 0.23.2, skl2onnx 0.17.0) from here: http://onnx.ai/sklearn-onnx/pipeline.html

This results in an error:

```
~/.pyenv/versions/3.7.5/envs/vouchers-training/lib/python3.7/site-packages/skl2onnx/_parse.py in _parse_sklearn_column_transformer(scope, model, inputs, custom_parsers)
    241     transformed_result_names = []
    242     # Encode each transform as our IR object
--> 243     for name, op, column_indices in model.transformers_:
    244         if op == 'drop':
    245             continue

AttributeError: 'ColumnTransformer' object has no attribute 'transformers_'
```

Is there a version constraint between sklearn and skl2onnx? Should I use different versions which are known to be compatible?

**Comment by xadupre** [comment]
This error happens when the model is not fit. *transformers_* is created after the model is trained.

**Comment by pederpansen** [comment]
Now that's embarrassing. Closing.
