### ISSUE TITLE
RandomForestClassifier converter

### ISSUE THREAD

**Issue by smstec** [onnx/sklearn-onnx#562]
I'm converting a trained RandomForestClassifier to ONNX.  I get the same outputs from calling `session.run(...)` as when I call `predict_proba(...)` in sklearn.  That's great and solves half of my problem.

I also have a need to call [`apply(...)`](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html?highlight=randomforestclassifier#sklearn.ensemble.RandomForestClassifier.apply) to get the leaf indices.  Is there an equivalent method in onnxruntime or an option I can apply in conversion to get the leaves?

**Comment by xadupre** [comment]
I had to do it to write the converter for IsolationForest. I could make it available in this converter with an option. Do you need both prediction and leaf indices or just the leaf indices? With the current ONNX specifications, this method requires to create two random forest in ONNX, one for the prediction, one for the leaves index. That will multiply the computing by two.

**Comment by smstec** [comment]
I need both prediction and the leaves.  I'll gladly run two RFs.

**Comment by xadupre** [comment]
I started to work on that in #563. It works for decision tree, I have to extend it to random forest.

**Comment by xadupre** [comment]
RandomForest was added too.
