### ISSUE TITLE
Request: KernelPCA addition

### ISSUE THREAD

**Issue by tomrod** [onnx/sklearn-onnx#582]
KernelPCA would be a very helpful addition to ONNX. Currently PCA is supported, but KernelPCA is not.

**Comment by tomrod** [comment]
Error output directed here:

`MissingShapeCalculator: Unable to find a shape calculator for type '<class 'sklearn.decomposition._kernel_pca.KernelPCA'>'.
It usually means the pipeline being converted contains a
transformer or a predictor with no corresponding converter
implemented in sklearn-onnx. If the converted is implemented
in another library, you need to register
the converted so that it can be used by sklearn-onnx (function
update_registered_converter). If the model is not yet covered
by sklearn-onnx, you may raise an issue to
https://github.com/onnx/sklearn-onnx/issues
to get the converter implemented or even contribute to the
project. If the model is a custom model, a new converter must
be implemented. Examples can be found in the gallery.`

**Comment by xadupre** [comment]
It should be doable. Is it urgent?

**Comment by tomrod** [comment]
It would be very helpful to some work flows. I'm not sure how yall prioritize the work. KernelPCA should generalize PCA since you can call a linear basis for KPCA

**Comment by xadupre** [comment]
Closing the issue. The PR was merged and a new release will be published soon.
