### ISSUE TITLE
Unable to find release of version 1.7.1 via pip

### ISSUE THREAD

**Issue by Sarthak-Agrawal** [onnx/sklearn-onnx#588]
I am facing issues addressed here #478 and understand that this would have been solved in release 1.7.1. The last-mentioned release is on Jun 8 2020 version 1.7.0 [here](https://pypi.org/project/skl2onnx/).

**Comment by gxlarson** [comment]
I'm not part of onnx or sklearn-onnx but I was able to get 1.7.1 by doing:

`pip install git+https://github.com/onnx/sklearn-onnx.git`

There are instructions in the README that say "If you install sklearn-onnx from its source code, you must set the environment variable `ONNX_ML=1` before installing the onnx package."

**Comment by svenski** [comment]
I'm also interested in getting the newest version (1.7.1) from PyPi. The newest [mlprodict](https://github.com/sdpython/mlprodict) version depends on it.

**Comment by xadupre** [comment]
The latest version of mlprodict is being tested with a branch which includes all the modifications scheduled to be merged in sklearn-onnx 1.8.0, see https://github.com/sdpython/mlprodict/blob/master/requirements.txt#L49.

**Comment by xadupre** [comment]
Closing the issue as version 1.9.2 was released.
