### ISSUE TITLE
sparse matrix support

### ISSUE THREAD

**Issue by jolio007** [onnx/sklearn-onnx#590]
I'm writing this issue because I can't seems to find any doc about it. 
My training data is a sparse matrix.
I'm stuck at what to put in either of the ways to convert a sklearn model. 

```
initial_type = [("input", SparseTensorType ??? ([None, 1]))]
onnx = to_onnx(modele_prediction, initial_types=initial_type, target_opset=7)
```
when I do 
`
onnx = convert_sklearn(modele_prediction, X=training_data, target_opset=7)
`
I get  `convert_sklearn() got an unexpected keyword argument 'X`
My training data being a ```
<267712x14525 sparse matrix of type <class 'numpy.float64'>
	with 2717713 stored elements in Compressed Sparse Row format>
```

**Comment by jolio007** [comment]
When I changed the conversion to being 
`onnx = to_onnx(modele_prediction, training_data,  target_opset=7)`
I got an error message `Unsupported type '<class 'scipy.sparse.csr.csr_matrix'>'.`

**Comment by jolio007** [comment]
I saw an example that helped me out

**Comment by ckhazan** [comment]
> I saw an example that helped me out

@jolio007 can you share a link to that example please

**Comment by rainyl** [comment]
> I saw an example that helped me out

so could you please share the resolution, thanks!
