### ISSUE TITLE
Is it possible to use SimpleImputer to accept input/output of double/float64?

### ISSUE THREAD

**Issue by ag-tcm** [onnx/sklearn-onnx#616]
I've got an sklearn SimpleImputer that I'd like to feed double/float64 tensors and get double/float64 tensors back.
According to the [Onnx runtime Imputer docs](https://github.com/onnx/onnx/blob/master/docs/Operators-ml.md#ai.onnx.ml.Imputer), double type tensors are supported. I can create the model without issue, but when I try to use the model I get an exception (from the Java Onnx runtime) while creating the session:
`ai.onnxruntime.OrtException: Error code - ORT_NOT_IMPLEMENTED - message: Could not find an implementation for the node Imputer:Imputer(1)`

The workaround appears to be to use the CastTransformer to cast the double input tensor to float as the first item in a pipeline, followed by the SimpleImputer.

I'd prefer not to apply the cast and use doubles from end to end. 

Side note: I noticed a comment in [test_sklearn_imputer_converter.py](https://github.com/onnx/sklearn-onnx/blob/b7eeb6ce63953c2d3434750596eda7aebad50316/tests/test_sklearn_imputer_converter.py) about sklearn converting "everything into float before looking into missing values". Perhaps this is related?

Here is the code to reproduce the exception as well as the workaround:
python
```
import skl2onnx
from skl2onnx.helpers.onnx_helper import save_onnx_model
from skl2onnx.common.data_types import DoubleTensorType
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from skl2onnx.sklapi import CastTransformer
import numpy as np

model = SimpleImputer(missing_values=float(np.nan), strategy="constant", fill_value=0.5)
data = np.array([[1, 2], [np.nan, 3], [7, 6]])
model.fit(data)

onnx_model = skl2onnx.to_onnx(model, X=data, initial_types=[('X', DoubleTensorType([None, 2]))], final_types=[('y', DoubleTensorType([None]))])
save_onnx_model(onnx_model, r'D:\test_imputer.onnx')

onnx_model = skl2onnx.to_onnx(Pipeline([('cast32', CastTransformer(dtype=np.float32)), ('imp', model)]), X=data, initial_types=[('X', DoubleTensorType([None, 2]))], final_types=[('y', DoubleTensorType([None]))])
save_onnx_model(onnx_model, r'D:\test_imputer2.onnx')
```

java
```
	@Test
	public void testImputerDouble() throws OrtException {
		OrtEnvironment env = OrtEnvironment.getEnvironment();

//Exception is thrown here
		Assertions.assertThrows(OrtException.class, () -> env.createSession("D:\\test_imputer.onnx"));
		
//No problem loading this one
		env.createSession("D:\\test_imputer2.onnx");
	}
```

**Comment by ag-tcm** [comment]
Would something like this solution for [Discrepencies with StandardScaler](http://onnx.ai/sklearn-onnx/auto_examples/plot_cast_transformer.html) which uses the 'div_cast' option be the approach to take here as well?

**Comment by xadupre** [comment]
I started to modify the converters to make them support double (see #566). Before that, I had to make onnxruntime support double in many operators. This should be available with the next release and I'll be able to check the converter has no discrepency.

**Comment by ag-tcm** [comment]
Thanks, looking forward to the next release!

**Comment by xadupre** [comment]
Did you try with the latest release?

**Comment by ag-tcm** [comment]
Sorry, ended up sticking with a workaround for this and haven't gotten a chance to test with the latest release.

**Comment by xadupre** [comment]
Casting to float is not something possible in your case? (see https://onnx.ai/sklearn-onnx/auto_tutorial/plot_ebegin_float_double.html#casttransformer).

**Comment by ag-tcm** [comment]
Yes, casting to float is the workaround in this case.
