### ISSUE TITLE
skl2onnx cannot be installed from its source distribution

### ISSUE THREAD

**Issue by leifwalsh** [onnx/sklearn-onnx#624]
The sdist on PyPI does not contain requirements.txt, yet setup.py needs to read it, so `pip install` from a sdist throws an exception (cannot read requirements.txt). Please create a MANIFEST.in to add this so that installing from released source packages works: https://packaging.python.org/guides/using-manifest-in/

**Comment by xadupre** [comment]
Addressed in PR #625.
