### ISSUE TITLE
how to control LightGBM outputs type?

### ISSUE THREAD

**Issue by LmYjQ** [onnx/sklearn-onnx#628]
Can anyone give me some explaination or document about the parameter in?
`update_registered_converter(
LGBMClassifier, 'LightGbmLGBMClassifier',
    calculate_linear_classifier_output_shapes, convert_lightgbm,
   options={'nocl': [True, False], 'zipmap': [True, False]}
)`

I want to get the output data type as tensor(float) instead of (seq(map(int64,tensor(float)))
`
import onnxruntime as rt
onnx_name = 'lgb_model.onnx'
session = rt.InferenceSession(onnx_name)
data_type = session.get_outputs()[1].type
`

**Comment by xadupre** [comment]
Options are used to change the behaviour of a converter for a specific model or all model of the same class. You may write `options={LGBMClassifier: {'zipmap': False}}`. That will change the output type in the ONNX graph for every LGBMClassifier in your pipeline. You'll find more details here: http://onnx.ai/sklearn-onnx/auto_tutorial/plot_dbegin_options.html.

**Comment by LmYjQ** [comment]
> Options are used to change the behaviour of a converter for a specific model or all model of the same class. You may write `options={LGBMClassifier: {'zipmap': False}}`. That will change the output type in the ONNX graph for every LGBMClassifier in your pipeline. You'll find more details here: http://onnx.ai/sklearn-onnx/auto_tutorial/plot_dbegin_options.html.

Thank you ,that's very helpful.
