### ISSUE TITLE
Release sdist

### ISSUE THREAD

**Issue by xhochy** [onnx/sklearn-onnx#630]
It would be nice if the sdist would also be released on PyPI. My intention is to package this for conda-forge and conda recipes are usually build from the sdist. Building from the Github tarball is also possible but using the sdist is preferable.

**Comment by xadupre** [comment]
That was done for 1.9.0. Let me know if that's ok that way.

**Comment by xadupre** [comment]
Closing the issue. Version 1.9.2 was release with sdist too.
