### ISSUE TITLE
One question about kmeans converter

### ISSUE THREAD

**Issue by humphrey-newcoder** [onnx/sklearn-onnx#633]
Hi guys, you have did a wonderful job for converting the sklearn models into onnx models. Here, when I read convert_sklearn_kmeans, I have a question. As we know, kmeans needs to keep updating the centers to a local optimal. But in this function, I have seen the comment 'Computation graph of distances to all centroids for a batch of examples.', so from my view, this implements one run for calculating the distances instead of iterating (like I thought). So how can this achieve the same result as the original kmeans do?

**Comment by xadupre** [comment]
I'm not sure I fully understood what you meant. There is no notion of streaming in ONNX and the ONNX graph is meant for training. Once the graph is built, it is not supposed to be updated. You may iterate by computing the predictions row by row but it is slower than computing all the predictions in one batch.

**Comment by humphrey-newcoder** [comment]
> I'm not sure I fully understood what you meant. There is no notion of streaming in ONNX and the ONNX graph is meant for training. Once the graph is built, it is not supposed to be updated. You may iterate by computing the predictions row by row but it is slower than computing all the predictions in one batch.

So you mean, in ONNX graph, we only need to implement the calculation of distances of different data points to nearest center points. The update of center points in Kmeans algorithm will be replaced by the training procedures?

**Comment by xadupre** [comment]
No training happens after ONNX conversion. The model is trained in scikit-learn and must be saved. Once converted in ONNX, the model is frozen and cannot be updated anymore. It needs to be updated in scikit-learn and converted again.

**Comment by xadupre** [comment]
Let me know if that answered your questions.

**Comment by xadupre** [comment]
Closing the issue, feel free to reopen it.
