### ISSUE TITLE
Lib raises runtime error during ada-boost conversions

### ISSUE THREAD

**Issue by ellil4** [onnx/sklearn-onnx#647]
Lib raises runtime error during ada-boost conversions. This occurs in calling both convert_sklearn() and to_onnx() in version 1.8.0.
After replace the package with ver. 1.7.0, this error vanished.
The error was raised from ln. 251 of onnx_ops.py.

**Comment by xadupre** [comment]
Is it possible to know the base estimator used?

**Comment by xadupre** [comment]
Could you try again with the latest package and copy paste the call stack if the error is still happening?

**Comment by xadupre** [comment]
This should be fixed by now. Closing the issue. Feel free to reopen.
