### ISSUE TITLE
runing error

### ISSUE THREAD

**Issue by chengl007** [onnx/sklearn-onnx#673]
onnx_model = onnxmltools.convert_sklearn(skl_model, initial_types=input_data_type)  got error:
Unable to find a shape calculator for type '<class 'dict'>'.
This why

**Comment by chengl007** [comment]
initial_types  how to structure  DictionaryType

**Comment by xadupre** [comment]
Is it possible to know more about the context? initial_types must be a list of tuple (name, type) where type is usually a tensor or at least a [DataType](https://github.com/microsoft/onnxconverter-common/blob/master/onnxconverter_common/data_types.py#L11).

**Comment by xadupre** [comment]
Closing the issue, feel free to reopen it.
