### ISSUE TITLE
Scikit-learn version requirements not included in requirements.txt

### ISSUE THREAD

**Issue by WouterDX** [onnx/sklearn-onnx#68]
Using scikit-learn 0.18.2 on python 3.6, I get "ModuleNotFoundErrors" when trying to import skl2onnx, for several imports related to scikit-learn.

In a stable python repo, I would expect the requirements.txt to describe version dependencies on third-party libraries . It seems this was ignored in this repo.

**Comment by c-bata** [comment]
It looks this issue is fixed at #94.

https://github.com/onnx/sklearn-onnx/blob/master/requirements.txt#L5

**Comment by vinitra** [comment]
Yes! Thanks @WouterDX and @c-bata. Closing this issue as it's been resolved by @xadupre.
