### ISSUE TITLE
SimpleImputer should support String type

### ISSUE THREAD

**Issue by victornoel** [onnx/sklearn-onnx#681]
Hi,

I'm getting this error:
```
RuntimeError: Operator SklearnSimpleImputer (type: SklearnSimpleImputer) got an input merged_columns with a wrong type <class 'onnxconverter_common.data_types.StringTensorType'>. Only [<class 'onnxconverter_common.data_types.FloatTensorType'>, <class 'onnxconverter_common.data_types.Int64TensorType'>, <class 'onnxconverter_common.data_types.DoubleTensorType'>] are allowed
```

But when using the option `strategy="most_frequent"` or `strategy="constant"`, it supports strings, see https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html.

**Comment by xadupre** [comment]
[ONNX Imputer](https://github.com/onnx/onnx/blob/master/docs/Operators-ml.md#aionnxmlimputer) does not support strings. That's why the converter does not support strings either. The change is not a simple one. Is this something urgent?

**Comment by xadupre** [comment]
One option would to decompose SimpleImputer(string) into SimpleImputer(int) + LabelEncoder. That needs a code change. I'll see what I can do about it.

**Comment by victornoel** [comment]
@xadupre :+1:

**Comment by victornoel** [comment]
Hey @xadupre, it has been some time, and there is still one thing that does not work: when I use `None` as the value for `missing_values`:
```
SimpleImputer(missing_values=None, strategy='most_frequent')
```

I get this error:
```
NotImplementedError: The converter is implemented when the missing values are string not <class 'NoneType'>.
```

**Comment by gs-alt** [comment]
I get the same error as @victornoel

**Comment by xadupre** [comment]
This unit test shows that this case should be supported: https://github.com/onnx/sklearn-onnx/blob/master/tests/test_sklearn_imputer_converter.py#L143. It is possible to get a code sample to understand what the differences are?

**Comment by gs-alt** [comment]
@xadupre That unit test uses `missing_values=""` but the error pops up when `missing_values=None`

I can replicate the error with the following setup:

**Environment**
```
scikit-learn==0.24.1
onnx==1.9.0
onnxruntime==1.9.0
```

**Code** - this is a simplified version of the unit test (I just quickly put all the code in the local file). 

```python
import onnx
from onnxruntime import InferenceSession
from onnxruntime import __version__ as ort_version
from skl2onnx import __max_supported_opset__ as max_opset
import unittest
from distutils.version import StrictVersion
import numpy as np
import sklearn

try:
    from sklearn.preprocessing import Imputer
except ImportError:
    Imputer = None

try:
    from sklearn.impute import SimpleImputer
except ImportError:
    # changed in 0.20
    SimpleImputer = None

from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import (
    FloatTensorType, Int64TensorType, StringTensorType)

def max_onnxruntime_opset():
    """
    See `Versioning.md
    <https://github.com/microsoft/onnxruntime/blob/
    master/docs/Versioning.md>`_.
    """
    vi = StrictVersion(ort_version.split('+')[0])
    if vi >= StrictVersion("1.9.0"):
        return 15
    if vi >= StrictVersion("1.8.0"):
        return 14
    if vi >= StrictVersion("1.6.0"):
        return 13
    if vi >= StrictVersion("1.3.0"):
        return 12
    if vi >= StrictVersion("1.0.0"):
        return 11
    if vi >= StrictVersion("0.4.0"):
        return 10
    if vi >= StrictVersion("0.3.0"):
        return 9
    return 8

import os
TARGET_OPSET = int(
    os.environ.get(
        'TEST_TARGET_OPSET',
        min(max_onnxruntime_opset(),
            min(max_opset,
                onnx.defs.onnx_opset_version()))))


class TestSklearnImputerConverter(unittest.TestCase):

    def _check_outputs_strings(self, model, model_onnx, data):
        idata = {'input': np.array(data).astype(np.str_)}
        sess = InferenceSession(model_onnx.SerializeToString())
        res = sess.run(None, idata)[0]
        exp = model.transform(data)
        if list(exp.ravel()) != list(res.ravel()):
            raise AssertionError(
                "Unexpected output expected %r != %r." % (exp, res))

    @unittest.skipIf(SimpleImputer is None,
                     reason="SimpleImputer changed in 0.20")
    @unittest.skipIf(
        StrictVersion(sklearn.__version__) < StrictVersion('0.24'),
        reason="SimpleImputer does not support strings")
    def test_simple_imputer_string_inputs_int_mostf(self):
        model = SimpleImputer(
            strategy="most_frequent", fill_value="nan", missing_values="")
        data = [["s1", "s2"], ["", "s3"], ["s7", "s6"], ["s8", ""]]
        model.fit(data)
        model_onnx = convert_sklearn(
            model, "scikit-learn simple imputer",
            [("input", StringTensorType([None, 2]))],
            target_opset=TARGET_OPSET)
        self.assertIn("ai.onnx.ml", str(model_onnx))
        self.assertTrue(model_onnx.graph.node is not None)
        self.assertEqual(len(model_onnx.graph.output), 1)
        self._check_outputs_strings(model, model_onnx, data)


if __name__ == "__main__":
    unittest.main()
```

You can get the following result by running it.

**IF  `missing_values=""` THEN** 

```
.
----------------------------------------------------------------------
Ran 1 test in 0.028s

OK
```

**IF `missing_values=None` THEN** 

```
E
======================================================================
ERROR: test_simple_imputer_string_inputs_int_mostf (__main__.TestSklearnImputerConverter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:/Users/gseif/AppData/Roaming/JetBrains/PyCharmCE2020.2/scratches/scratch_7.py", line 81, in test_simple_imputer_string_inputs_int_mostf
    target_opset=TARGET_OPSET)
  File "C:\Users\gseif\AppData\Local\Programs\Python\Python36\lib\site-packages\skl2onnx\convert.py", line 186, in convert_sklearn
    remove_identity=not intermediate, verbose=verbose)
  File "C:\Users\gseif\AppData\Local\Programs\Python\Python36\lib\site-packages\skl2onnx\common\_topology.py", line 1363, in convert_topology
    topology.convert_operators(container=container, verbose=verbose)
  File "C:\Users\gseif\AppData\Local\Programs\Python\Python36\lib\site-packages\skl2onnx\common\_topology.py", line 1200, in convert_operators
    self.call_converter(operator, container, verbose=verbose)
  File "C:\Users\gseif\AppData\Local\Programs\Python\Python36\lib\site-packages\skl2onnx\common\_topology.py", line 1015, in call_converter
    conv(self.scopes[0], operator, container)
  File "C:\Users\gseif\AppData\Local\Programs\Python\Python36\lib\site-packages\skl2onnx\common\_registration.py", line 26, in __call__
    return self._fct(*args)
  File "C:\Users\gseif\AppData\Local\Programs\Python\Python36\lib\site-packages\skl2onnx\operator_converters\imputer_op.py", line 31, in convert_sklearn_imputer
    "are string not %r." % type(op.missing_values))
NotImplementedError: The converter is implemented when the missing values are string not <class 'NoneType'>.

----------------------------------------------------------------------
Ran 1 test in 0.004s

FAILED (errors=1)
```

**Comment by xadupre** [comment]
I see. This was not implemented on purpose because ONNX is strongly typed. If the input type is string, the missing value must be encoded as a string. The error message may be not clear enough but that's a consequence of ONNX strong types.

**Comment by victornoel** [comment]
@xadupre right, it makes sense from an inference point of view. What would be the way to ensure we can use `None` for `missing_values` (useful for training) while allowing sklearn-onnx to work?

Maybe sklearn-onnx could only use `statistics_` to detect types and not check `missing_values` at all for validation? I'm not sure how feasible it is though :)

**Comment by victornoel** [comment]
Or maybe just ignore `missing_values` if it is `None`, since if I understand correctly, in onnx, during inference, a `StringType` input cannot be none/null/undefined?

**Comment by xadupre** [comment]
True, the converter does not automatically replace it by a string or an empty string. Only the user can do that.

**Comment by xadupre** [comment]
I'll close the issue. Feel to reopen it.

**Comment by saramohammadinejad** [comment]
Does onnxmltools.convert_lightgbm support categorical features? When I have categorical features I receive the following error:

check_input_and_output_types(operator, good_input_types=[FloatTensorType, Int64TensorType])
  File "/scratch/pyvenv/lib64/python3.8/site-packages/onnxconverter_common/utils.py", line 322, in check_input_and_output_types
    raise RuntimeError('Operator %s (type: %s) got an input %s with a wrong type %s. Only %s are allowed'
RuntimeError: Operator LgbmClassifier (type: LgbmClassifier) got an input string_input with a wrong type <class 'onnxconverter_common.data_types.StringTensorType'>. Only [<class 'onnxconverter_common.data_types.FloatTensorType'>, <class 'onnxconverter_common.data_types.Int64TensorType'>] are allowed

Here is my code:
initial_type = [('string_input', StringTensorType([None, 3]))]
onnx = onnxmltools.convert_lightgbm(lgbm_model, 
                initial_types=initial_type)
