### ISSUE TITLE
Custom transform with dictionary mapping

### ISSUE THREAD

**Issue by itacdonev** [onnx/sklearn-onnx#686]
I am doing a weight of evidence custom transformer for the sklearn model, which I am trying to convert to ONNX. 

In the custom transformer class there is a dictionary of interval keys with their corresponding float values, which maps on X. If the value of X is in the interval then the value from the dictionary is taken.

From the `transform` part of the custom transformer:

```python
# Round the values to reduce the need for precision
X[feature] = np.round(X[feature], decimals = 2)

# Map the WOE values
X[feature] = X[feature].map(self.woe_dict[i])
```

Example of the `woe_dict`:
```python
value=[OrderedDict([
(Interval(-inf, -0.05, closed='right'), -0.719), 
(Interval(-0.05, 0.32, closed='right'), -0.285), ...
```

How can I write the converter for such dict mapping?

**Comment by xadupre** [comment]
Is there anyway to use an OrdinalEncoder? This preprocessing can be convert using sklearn-onnx.

**Comment by itacdonev** [comment]
Not sure that this would work since the value of the input `X[feature]` is numeric (float). I need something that would check in which interval the value of the feature is, given the dictionary, and then assign its value form the dictionary. So, given the above example, if I have that the `X[feature] = 0.1` then the transformed value would be `-0.285`.

**Comment by xadupre** [comment]
Then the best would be to use a tree ensemble to do that. Two options, implements a function which writes that node or trains a DecisionTreeClassifier with no error on a specific dataset (but the thresholds might be different). Which one do you prefer?

**Comment by xadupre** [comment]
Let me know if PR answers your need. I created a transformer `WOETransformer(intervals, labels, onehot=False)` which returns a label associated to an interval a feature falls into. I'll add an example in the documentation later. The last unit test in the PR would be the starting point.

**Comment by xadupre** [comment]
Closing the issue. Feel free to reopen.
