### ISSUE TITLE
Issues in loading Sklearn's SVC model in scala/Java with ONXX 

### ISSUE THREAD

**Issue by aakashveera** [onnx/sklearn-onnx#693]
For a demonstration of this issue, I have used IRIS as the data.
I have created models for IRIS data with sklearn's Randomforest, Logistic Regression and SVC and dumped all three using onxx library. 
Now while accessing the onxx models in scala the RF model and logistic-reg model works as expected

![image](https://user-images.githubusercontent.com/54843933/127280588-604759af-f50d-4059-9b79-c70dcc0da60e.png)

Now while loading the SVC model trained and dumped in the same way it is giving some weird output as shown in the image and couldn't able to parse the results.

![image](https://user-images.githubusercontent.com/54843933/127280790-f21d91e7-3a27-4323-8eaf-28aaf71ff394.png)

(usually this happens when we print a java array. But this isn't a java array. Indexing causes error)

Initally had issues in saving svc model. Referred https://github.com/onnx/sklearn-onnx/issues/302 and was able to save the model. But now I am getting errors in parsing the output only in scala/Java. while loading the saved onnx model in Python the results were good as expected.

**Comment by xadupre** [comment]
If the model works in python, this might be an issue for the java binding of onnxruntime. Is it possible to share the onnx file?

**Comment by aakashveera** [comment]
Hi @xadupre,

The zip file has the both Logistic Regression as well as SVC model.

[models.zip](https://github.com/onnx/sklearn-onnx/files/6920585/models.zip)

**Comment by xadupre** [comment]
The SVC model outputs two arrays (label, predictions), the logistic regression outputs one array, one map (the ONNX graph contains a ZipMap node). The SVC models was converted with the option `{SVC: {'zipmap': False}}`. In one of your comments, you say the error happens when a java array is printed. Could these two facts be related?

**Comment by aakashveera** [comment]
Seems its returning label and predictions zipped. zipmap:True and False both has no effect in scala. how to get only the predictions?

**Comment by xadupre** [comment]
It should have some effect, it changes the ONNX graph. The effect should be the same in any language: https://onnx.ai/sklearn-onnx/parameterized.html#zipmap, https://onnx.ai/sklearn-onnx/auto_tutorial/plot_dbegin_options.html#option-zipmap.

**Comment by Craigacp** [comment]
I responded to this issue on ONNX Runtime (https://github.com/microsoft/onnxruntime/issues/8525), but it looks like the printed output is a 2d Java array, and it can be indexed just fine. I loaded the model up in ORT via jshell and inspected the output without issue.

```java
jshell> import ai.onnxruntime.*

jshell> var env = OrtEnvironment.getEnvironment()
env ==> OrtEnvironment(name=ort-java,logLevel=ORT_LOGGING_LEVEL_WARNING)

jshell> var session = env.createSession("svc_iris.onnx", new OrtSession.SessionOptions())
session ==> OrtSession(numInputs=1,numOutputs=2)

jshell> session.getOutputInfo()
$4 ==> {label=NodeInfo(name=label,info=TensorInfo(javaType=INT64,onnxType=ONNX_TENSOR_ELEMENT_DATA_TYPE_INT64,shape=[-1])), probabilities=NodeInfo(name=probabilities,info=TensorInfo(javaType=FLOAT,onnxType=ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT,shape=[-1, 3]))}

jshell> var inputArr = new float[1][4]
inputArr ==> float[1][] { float[4] { 0.0, 0.0, 0.0, 0.0 } }

jshell> var tensor = OnnxTensor.createTensor(env,inputArr)
tensor ==> OnnxTensor(info=TensorInfo(javaType=FLOAT,onnxTyp ... _TYPE_FLOAT,shape=[1, 4]))

jshell> var result = session.run(Map.of("float_input",tensor))
result ==> ai.onnxruntime.OrtSession$Result@2d363fb3

jshell> var first_output = result.get(0)
first_output ==> OnnxTensor(info=TensorInfo(javaType=INT64,onnxTyp ... ATA_TYPE_INT64,shape=[1]))

jshell> var second_output = result.get(1)
second_output ==> OnnxTensor(info=TensorInfo(javaType=FLOAT,onnxTyp ... _TYPE_FLOAT,shape=[1, 3]))

jshell> first_output.getValue()
$14 ==> long[1] { 0 }

jshell> second_output.getValue()
$15 ==> float[1][] { float[3] { 2.086214, -0.08464867, 0.9971936 } }
```
