### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by janjagusch** [onnx/sklearn-onnx#699]
Hi!

Could you please release a new version that contains that changes made in https://github.com/onnx/sklearn-onnx/pull/697?

Thanks a lot. 🙂

**Comment by xadupre** [comment]
Ok. I'll do that today.

**Comment by janjagusch** [comment]
> Ok. I'll do that today.

Thanks!

**Comment by xadupre** [comment]
Version 1.9.2 is released.
