### ISSUE TITLE
I am facing issues in predicting througn onnx runtime

### ISSUE THREAD

**Issue by RAOMMA** [onnx/sklearn-onnx#716]
import onnxruntime as rt
import numpy
sess = rt.InferenceSession("rf_svc.onnx")
input_name = sess.get_inputs()[0].name
label_name = sess.get_outputs()[0].name
pred_onx = sess.run(None,X_train)[0]

**Error**

TypeError                                 Traceback (most recent call last)
<ipython-input-80-017422b2001d> in <module>()
      4 input_name = sess.get_inputs()[0].name
      5 label_name = sess.get_outputs()[0].name
----> 6 pred_onx = sess.run(None,X_train)[0]

/usr/local/lib/python3.7/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py in run(self, output_names, input_feed, run_options)
    186             output_names = [output.name for output in self._outputs_meta]
    187         try:
--> 188             return self._sess.run(output_names, input_feed, run_options)
    189         except C.EPFail as err:
    190             if self._enable_fallback:

TypeError: run(): incompatible function arguments. The following argument types are supported:
    1. (self: onnxruntime.capi.onnxruntime_pybind11_state.InferenceSession, arg0: List[str], arg1: Dict[str, object], arg2: onnxruntime.capi.onnxruntime_pybind11_state.RunOptions) -> List[object]

Invoked with: <onnxruntime.capi.onnxruntime_pybind11_state.InferenceSession object at 0x7f196c3b1230>, ['output_label', 'output_probability'], 15354        Antatt forbruk avløp i år 931521241 942110464
3136                Månedlig fastbeløp 948728249 880396072
11081                 Strøm, juni 2020 917807086 991854126
19201             Strøm, november 2020 948722941 880396072
8765     Fast utlønning 1 stk á kr 577,50 959679444 946...
                               ...                        
6731                  Strøm, juni 2020 948969858 880396072
16079              Eiendomsskatt bolig 948720442 942110464
7937                      Øreavrunding 975509648 890729142
11406                        Feiegebyr 961395038 942110464
3672              Administrasjonsgebyr 958748159 880396072
Name: Input_Data, Length: 15393, dtype: object, None

**Comment by xadupre** [comment]
You probably defined the input as `StringTensorType([None, 1])` so your input array must have a vector with two dimensions. You should write `X_train.values.reshape((-1, 1))`.

**Comment by RAOMMA** [comment]
It worked thanks 
Can you also tell me how to get accuracy score through it if possible.

**Comment by xadupre** [comment]
The score is not included in the ONNX graph. You'll need to call one scikit-learn method to compute it using ONNX predictions.

**Comment by RAOMMA** [comment]
Ok Sir Thanks 
I am closing this Issue

**Comment by RAOMMA** [comment]
Hi is it possible to predict probability 
Like we do in the model prediction 
Model.predict_proba

**Comment by xadupre** [comment]
You can write ``convert_sklearn(text_clf_svc, initial_types=initial_type, options={'zipmap': False})`` to get the probabilities as a tensor. Probabilities are the second output.

**Comment by RAOMMA** [comment]
Thanks 😊😊
