### ISSUE TITLE
Facing Issues in converting Ensemble of Five algorithm

### ISSUE THREAD

**Issue by RAOMMA** [onnx/sklearn-onnx#717]
estimators_list = ['SVC', 'MNB', 'MLP', 'CNB', 'SGD']
        estimators = [('svc', text_clf_svc), ('mnb', text_clf_mnb), ('mlp', text_clf_mlp), 
                      ('cnb', text_clf_cnb), ('sgd', text_clf_sgd), ]
        
        print('Ensemble step 1')
        ### Create our voting classifier, inputting our models
        ensemble = VotingClassifier(estimators, voting='soft')

        print('Ensemble step 2')
        ### Fit model to training data   
        ensemble_start_time = datetime.datetime.now() 
        print('Ensemble start date and time: {} \n'.format(ensemble_start_time.strftime("%Y-%m-%d at %H:%M:%S")))
        ensemble.fit(X_train, y_train)
        
        initial_type = [('Input_Data', StringTensorType([None, 1]))]
        onx = convert_sklearn(ensemble, initial_types=initial_type)
        with open("rf_svc.onnx", "wb") as f:
          f.write(onx.SerializeToString())

**Error**

RuntimeError                              Traceback (most recent call last)
<ipython-input-82-0310e209baa3> in <module>()
----> 1 training(Input_data,Mapped_Konto,output_filename)

7 frames
/usr/local/lib/python3.7/dist-packages/onnxconverter_common/utils.py in check_input_and_output_types(operator, good_input_types, good_output_types)
    322                 raise RuntimeError('Operator %s (type: %s) got an input %s with a wrong type %s. Only %s are allowed'
    323                                    % (operator.full_name, operator.type, variable.full_name, type(variable.type),
--> 324                                       good_input_types))
    325 
    326     if good_output_types is not None:

RuntimeError: Operator SklearnVotingClassifier (type: SklearnVotingClassifier) got an input Input_Data with a wrong type <class 'onnxconverter_common.data_types.StringTensorType'>. Only [<class 'onnxconverter_common.data_types.BooleanTensorType'>, <class 'onnxconverter_common.data_types.DoubleTensorType'>, <class 'onnxconverter_common.data_types.FloatTensorType'>, <class 'onnxconverter_common.data_types.Int64TensorType'>] are allowed

**Comment by RAOMMA** [comment]
Hi Xadupre,
 If you have time please have a look at the file I shared in issue #712 . There is an error that occurred during runtime prediction.
Thanks in Advance

**Comment by RAOMMA** [comment]
Hi,Have you resolved issue #712 ??
If yes it is still giving same error if No then please tell till when it can be resolved.
Thanks

**Comment by xadupre** [comment]
I identified one bug which is the use of SVC or LinearSVC in CalibratedClassifierCV. I fixed LinearSVC, that leaves SVC.

**Comment by xadupre** [comment]
May I close this issue? I leave #712 open.

**Comment by RAOMMA** [comment]
Yeah Sure
