### ISSUE TITLE
unreserve_name function does not respect already declared variables

### ISSUE THREAD

**Issue by janjagusch** [onnx/sklearn-onnx#718]
I believe there is a bug in the `Scope.unreserve_name` function: It removes the name from the `Scope.onnx_variable_names` even if it is already declared in `Scope.variables`.

https://github.com/onnx/sklearn-onnx/blob/314cd07c19a78597c15c2ea10862b4e5d4318aa5/skl2onnx/common/_topology.py#L650-L658

If that happens then variables in `Scope.variables` could get overwritten. That is because the unique variable name is not taken anymore but a name-variable pair is already set in `Scope.variables`.

https://github.com/onnx/sklearn-onnx/blob/314cd07c19a78597c15c2ea10862b4e5d4318aa5/skl2onnx/common/_topology.py#L624-L628

This happened to me and was quite difficult to debug.

---

My suggested solution is to only unreserve an ONNX name, if the name is not already used in `Scope.variables`. If it is, then it should raise a warning instead of throwing an error. You could also make it throw an error, but then you'd have to fix it in `parse_sklearn` (which is I believe the only time the `unreserve_name` function is actually called):

https://github.com/onnx/sklearn-onnx/blob/314cd07c19a78597c15c2ea10862b4e5d4318aa5/skl2onnx/_parse.py#L566-L568

Another approach would be to get rid of `unreserve_name` altogether, since it's only called once and doesn't seem particularly useful. But maybe I'm mistaken here. 🙂

**Comment by janjagusch** [comment]
@xadupre, here a reproducible example for you. Short summary of what I'm doing here:

- I create a `Pipeline` object that contains a custom `Passthrough` transformer, which just passes the data without changing it.
- In the `parser` function, I create an output variable for each input variable with the same raw name as the input.
- I try to convert the pipeline to ONNX -> the conversion fails with the error mentioned above (tested with version 1.9.2).
- The same code succeeds with the changes introduced in #719.

---

```py
from typing import List

from skl2onnx.common._topology import ModelComponentContainer, Operator, Scope, Variable
from skl2onnx import get_model_alias, update_registered_converter
from skl2onnx.algebra.onnx_ops import OnnxIdentity
from skl2onnx import convert_sklearn
from onnxconverter_common.data_types import Int64TensorType
from sklearn.pipeline import Pipeline


class Passthrough:
    """Dummy sklearn transformer that illustrates the issue with unreserving ONNX names."""
    
    def fit(self, X, y=None):
        return self
    
    def transform(self, X):
        return X


def parser(
    scope: Scope, model: Passthrough, inputs: List[Variable], custom_parsers=None
):
    alias = get_model_alias(type(model))
    operator = scope.declare_local_operator(alias, model)
    operator.inputs = inputs
    for op_input in inputs:
        op_output = scope.declare_local_variable(op_input.raw_name, op_input.type)
        operator.outputs.append(op_output)
    return operator.outputs


def shape_calculator(operator: Operator):
    op_input_map = {op_input.raw_name: op_input for op_input in operator.inputs}
    for op_output in operator.outputs:
        op_output.type.shape = op_input_map[op_output.raw_name].type.shape
     
   
def converter(
    scope: Scope, operator: Operator, container: ModelComponentContainer
):
    op_input_map = {op_input.raw_name: op_input for op_input in operator.inputs}
    for op_output in operator.outputs:
        op_input = op_input_map[op_output.raw_name]
        OnnxIdentity(
            op_input,
            output_names=[op_output],
            op_version=container.target_opset,
        ).add_to(scope, container)
        

update_registered_converter(
    Passthrough,
    "Passthrough",
    shape_calculator,
    converter,
    parser=parser,
)


pipeline = Pipeline([("passthrough", Passthrough())])
initial_types = [("input", Int64TensorType([None]))]
convert_sklearn(pipeline, initial_types=initial_types)
```

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-29fe8f96108a> in <module>
----> 1 convert_sklearn(pipeline, initial_types=initial_types)

~/Projects/personal/sklearn-onnx/skl2onnx/convert.py in convert_sklearn(model, name, initial_types, doc_string, target_opset, custom_conversion_functions, custom_shape_calculators, custom_parsers, options, intermediate, white_op, black_op, final_types, dtype, verbose)
    154 
    155     # Infer variable shapes
--> 156     topology.compile()
    157 
    158     # Convert our Topology object into ONNX. The outcome is an ONNX model.

~/Projects/personal/sklearn-onnx/skl2onnx/common/_topology.py in compile(self)
   1040         here.
   1041         """
-> 1042         self._prune()
   1043         self._resolve_duplicates()
   1044         self._fix_shapes()

~/Projects/personal/sklearn-onnx/skl2onnx/common/_topology.py in _prune(self)
   1013         # Conduct a dummy evaluation of this topology. It may set all
   1014         # reachable operators evaluated and all reachable variables fed.
-> 1015         for operator in self.topological_operator_iterator():
   1016             pass
   1017 

~/Projects/personal/sklearn-onnx/skl2onnx/common/_topology.py in topological_operator_iterator(self)
    778                 for op in self.unordered_operator_iterator():
    779                     if not op.is_evaluated and op.raw_operator is not None:
--> 780                         raise RuntimeError(
    781                             "One operator was not evaluated ("
    782                             "inputs fed=%r, outputs fed=%r, op=%r)." % (

RuntimeError: One operator was not evaluated (inputs fed=False, outputs fed=False, op=Operator(type='Passthrough', onnx_name='Passthrough', inputs='input', outputs='input2', raw_operator=<__main__.Passthrough object at 0x7fb5d3f08b50>)).
```

---

Some thoughts:

I think I understand what's the point of `scope.temp()` - it allows you to parse the model without actually writing into the scope. However, `scope.temp().variables` does not equal `scope.variables`:

```py
>>> scope.variables
{'input': Variable(raw_name='input', onnx_name='input', type=Int64TensorType(shape=[None]))}
>>> scope.temp().variables
{}
```

That's why `_parse_sklearn(scope.temp(), model, inputs, custom_parsers=custom_parsers)` produces an output variable that's with an ONNX name that's already taken:

```
>>> _parse_sklearn(scope.temp(), model, inputs, custom_parsers=custom_parsers)
[Variable(raw_name='input', onnx_name='input', type=Int64TensorType(shape=[None]))]
```

Whereas `_parse_sklearn(scope, model, inputs, custom_parsers=custom_parsers)` does not:

```
>>> _parse_sklearn(scope, model, inputs, custom_parsers=custom_parsers)
[Variable(raw_name='input', onnx_name='input1', type=Int64TensorType(shape=[None]))]
```

Maybe we should use something like `deepcopy(scope)` here instead of `scope.temp()`?

https://github.com/onnx/sklearn-onnx/blob/f33fc0012b280406a18a5bdb9a03de2c2e4f251d/skl2onnx/_parse.py#L554-L555

I also think that we should add the `onnx_name` and not the `raw_name` to the `reserved` list. That is because I don't see how we can assume that the `raw_name` is unique and not already taken in the scope.

https://github.com/onnx/sklearn-onnx/blob/f33fc0012b280406a18a5bdb9a03de2c2e4f251d/skl2onnx/_parse.py#L562

**Comment by xadupre** [comment]
Thanks. I'll look into that today.

**Comment by xadupre** [comment]
The issue is due to a variable name used both for inputs and outputs. I'm not sure ONNX specifications allows this case but sklearn-onnx does not. Every name has to be unique. PR #724 fixes it. It raises a warning in that case and renames the output.

**Comment by janjagusch** [comment]
> The issue is due to a variable name used both for inputs and outputs. I'm not sure ONNX specifications allows this case but sklearn-onnx does not. Every name has to be unique. PR #724 fixes it. It raises a warning in that case and renames the output.

Thanks for getting back to me so fast @xadupre. When you say 'variable names', do you mean the `raw_name` property or the `onnx_name` property? I agree that `onnx_name`s have to be unique but I don't believe `raw_names`s have to. I also don't think this is a constraint in `sklearn-onnx` because we can declare several variables with the same `raw_name` and the `get_unique_variable_name` will create unique `onnx_name`s:

https://github.com/onnx/sklearn-onnx/blob/2fd16a0053042030f135d1c3ae43fc999eb61f92/skl2onnx/common/_topology.py#L630-L637

I don't fully understand why suddenly this would be an issue if one of the variables happened to be in input. Maybe you could help me out here. 🙁

**Comment by xadupre** [comment]
There was no test about input and output sharing the same raw_names. It is now with this PR. It is true that `get_unique_variable_name` returns a unique name. To do that it increments `i` in "name%d" % i` until it becomes unique. But input names were not added to the initial list to begin with. That's why in this particular case, the model ended up with two equal onnx_name.

**Comment by xadupre** [comment]
I think the current design is over complicated. PR #726 simplifies it. It removes reserved_names. I'll see if it is not too complicated to ix all unit tests it will probably break. parser and shape_calculator could be removed.

**Comment by xadupre** [comment]
Thanks, #726 is ready to be reviewed.
