### ISSUE TITLE
Tfidf+Classifer onnx bad input types?

### ISSUE THREAD

**Issue by WilliamTambellini** [onnx/sklearn-onnx#72]
Hi, 
I ve trained a model following the sklearn doc classification tuto : 
https://scikit-learn.org/stable/tutorial/text_analytics/working_with_text_data.html#building-a-pipeline

    cv = CountVectorizer()
    tt = TfidfTransformer()
    lsvc = LinearSVC(penalty=penalty, dual=False, tol=1e-3)
    text_clf = Pipeline([ 
        ('vect', cv),
        ('tfidf', tt),
        ('clf', lsvc),
    ])
    text_clf.fit(twenty_train.data, twenty_train.target) 
    onnx = convert_sklearn(text_clf, 
      target_opset=9, 
      name='DocClassifierCV-Tfidf-LSVC', 
      initial_types=[('input', StringType())]
      )
    with open("DocClassifierCV-Tfidf-LSVC.onnx", "wb") as f:
      f.write(onnx.SerializeToString())

When viewing the onnx with netron, the input type is indeed string.

but inference does nt seem to be possible using string input : 

    sess = rt.InferenceSession("DocClassifierCV-Tfidf-LSVC.onnx")
    label_name = sess.get_outputs()[0].name
    input_name = sess.get_inputs()[0].name
    pred_onx = sess.run([label_name],  {input_name: "hello world"}) 

RuntimeError: Input must be a list of dictionaries or a single numpy array for input 'input'.

Attaching the onnx file ...

**Comment by WilliamTambellini** [comment]
[DocClassifierCV-Tfidf-LSVC.onnx.gz](https://github.com/onnx/sklearn-onnx/files/2927989/DocClassifierCV-Tfidf-LSVC.onnx.gz)

**Comment by prabhat00155** [comment]
Sorry for the delayed response, I somehow missed this issue. As the error says, you need to pass a numpy array as input here. Also, there are some changes needed. Here is the fixed version:

from onnxmltools import save_model

cv = CountVectorizer()
tt = TfidfTransformer()
lsvc = LinearSVC(dual=False, tol=1e-3)
text_clf = Pipeline([ 
    ('vect', cv),
    ('tfidf', tt),
    ('clf', lsvc),
])
text_clf.fit(twenty_train.data, twenty_train.target) 
onnx_model = convert_sklearn(text_clf, 
  name='DocClassifierCV-Tfidf-LSVC', 
  initial_types=[('input', StringTensorType([1, 1]))]
  )

save_model(onnx_model, 'cv.onnx')
sess = InferenceSession("cv.onnx")
label_name = sess.get_outputs()[0].name
input_name = sess.get_inputs()[0].name
res = sess.run(None, input_feed={'input': np.array([['hello world']])})
