### ISSUE TITLE
Input variables are unexpectedly renamed if they are identical to output variables

### ISSUE THREAD

**Issue by cbourjau** [onnx/sklearn-onnx#767]
If input variable names are identical to output variable names, the input variable is silently renamed. This creates issues since the input name is needed to perform inferences. IMHO, this behavior should either be explicit or it should be the output variable name that gets renamed. I have created a failing test case showing the current behavior: #766

**Comment by xadupre** [comment]
I replied in #766 but the current behaviour is expected. It may have changed compare to earlier versions but the case where inputs and outputs have a name in common is rare.

**Comment by xadupre** [comment]
I'll close the issue feel free to reopen it.
