### ISSUE TITLE
Is it possible to convert a pipeline with 3 steps: pre-processing, training and post-processing into an onnx-model.

### ISSUE THREAD

**Issue by RAOMMA** [onnx/sklearn-onnx#779]

**Comment by xadupre** [comment]
It should be if you are using estimators from scikit-learn. If you are not, it usually means rewriting the inference function of some models into ONNX. I would need more information about the model to go further.

**Comment by RAOMMA** [comment]
Yes I am using scikit-learn model 
Here is the model details
[new_data.zip](https://github.com/onnx/sklearn-onnx/files/7546031/new_data.zip)

**Comment by xadupre** [comment]
Your notebook show you tried to convert into ONNX? What was the issue? You are using a multioutputclassifier. The behaviour changed in the latest version. Option zipmap was ignored. To make it consistent with other converters, zipmap is set to True by default but there is no way to represent a sequence of dictionaries in ONNX. You need to set zipmap to False. I'm currently working on this PR related to this issue: https://github.com/onnx/sklearn-onnx/pull/776.

**Comment by RAOMMA** [comment]
I just want to convert model after post processing as model given in the last cell of the code.
Can you tell me how I can convert the model after post processing or I have describe post processing in the pipelines.

**Comment by xadupre** [comment]
You mean `class get_max_vote_result(BaseEstimator):`?

**Comment by RAOMMA** [comment]
Yes

**Comment by xadupre** [comment]
sklearn-onnx will use [onnx-script](https://github.com/microsoft/onnx-script) next year. That should makes things easier.
