### ISSUE TITLE
Unable to find column name among names ['variable']. 

### ISSUE THREAD

**Issue by VanBernard** [onnx/sklearn-onnx#785]
I'm getting an error when I was trying to convert a Scikit-learn pipeline to Onnx
![error_skl2onnx](https://user-images.githubusercontent.com/14114329/142452340-b2a390b1-66c8-41fc-9d9b-0cb76f80f7c7.png)
Where the inputs are :
[('pi_data_value', DoubleTensorType(shape=[1, 1])),
 ('a', StringTensorType(shape=[1, 1])),
 ('b', StringTensorType(shape=[1, 1])),
 ('c', StringTensorType(shape=[1, 1]))]
Can anyone help me with this issue?

**Comment by xadupre** [comment]
It is possible to use sklearn-onnx directly? `from skl2onx import convert_sklearn...`. If it gives the same error, I'll need to know more about the pipeline you try to convert. You may also enable logging and copy paste the output.

```
import logging
log = logging.getLogger('skl2onnx')
log.setLevel(logging.DEBUG)
logging.basicConfig(level=logging.DEBUG)
```

**Comment by VanBernard** [comment]
I used directly the skl2onnx.convert_sklearn() and I got the same error,
here the code and the debug output:
import onnxmltools
import skl2onnx
try:
    model_onnx =  skl2onnx.convert_sklearn(model, initial_types =  inputs)
except Exception as e:
    print(e)

*log:*

DEBUG:skl2onnx:[Var] +Variable('pi_data_value', 'pi_data_value',
type=DoubleTensorType(shape=[1, 1])) DEBUG:skl2onnx:[Var] +Variable('a',
'a', type=StringTensorType(shape=[1, 1])) DEBUG:skl2onnx:[Var]
+Variable('b', 'b', type=StringTensorType(shape=[1, 1]))
DEBUG:skl2onnx:[Var] +Variable('c', 'c', type=StringTensorType(shape=[1,
1])) DEBUG:skl2onnx:[Var] update is_root=True for Variable('pi_data_value',
'pi_data_value', type=DoubleTensorType(shape=[1, 1])) DEBUG:skl2onnx:[Var]
update is_root=True for Variable('a', 'a', type=StringTensorType(shape=[1,
1])) DEBUG:skl2onnx:[Var] update is_root=True for Variable('b', 'b',
type=StringTensorType(shape=[1, 1])) DEBUG:skl2onnx:[Var] update
is_root=True for Variable('c', 'c', type=StringTensorType(shape=[1, 1]))
DEBUG:skl2onnx:[Op] +Operator(type='None', onnx_name='None', inputs='',
outputs='', raw_operator=ColumnSelector(cols=['a', 'b', 'c']))
DEBUG:skl2onnx:[Op] add In Variable('pi_data_value', 'pi_data_value',
type=DoubleTensorType(shape=[1, 1])) to Operator(type='None',
onnx_name='None', inputs='pi_data_value', outputs='',
raw_operator=ColumnSelector(cols=['a', 'b', 'c'])) DEBUG:skl2onnx:[Op] add
In Variable('a', 'a', type=StringTensorType(shape=[1, 1])) to
Operator(type='None', onnx_name='None', inputs='pi_data_value,a',
outputs='', raw_operator=ColumnSelector(cols=['a', 'b', 'c']))
DEBUG:skl2onnx:[Op] add In Variable('b', 'b',
type=StringTensorType(shape=[1, 1])) to Operator(type='None',
onnx_name='None', inputs='pi_data_value,a,b', outputs='',
raw_operator=ColumnSelector(cols=['a', 'b', 'c'])) DEBUG:skl2onnx:[Op] add
In Variable('c', 'c', type=StringTensorType(shape=[1, 1])) to
Operator(type='None', onnx_name='None', inputs='pi_data_value,a,b,c',
outputs='', raw_operator=ColumnSelector(cols=['a', 'b', 'c']))
DEBUG:skl2onnx:[Var] +Variable('variable', 'variable',
type=DoubleTensorType(shape=[])) DEBUG:skl2onnx:[Var] set parent for
Variable('variable', 'variable', type=DoubleTensorType(shape=[])),
parent=Operator(type='None', onnx_name='None',
inputs='pi_data_value,a,b,c', outputs='',
raw_operator=ColumnSelector(cols=['a', 'b', 'c'])) DEBUG:skl2onnx:[Op] add
Out Variable('variable', 'variable', type=DoubleTensorType(shape=[])) to
Operator(type='None', onnx_name='None', inputs='pi_data_value,a,b,c',
outputs='variable', raw_operator=ColumnSelector(cols=['a', 'b', 'c']))
Unable to find column name 'a' among names ['variable']. Make sure the
input names specified with parameter initial_types fits the column names
specified in the pipeline to convert.

Thanks in advance.

**Comment by xadupre** [comment]
Are you using ColumnSelector from mlxtend? There is no unit test about that as it is not in scikit-learn.

**Comment by VanBernard** [comment]
I used the databricks automl :



*from databricks import automlsummary = automl.regress(df_raw,
target_col=tg, timeout_minutes=5)model_uri = summary.best_trial.model_path*

*import mlflowmodel = mlflow.sklearn.load_model(model_uri)*
It produced the next pipeline:
[image: image.png]
Is it mean that it is not possible to use automl to generate a Onnx file?
 I'm not sure how to solve it...

**Comment by xadupre** [comment]
I was able to replicate your issue by using one unit test implemented in automl. The current error message is confusing but it comes from the fact ColumnSelector has no implemented converter. This transformer could be easily replaced by a ColumnTransformer with the latest versions of scikit-learn. automl includes models dealing with timeseries and there is no converter for such models, even in scikit-learn. I don't know how function `automl.regress` works and I'm not sure it would be easy to implement a mechanism which works in all cases. I would need an example I can run to see what I can do.

**Comment by VanBernard** [comment]
*Thank you so much for your help, I will try by this way... :)*

**Comment by xadupre** [comment]
I'll close the issue. Feel free to reopen it.
