### ISSUE TITLE
Possible error in shape inference of sub-graph for conversion of sklearn.gaussian_process.GaussianProcessRegressor()

### ISSUE THREAD

**Issue by tsimpkin** [onnx/sklearn-onnx#789]
Possibly something related to https://github.com/onnx/sklearn-onnx/issues/482

Transferring issue from onnxruntime board (https://github.com/microsoft/onnxruntime/issues/9808#issue-1057986666):

**Describe the bug**
When trying to get output predictions from an inference session with a model that uses the SKLearn Gaussian Process Regressor, I get the following error message:

onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Scan node. Name:'Sc_Scan' Status Message: Subgraph must have the shape set for all outputs but next_out did not.

I initially thought this was an issue with the runtime, as the opset checks were fine.

**System information**

    OS Platform and Distribution: Windows 10
    ONNX Runtime installed from: pypi
    ONNX Runtime version: 1.9.0
    Python version: 3.7.9
    SKLearn version: 1.0.1

**To Reproduce**
Train any model using sklearn.gaussian_process.GaussianProcessRegressor() and try to output predictions from onnxruntime inference session.

    Describe steps/code to reproduce the behavior.
    I first observed it when it was part of a stacking regressor model, but double checked it as a standalone as well. Here's a brief script to reproduce:

import numpy as np
from sklearn.datasets import make_regression
from sklearn.gaussian_process import GaussianProcessRegressor as GPR
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import make_pipeline
import onnxruntime as rt
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType

#Create and prepare data.
n_samples, n_features = 10000, 10
X, y = make_regression(n_samples, n_features)  
tx1,vx1,ty1,vy1 = train_test_split(X, y)

#Define model with scaling.
model = GPR()
pipe = make_pipeline(MinMaxScaler(feature_range=(-1, 1)), model)
pipe.fit(tx1, ty1)

#Convert to onnx and run predictions.
initial_type=[('data_in', FloatTensorType([None, X.shape[1]]))]
onx = convert_sklearn(pipe, initial_types=initial_type)
sess = rt.InferenceSession(onx.SerializeToString())
pred_ort = sess.run(None, {'data_in': vx1.astype(np.float32)})[0]

#Show output for comparison.
print(pred_ort[:10])
print(vy1[:10])

**Expected behavior**
This should output both predicted and actual values for comparison.

**Comment by xadupre** [comment]
Thanks for creating this issue. There was two issues, one in MinMaxScaler, another one in GaussianProcessRegressor. The first one needs a fix. The second one fails on last version of onnxruntime (due to shape inference). This could be avoided by using custom operator CDist (`convert_sklearn(..., options={GaussianProcessRegressor: {'optim': 'cdist'}})`). I'll probably publish a new release soon.

**Comment by xadupre** [comment]
The PR was merged. I'll close the issue. Fill free to reopen it.
