### ISSUE TITLE
Different Input Types

### ISSUE THREAD

**Issue by muzaffersenkal** [onnx/sklearn-onnx#804]
Hi  everyone,

I am trying to convert my linear model to onnx without scikit-learn pipeline. In my case,  there are float and integer column types in my dataframe. I adapted it to my own code using the document [here](http://onnx.ai/sklearn-onnx/auto_examples/plot_intermediate_outputs.html#id3).
```python
initial_types = [('float_0', FloatTensorType(shape=[None, 1])),
 ('integer_1', Int32TensorType(shape=[None, 2])),
 ('float_2', FloatTensorType(shape=[None, 1]))]


onx = convert_sklearn(linear_model, initial_types= initial_types)
with open("model.onnx", "wb") as f:
    f.write(onx.SerializeToString())
```

`RuntimeError: For operator SklearnLinearClassifier (type: SklearnLinearClassifier), at most 1 input(s) is(are) supported but we got 3 output(s) which are ['float_0', 'integer_1', 'float_2']
`

However, I am getting an error. 

Does SklearnLinearClassifier take only one input? Why can't I define different types of inputs? 
Can you help identify the problem here, and how can I solve it?

Thank you for your help in advance.

**Comment by xadupre** [comment]
scikit-learn casts casting every input into float without saying it. A linear classifier is equivalent to a matrix multiplication. You should convert your model with a single vector of 4 columns.

**Comment by muzaffersenkal** [comment]
> scikit-learn casts casting every input into float without saying it. A linear classifier is equivalent to a matrix multiplication. You should convert your model with a single vector of 4 columns.

I see, thank you.  I am asking to make sure, does it convert categorical type to float as well? And is this conversion same for all models under the sckit-learn?  I am really appreciate it for your response.

**Comment by xadupre** [comment]
Most of the predictors work with floats. Every time a model needs a gradient, it requires floats. categories are implicitely cast into float.
