### ISSUE TITLE
Load model from pipeline_xgboost.onnx failed

### ISSUE THREAD

**Issue by webstruck** [onnx/sklearn-onnx#829]
I'm trying to convert and run inference on XGBoost model. But I get similar error below which I could also reproduce using the code from [official tutorial](http://onnx.ai/sklearn-onnx/auto_examples/plot_pipeline_xgboost.html)

Exception has occurred: Fail
[ONNXRuntimeError] : 1 : FAIL : Load model from pipeline_xgboost.onnx failed:/onnxruntime_src/onnxruntime/core/graph/model_load_utils.h:47 void onnxruntime::model_load_utils::ValidateOpsetForDomain(const std::unordered_map<std::basic_string<char>, int>&, const onnxruntime::logging::Logger&, bool, const string&, int) ONNX Runtime only *guarantees* support for models stamped with official released onnx opset versions. Opset 3 is under development and support for this is limited. The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain ai.onnx.ml is till opset 2.
  File "/ml/workdir/interop/xgboost_test.py", line 53, in <module>
    sess = rt.InferenceSession("pipeline_xgboost.onnx", providers=["CPUExecutionProvider"])

### Environment

numpy: 1.21.5
scikit-learn: 1.0.2
onnx:  1.11.0
onnxruntime:  1.10.0
skl2onnx:  1.10.4
onnxconverter_common 1.9.0
onnxmltools 1.10.0

**Comment by xadupre** [comment]
I introduced new versions of TreeEnsembleRegressor in onnx 1.11 to support double coefficients. Lastest version of domain ai.onnx.ml is now 3 and this is the one chosen by default. But the code was not updated yet for this change. I modified the example to let the converter know opset 2 for domain ai.onnx.ml needs to be used.

**Comment by webstruck** [comment]
@xadupre Which part of code is updated? I don't see any change in the online tutorial.

**Comment by xadupre** [comment]
The online documentation is not yet updated. But the needed change is this one: https://github.com/onnx/sklearn-onnx/pull/831/files#diff-202b6f6c9e0dcba4019ecc0c9ee184beea1f5c8b20f7604c3ebc70996e774521L63.

**Comment by webstruck** [comment]
Ahh, got it, thanks!
