### ISSUE TITLE
Load IsolationForest model failed 

### ISSUE THREAD

**Issue by julien-blanchon** [onnx/sklearn-onnx#833]
I'm trying to convert, store and then load an IsolationForest model, but the load part failed and raised an `ONNXRuntimeError`:
```raw
Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from ./isolation.onnx failed:/onnxruntime_src/onnxruntime/core/graph/model_load_utils.h:47 void onnxruntime::model_load_utils::ValidateOpsetForDomain(const std::unordered_map<std::basic_string<char>, int>&, const onnxruntime::logging::Logger&, bool, const string&, int) ONNX Runtime only *guarantees* support for models stamped with official released onnx opset versions. Opset 3 is under development and support for this is limited. The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain ai.onnx.ml is till opset 2.
```
My model convertion to ONNX is done with:
```python
initial_type = [('float_input', FloatTensorType([None, 64]))] # batch_size * features_size(==64)
onx = convert_sklearn(clf, initial_types=initial_type, verbose=3, target_opset=12)
with open("./isolation.onnx", "wb") as f:
    f.write(onx.SerializeToString())
```
And then I load my onnx graph with:
```python
# Compute the prediction with ONNX Runtime
sess = rt.InferenceSession("./isolation.onnx", providers=['CPUExecutionProvider'])
```
-------------------------------------

Seems to be similar to https://github.com/onnx/sklearn-onnx/issues/829

**Comment by julien-blanchon** [comment]
By forcing an opset 2 for "ai.onnx.ml" (`onx = convert_sklearn(clf, initial_types=initial_type, verbose=3, target_opset={'': 12, 'ai.onnx.ml': 2})`):
```raw
RuntimeError: Opset number 3 is higher than targeted opsets {'': 12, 'ai.onnx.ml': 2} for node type 'TreeEnsembleRegressor' name='node_sample0_TreeEnsembleRegressor' input=['node_sample0_output0'] output=['node_sample0_Y0'] (domain='ai.onnx.ml').
```

Look like TreeEnsembleRegressor need at least 3 or higher. But at the load ONNXRuntimeError want 2 or lower

**Comment by xadupre** [comment]
Did you use the version from master branch or the released version?

**Comment by julien-blanchon** [comment]
Released version, I'm trying out with master branch version

**Comment by julien-blanchon** [comment]
Still don't work with:
```raw
onnx                          1.11.0
onnxconverter-common          1.9.0
onnxruntime-gpu               1.10.0
skl2onnx                      1.11
```
`skl2onnx` from `pip install git+https://github.com/onnx/sklearn-onnx.git`

**Comment by xadupre** [comment]
I was not able to replicate. I created a PR with a change which could possibly fix your issue. Otherwise, is it possible to enable the logging to see what happens?

```
import logging
logger = logging.getLogger('skl2onnx')
logger.setLevel(logging.DEBUG)
logging.basicConfig(level=logging.DEBUG)
```

**Comment by julien-blanchon** [comment]
Yes, It's fix now, work like a charm with github.com/xadupre/sklearn-onnx (and now also this repo). We can now export with opset `{'': 12, 'ai.onnx.ml': 2}` and so import it with the latest release version of onnxruntime.

Thanks you very much, I appreciate your work and your online teaching resources :)

One question as I'm here, sklearn-onnx export the whole computational graph (ie the full .predict function), but for my usage it's quite better to only export the IsolationForest decision function (ie the .decision_function) before the threshold operation. What's the most canonical way of doing: 
- Cut the onnx graph before the threshold operation (in Python) and then export the Serialized model. 
- Or adapt sklearn-onnx to export decision_function instead (or both) of full predict function

**Comment by xadupre** [comment]
Short term solution: you can check the list of available options for all converters here: https://onnx.ai/sklearn-onnx/auto_tutorial/plot_dbegin_options.html#list-of-available-options. Otherwise, you can use this function [select_model_inputs_outputs](https://onnx.ai/sklearn-onnx/api_summary.html?highlight=select#skl2onnx.helpers.onnx_helper.select_model_inputs_outputs) to select the nodes you need to promote as outputs or this one [select_model_inputs_outputs](http://www.xavierdupre.fr/app/mlprodict/helpsphinx/mlprodict/onnx_tools/onnx_manipulations.html#mlprodict.onnx_tools.onnx_manipulations.select_model_inputs_outputs) in a package where I implemented many tools.

Other option, add an option to export that method but that requires an easy code change.

**Comment by julien-blanchon** [comment]
Thanks, as I looked at the graph it seems that there are already 2 output node for IsolationForest, `label` which is the thresholded score (.predict output) and `scores` which is the raw score (.decision_function). So I just need to select the "scores" output in my Session run. So the feature is already implemented.

I suppose this issues is now closed. Have a nice day !
