### ISSUE TITLE
Conversion of PyMorphy2 preprocessing to ONNX

### ISSUE THREAD

**Issue by kos345** [onnx/sklearn-onnx#841]
Hello.
Could you help with Conversion of PyMorphy2 preprocessing to ONNX, please?
I've created custom class with method that does some text preprocessing (using re.sub()) and then lemmatizes the text using PyMorphy2.
I use this custom class in TfidfVectorizer as preprocessor parameter. When I try to convert pipeline with this TfidfVectorizer I get NotImplementedError: Custom preprocessor cannot be converted into ONNX.
Could you help, how I can convert this custom preprocessor to ONNX?

**Comment by xiaowuhu** [comment]
@kos345 is this problem still block you? if not, we will close this issue after few days.
