### ISSUE TITLE
SGDOneClassSVM converter

### ISSUE THREAD

**Issue by julien-blanchon** [onnx/sklearn-onnx#853]
Look like we still don't have any exporter for the SGDOneClassSVM operator

**Comment by julien-blanchon** [comment]
I'm not very familiar with the sklearn-onnx exporting process. According to this blog post it's missing a `_shape_calculator` and `_converter` and adding it to the register (`register_converter`). Any clues on this ?

**Comment by julien-blanchon** [comment]
Classical OneClassSVM still work but is practically not usable for very large dataset, so an converter for SGDOneClassSVM will be welcome

**Comment by garymm** [comment]
@xadupre can you please assign this to @xiaowuhu (I don't have permission)
