### ISSUE TITLE
MultiOutputClassifier onnx conversion gives OnnxRuntimeError :10 INVALID_GRAPH

### ISSUE THREAD

**Issue by SwatiTiwarii** [onnx/sklearn-onnx#856]
I have multiLabel data(each row is float vector of shape 6) set and i am using sklearn MultiOutputClassifier and converting that to onnx.

	pipe = Pipeline(steps=[
            ('classifier', MultiOutputClassifier(estimator=LogisticRegression()))])
	pipe.fit(traindata, trainlabel)
	y_test = pipe.predict_proba(testdata)
	final_type = [('label', Int64TensorType([1, 3])), ('output', FloatTensorType([1, 3]))] 
	onx6 = to_onnx(pipe, traindata, target_opset=12 ,final_types=final_type ,  options={MultiOutputClassifier: {'zipmap': False}})
 	sess = InferenceSession(onx6.SerializeToString())

	pred_onx = sess.run(None, {"input": testdata[:5].astype(numpy.float32)})
	print("predict", pred_onx[0])
	print("predict_proba", pred_onx[1][:1])

Above code is failing on line InferenceSession(onx6.SerializeToString()). 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py in __init__(self, path_or_bytes, sess_options, providers, provider_options, **kwargs)
    333 
    334         try:
--> 335             self._create_inference_session(providers, provider_options, disabled_optimizers)
    336         except ValueError:
    337             if self._enable_fallback:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py in _create_inference_session(self, providers, provider_options, disabled_optimizers)
    370             sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    371         else:
--> 372             sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
    373 
    374         if disabled_optimizers is None:

InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Type Error: Type 'seq(tensor(double))' of input parameter (probabilities) of operator (Cast) in node (Cast1) is invalid.

Can you please let me know hot to convert MultiOutputClassifier to onnx

onnxconverter-common               1.7.0
onnxmltools                        1.10.0
onnxruntime                        1.11.0
skl2onnx                           1.11.1

**Comment by xadupre** [comment]
The following example works. The different comes from final_type optional. The option was only tested for regressor or classifier, no multi output models. It assumes all outputs are tensors and cast them into tensors with a different element type. I assume you need to merge the sequence of probabilities into one single tensor?

```python
import numpy
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.multioutput import MultiOutputClassifier
from skl2onnx import to_onnx
from skl2onnx.common.data_types import FloatTensorType, Int64TensorType
from onnxruntime import InferenceSession


rnd = numpy.random.randn(100, 3)
labels = (rnd >= 0.5).astype(numpy.int64)

traindata = testdata = rnd
trainlabel = labels

pipe = Pipeline(steps=[
        ('classifier', MultiOutputClassifier(estimator=LogisticRegression()))])
pipe.fit(traindata, trainlabel)
y_test = pipe.predict_proba(testdata)
onx6 = to_onnx(pipe, traindata.astype(numpy.float32),
               target_opset=12,
               options={MultiOutputClassifier: {'zipmap': False}})

sess = InferenceSession(onx6.SerializeToString())

pred_onx = sess.run(None, {"X": testdata[:5].astype(numpy.float32)})
print("predict", pred_onx[0])
print("predict_proba", pred_onx[1][:1])
```

**Comment by SwatiTiwarii** [comment]
If i disable final_type option , i get following error  , why am I getting an output label of type string
---------------------------------------------------------------------------
Fail                                      Traceback (most recent call last)
<ipython-input-29-983461d8171f> in <module>
      1 from onnxruntime import InferenceSession
----> 2 sess = InferenceSession(onx6.SerializeToString())

~\AppData\Local\Continuum\anaconda3\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py in __init__(self, path_or_bytes, sess_options, providers, provider_options, **kwargs)
    333 
    334         try:
--> 335             self._create_inference_session(providers, provider_options, disabled_optimizers)
    336         except ValueError:
    337             if self._enable_fallback:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py in _create_inference_session(self, providers, provider_options, disabled_optimizers)
    370             sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    371         else:
--> 372             sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)
    373 
    374         if disabled_optimizers is None:

Fail: [ONNXRuntimeError] : 1 : FAIL : Type Error: Type (tensor(string)) of output arg (label) of node (Co_Concat) does not match expected type (tensor(int64)).

**Comment by SwatiTiwarii** [comment]
Using 
labels = label.astype(numpy.int64) , has solved this issue for me. 
Alongwith ignoring input types
