### ISSUE TITLE
Error while importing ONNX

### ISSUE THREAD

**Issue by karthikavarmar** [onnx/sklearn-onnx#870]
I installed onnx using github link and using pip also. But it is throwing the below error:

TypeError: Couldn't build proto file into descriptor pool: duplicate file name (onnx/onnx-ml.proto)

**Comment by xadupre** [comment]
Difficult to understand what is going on. Could you tell more about the OS, python version, onnx version you use?

**Comment by xadupre** [comment]
I'm closing the issue, feel free to reopen it the problem still exists.
