### ISSUE TITLE
test onnx 1.12.0 release candidate

### ISSUE THREAD

**Issue by xiaowuhu** [onnx/sklearn-onnx#876]
pip install -i https://test.pypi.org/simple/ onnx==1.12.0rc5

**Comment by garymm** [comment]
rc5 is ready now, please use that

**Comment by xiaowuhu** [comment]
onnxruntime/backend/backend/py/ line 126, cannot parse the version string like 1.12.0rc5

**Comment by xiaowuhu** [comment]
complete by: https://github.com/onnx/sklearn-onnx/pull/877
