### ISSUE TITLE
Version compatibility between ONNX runtime and skl2onnx

### ISSUE THREAD

**Issue by arunguru-msft** [onnx/sklearn-onnx#878]
We are having issues with ONNX models converted using skl2onnx 1.7.0 works, but the same model converted with skl2onnx 1.11.2 no longer works with the ONNX Runtime version 1.5.3. We are wondering if there are breaking changes in skl2onnx that they may no longer work with older versions of ONNX runtime. Can you please share any compatibility matrix that may be available for the same?

**Comment by xadupre** [comment]
Is it possible to know more about the error you get and the version of the package onnx you use? skl2onnx is able to produce model valid for older version of onnxruntime. The arguement `target_opset` must be filled with a value supported by your version of onnxruntime. You can find this information here: https://github.com/microsoft/onnxruntime/blob/master/docs/Versioning.md#version-matrix. For onnxruntime==1.5.3, it should be `target_opset=12`.

**Comment by xadupre** [comment]
May we close the issue or do you need more information about your issue?

**Comment by arunguru-msft** [comment]
Yes please, thanks you for sharing the details
