### ISSUE TITLE
Converter for BayesSearchCV

### ISSUE THREAD

**Issue by fabiogeraci** [onnx/sklearn-onnx#882]
Hello devs,

I am working on a converter for BayesSearchCV, but I getting the following error, I am not sure what I am missing, any help is appreciated.

> Error
> Traceback (most recent call last):
>   File "/home/fabio/Documents/sklearn-onnx/tests/test_sklearn_bayes_search_cv_converter.py", line 33, in test_bayes_search_binary_float
>     model_onnx = convert_sklearn(
>   File "/home/fabio/Documents/sklearn-onnx/skl2onnx/convert.py", line 174, in convert_sklearn
>     topology = parse_sklearn_model(
>   File "/home/fabio/Documents/sklearn-onnx/skl2onnx/_parse.py", line 799, in parse_sklearn_model
>     outputs = parse_sklearn(scope, model, inputs,
>   File "/home/fabio/Documents/sklearn-onnx/skl2onnx/_parse.py", line 719, in parse_sklearn
>     res = _parse_sklearn(
>   File "/home/fabio/Documents/sklearn-onnx/skl2onnx/_parse.py", line 656, in _parse_sklearn
>     outputs = sklearn_parsers_map[tmodel](scope, model, inputs,
>   File "/home/fabio/Documents/sklearn-onnx/skl2onnx/_parse.py", line 419, in _parse_sklearn_bayes_search_cv
>     options = scope.get_options(model)
>   File "/home/fabio/Documents/sklearn-onnx/skl2onnx/common/_topology.py", line 878, in get_options
>     self._get_allowed_options(model, fail=fail),
>   File "/home/fabio/Documents/sklearn-onnx/skl2onnx/common/_topology.py", line 834, in _get_allowed_options
>     raise NotImplementedError(
> NotImplementedError: No registered models, no known allowed options for model 'BayesSearchCV'.

**Comment by xiaowuhu** [comment]
@fabiogeraci  can you please share me you code which can repro this issue? so I can try to fix it.
