### ISSUE TITLE
Is PolynomialFeatures actually supported?

### ISSUE THREAD

**Issue by fmathx** [onnx/sklearn-onnx#888]
Hi,
I have been using skl2onnx for some time now but I think I must be doing something wrong. Very often I run into problems with either the skl2onnx conversion OR the resulting ONNX file being unreadable with onnxruntime, despite the fact that my model contains only operators that are listed as supported here:
https://onnx.ai/sklearn-onnx/supported.html

In the present case, my problem is with PolynomialFeatures. Here's the code that defines my pipeline (please forget about whether getting polynomialfeatures after PCA is meaningful, I'm experimenting here):

```
def define_preprocessing_pipeline(X):
    """
    Return a pipeline containing the most basic preprocessing steps:
        - standard scaling / PCA of numerical features
        - one-hot encoding of categorical features
    """
    X_columns = list(X.columns)
    scalable_columns = columns.get_scalable_columns(X_columns)
    categorical_columns = columns.get_columns_by_data_type(X_columns, columns.DataType.categorical)

    scaling_transformer = Pipeline(
        steps=[
            ("scaler", StandardScaler()),
            ("pca", PCA(n_components=len(scalable_columns))),
            ("polynomial", PolynomialFeatures(include_bias=False))
        ]
    )

    category_transformer = Pipeline(
        steps=[("onehot", OneHotEncoder(handle_unknown="ignore", sparse=False))]
    )

    preprocessor = ColumnTransformer(
        transformers=[
            ("scalable", scaling_transformer, scalable_columns),
            ("categories", category_transformer, categorical_columns)
        ],
        remainder="passthrough"
    )

    return preprocessor


preprocess_pipeline = define_preprocessing_pipeline(X_train)

final_pipeline = Pipeline(
    steps=[
        ("preprocessing", preprocess_pipeline),
        ("classifier", RandomForestClassifier(max_depth=25))
    ]
)

final_pipeline.fit(X_train, y_train)
```

This trains and predicts appropriately enough. It converts to ONNX without error too. The resulting ONNX is readable via Netron without warnings.

I use skl2onnx version 1.11.2 (after updating it. previously I was using 1.10.1 with the same result).
onnxruntime is 1.11.1
target opset is 12

If I set include_bias to False, I get this error when loading:
NotImplemented: [ONNXRuntimeError] : 9 : NOT_IMPLEMENTED : Could not find an implementation for ReduceProd(11) node with name 'ReduceProd'

Here is the netron graph:

![netron_graph](https://user-images.githubusercontent.com/107659868/179815878-05f94925-5ce8-42b7-b563-8091ace3ec64.PNG)

If I set include_bias to True, I get another error about different data types being fed to the concat operator that follows (which, after visualizing the resulting graph with Netron, shows that a separate node is created at the same level as all other polynomial features but which seems to be a shape attribute of some sort).

The first error (when include_bias is False) is what really bothers me. Anyone has any idea what the problem might be (and/or how to solve it)?

**Comment by xadupre** [comment]
How did you convert the model? onnxruntime does not implement ReduceProd for double. I assume the model works if you use float tensors as inputs.

**Comment by fmathx** [comment]
You're right. Changing my inputs definition to float got it working.
This is no good for me though, since the program I have to integrate it into (amazingly enough) cannot write floats; only doubles...

At least now I know what the problem is. Thank you.
