### ISSUE TITLE
Conversion of `GaussianProcessRegressor` with `RBF` kernel and anisotropic length scales?

### ISSUE THREAD

**Issue by whophil** [onnx/sklearn-onnx#901]
Thanks for this project!

I am testing out `sklearn-onnx` for persistence of sklearn's `GaussianProcessRegressor`.

The GPR I am testing uses a RBF kernel with anisotropic length scales. In sklearn, this is represented by a length scale which is an array.

In sklearn-onnx, it appears that conversion of kernels with array length scales is explicitly denied

https://github.com/onnx/sklearn-onnx/blob/e85674a67a0a043e19c2ffe181e5d31eca8ce40b/skl2onnx/operator_converters/_gp_kernels.py#L237-L240

Is this something that will likely be implemented in the future, or is there a deeper reason why this is not supported?

**Comment by xadupre** [comment]
The fix was merged in main branch on github and will be released with the next release.
