### ISSUE TITLE
Can onnx converted by "convert_sklearn" run on GPU?

### ISSUE THREAD

**Issue by GoHard2023** [onnx/sklearn-onnx#903]
As the title, If I convert `RandomForestClassifier` to an ONNX model, how can we run it on GPUs?

**Comment by xadupre** [comment]
It depends on the runtime you are using. onnxruntime has currently only one cpu implementation for TreeEnsembleClassifier.

**Comment by xadupre** [comment]
You could use hummingbird to convert your tree into a neural network and then run it on GPU.
