### ISSUE TITLE
Add Source Distribution to 1.12 Release

### ISSUE THREAD

**Issue by janjagusch** [onnx/sklearn-onnx#907]
Hi!

I'm part of the team maintaining the [`sklearn-onnx` Conda-Forge feedstock](https://github.com/conda-forge/skl2onnx-feedstock). In your 1.12 release, [you didn't include a source distribution file](https://pypi.org/project/skl2onnx/#files) (see 1.11 release for comparison [here](https://pypi.org/project/skl2onnx/1.11/#files)). The source distribution is also missing for 1.11.1 and 1.11.2. We cannot build Conda packages without the source distribution, so I would really appreciate it if you could still add it to those releases.

Thanks a lot in advance for your help! 🙏

**Comment by xiaowuhu** [comment]
@janjagusch sorry for the inconvenience. I just upload the tar.gz file for 1.12 release, please have a try.

**Comment by janjagusch** [comment]
Thank you, @xiaowuhu. I've added the 1.12 release [here](https://github.com/conda-forge/skl2onnx-feedstock/pull/16#event-7331988601). 🙏
