### ISSUE TITLE
Add support for QuadraticDiscriminantAnalysis model

### ISSUE THREAD

**Issue by Seanny123** [onnx/sklearn-onnx#911]
As explained in the documentation, not all sklearn models are supported. It would be helpful to add support for [`QuadraticDiscriminantAnalysis`](https://scikit-learn.org/stable/modules/generated/sklearn.discriminant_analysis.QuadraticDiscriminantAnalysis.html) which currently gives this error:

```python
MissingShapeCalculator: Unable to find a shape calculator for type 
'<class 'sklearn.discriminant_analysis.QuadraticDiscriminantAnalysis'>'.
```
In a perfect world, I would make a PR after following [the documentation for creation a custom converter](http://onnx.ai/sklearn-onnx/tutorial_2_new_converter.html). I am unlikely to have time/energy for this in the coming months. :disappointed:

**Comment by xiaowuhu** [comment]
@Seanny123 let me check the possibility. :)

**Comment by xiaowuhu** [comment]
@Seanny123 will release this converter in 1.13 in next few days.
