### ISSUE TITLE
MissingShapeCalculator: Unable to find a shape calculator for type '<class 'skforecast.ForecasterAutoreg.ForecasterAutoreg.ForecasterAutoreg'>'.

### ISSUE THREAD

**Issue by arcosmarcela** [onnx/sklearn-onnx#923]
Hi! I have this problem with my try to convert in onnx a XGBoost model when I use 
* onx = convert_sklearn(forecaster, 'PrediccionElectrica',[('input', FloatTensorType([None, 2]))]) 

MissingShapeCalculator: Unable to find a shape calculator for type '<class 'skforecast.ForecasterAutoreg.ForecasterAutoreg.ForecasterAutoreg'>'.
It usually means the pipeline being converted contains a
transformer or a predictor with no corresponding converter
implemented in sklearn-onnx. If the converted is implemented
in another library, you need to register
the converted so that it can be used by sklearn-onnx (function
update_registered_converter). If the model is not yet covered
by sklearn-onnx, you may raise an issue to
https://github.com/onnx/sklearn-onnx/issues
to get the converter implemented or even contribute to the
project. If the model is a custom model, a new converter must
be implemented. Examples can be found in the gallery.

**Comment by arcosmarcela** [comment]
and with 
onnx_model = onnxmltools.convert_xgboost(forecaster, initial_types=initial_types)
onnxmltools.utils.save_model(onnx_model, './xgboost_boston.onnx')

i have this 

ValueError: No proper operator name found for '<class 'skforecast.ForecasterAutoreg.ForecasterAutoreg.ForecasterAutoreg'>'

**Comment by xadupre** [comment]
onnxmltools or sklearn-onnx do not support this library. The prediction function must be implemented with onnx primitives in a converter. This tutorial shows what it means: https://onnx.ai/sklearn-onnx/auto_tutorial/plot_icustom_converter.html.
