### ISSUE TITLE
Missing `packaging` package dependency

### ISSUE THREAD

**Issue by Chichilele** [onnx/sklearn-onnx#928]
Platform: Ubuntu 20.04.5 LTS
python:  3.8.14

error logs: https://gist.github.com/Chichilele/e2117529ff9d5c28370bfd587fb07252 
```python
ModuleNotFoundError: No module named 'packaging'
```

installing the module fixes it. Perhaps is should be listed in the dependencies

**Comment by xiaowuhu** [comment]
Looking
