### ISSUE TITLE
'numpy.bool_' type of model.classes_

### ISSUE THREAD

**Issue by kn1kn1** [onnx/sklearn-onnx#946]
Hi Team,

As @Rohan-Kumar commented at https://github.com/onnx/sklearn-onnx/issues/476#issuecomment-762467641, 'numpy.bool_' type of model.classes_ will be supported in the future release?

Sample code to reproduce the error:
- https://drive.google.com/file/d/1x0HexgjHL4A6FfoUiScAY_-BQdC2eR_s/view?usp=sharing
- [onnx_sklearn_exp.ipynb
](https://gist.github.com/kn1kn1/133526aadf029f50fc5b97564aac29f0)

I encountered the same error as this notebook and would like to hear about it.

**Comment by kn1kn1** [comment]
Thank you for replying.
My case was [sklearn.ensemble.RandomForestClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html).

**Comment by xadupre** [comment]
Thanks, I added a unit test to cover that specific case.

**Comment by xadupre** [comment]
This should have been fixed in PR #947. Feel free to reopen this issue if that occurs again.
