### ISSUE TITLE
scikit-learn 1.2 causes bug due to n_features_ deprecated

### ISSUE THREAD

**Issue by ksaur** [onnx/sklearn-onnx#951]
Hello! scikit-learn==1.2 was released today and we are having failures due  [n_features_ is deprecated in 1.0 and will be removed in 1.2.](https://github.com/scikit-learn/scikit-learn/blob/2cf0f94f49f393d8d08dbf530cdde7e958a3ee99/sklearn/tree/_classes.py#L1054)

which causes an error on [convert_sklearn_gradient_boosting_classifier](https://github.com/onnx/sklearn-onnx/blob/3c9e0c1a757229f63b94f01cef3a51b638f91f54/skl2onnx/operator_converters/gradient_boosting.py#L36) with `x0 = np.zeros((1, op.estimators_[0, 0].n_features_))`

**Comment by xadupre** [comment]
Working on it.

**Comment by xadupre** [comment]
Your PR #952 was merged.
