### ISSUE TITLE
Not supported package adtk

### ISSUE THREAD

**Issue by ClaasWagner** [onnx/sklearn-onnx#965]
Hi,
I'm using the [adtk](https://adtk.readthedocs.io/en/stable/index.html) package to find anomalies in a time series based data set. For further steps, it is needed to convert it to onnx.
`try:
    onx = to_onnx(pipeline, x_train)
except NotImplementedError as e:
    print(e)`

`onx = to_onnx_ext(pipeline, x_train, options={PcaAD: {'zipmap': False}})`

While running this code, both times this error occures:
![image](https://user-images.githubusercontent.com/117901119/216032864-a1112992-be64-4feb-a955-8f0bed193ec1.png)
Building a custom converter as described [here](http://www.xavierdupre.fr/app/sklearn-onnx/helpsphinx/auto_examples/plot_custom_parser_alternative.html#custom-converter) did not work either, probably because it is not covered yet by skl2onnx.
Is it possible that you integrate the adtk package into skl2onnx or do you have any ideas to solve this problem?

Thanks

**Comment by xadupre** [comment]
It is supported by sklearn-onnx, you can check the documentation here: http://onnx.ai/sklearn-onnx/auto_tutorial/plot_icustom_converter.html. I can tell much more without knowing more about the model you try to convert.

**Comment by xadupre** [comment]
Closing the issue. Feel free to reopen.
