### ISSUE TITLE
How do I have a Float16 input?

### ISSUE THREAD

**Issue by SaleemAkhtarAngstrom** [onnx/sklearn-onnx#973]
I want to use a Float16 input to speed up inference, is this possible? It seems that FloatTensorType only allows Float32.

**Comment by xadupre** [comment]
True. There is no plan to support float 16 in sklearn-onnx but once the onnx graph is obtained, it can be postprocessed to replace float by float16. If you don't use trees, it should be working fine.

**Comment by xadupre** [comment]
The library is implemented to support float32 or float64. It should be too difficult to add support for float16 but it would impact many files and would require to ad many unit tests. Did you try to convert all initializers and all inputs, outputs to float16?

**Comment by SaleemAkhtarAngstrom** [comment]
Hey, thanks for the reply! I actually use lightgbm as the base model that's converted - I'm guessing f16 inputs will not work on anything tree based based on what you've said above?

**Comment by xadupre** [comment]
onnxruntime implementation does not support float16 for trees. It should be possible to use float16 but we need to update onnx standard first. Maybe a tool such as [hummingbird-ml](https://pypi.org/project/hummingbird-ml/) could help you.

**Comment by SaleemAkhtarAngstrom** [comment]
Thanks for the pointer, did give that a go but found batch size 1 cpu inference to be slower on hummingbird than onnx

**Comment by xadupre** [comment]
Closing the issue. Feel free to reopen.
