### ISSUE TITLE
Converter for Isotonic Regression

### ISSUE THREAD

**Issue by praneeth5222** [onnx/sklearn-onnx#985]
Hello
I wanted to implement sklearn [Isotonic regression](https://scikit-learn.org/stable/modules/generated/sklearn.isotonic.IsotonicRegression.html) in ONNX but unable to find a converter from sklearn-onnx. 
Can you suggest me what needs to be done?

**Comment by xadupre** [comment]
A new converter must be added to sklearn-onnx. The changes should look like the following https://github.com/onnx/sklearn-onnx/pull/945. Would you like to contribute?

**Comment by praneeth5222** [comment]
Thank you @xadupre for your response. I will get back to you when I get time to contribute.
